// generated by xtask gen-tables from exiftool -listx 13.59 — DO NOT EDIT
// (regenerate with `cargo xtask gen-tables --kind tagdef --module ID3v1_Enh \
//    --out <path>`)
// source table: ID3::v1_Enh

use crate::tagtable::{PrintConv, PrintConvHash, PrintValue, TagDef, TagId, ValueConv};

static V1_ENH_SPEED_MAP: &[(&str, PrintValue)] = &[
  ("1", PrintValue::Str("Slow")),
  ("2", PrintValue::Str("Medium")),
  ("3", PrintValue::Str("Fast")),
  ("4", PrintValue::Str("Hardcore")),
];

static V1_ENH_TITLE2: TagDef = TagDef::new("Title2", "ID3v1_Enh", ValueConv::None, PrintConv::None);
static V1_ENH_ARTIST2: TagDef =
  TagDef::new("Artist2", "ID3v1_Enh", ValueConv::None, PrintConv::None);
static V1_ENH_ALBUM2: TagDef = TagDef::new("Album2", "ID3v1_Enh", ValueConv::None, PrintConv::None);
static V1_ENH_SPEED: TagDef = TagDef::new(
  "Speed",
  "ID3v1_Enh",
  ValueConv::None,
  PrintConv::Hash(PrintConvHash::direct(&V1_ENH_SPEED_MAP)),
);
static V1_ENH_GENRE: TagDef = TagDef::new("Genre", "ID3v1_Enh", ValueConv::None, PrintConv::None);
static V1_ENH_STARTTIME: TagDef =
  TagDef::new("StartTime", "ID3v1_Enh", ValueConv::None, PrintConv::None);
static V1_ENH_ENDTIME: TagDef =
  TagDef::new("EndTime", "ID3v1_Enh", ValueConv::None, PrintConv::None);

/// `ID3::v1_Enh` (g0 `ID3`, g1 `ID3v1_Enh`) — 7 tags.
pub fn get(id: TagId) -> Option<&'static TagDef> {
  match id {
    TagId::Int(4) => Some(&V1_ENH_TITLE2),
    TagId::Int(64) => Some(&V1_ENH_ARTIST2),
    TagId::Int(124) => Some(&V1_ENH_ALBUM2),
    TagId::Int(184) => Some(&V1_ENH_SPEED),
    TagId::Int(185) => Some(&V1_ENH_GENRE),
    TagId::Int(215) => Some(&V1_ENH_STARTTIME),
    TagId::Int(221) => Some(&V1_ENH_ENDTIME),
    _ => None,
  }
}
