// generated by xtask gen-tables from exiftool -listx 13.59 — DO NOT EDIT
// (regenerate with `cargo xtask gen-tables --kind tagdef --module ID3v2_2 \
//    --out <path>`)
// source table: ID3::v2_2

use crate::tagtable::{PrintConv, PrintConvHash, PrintValue, TagDef, TagId, ValueConv};

static V2_2_PICTURETYPE_MAP: &[(&str, PrintValue)] = &[
  ("0", PrintValue::Str("Other")),
  ("1", PrintValue::Str("32x32 PNG Icon")),
  ("2", PrintValue::Str("Other Icon")),
  ("3", PrintValue::Str("Front Cover")),
  ("4", PrintValue::Str("Back Cover")),
  ("5", PrintValue::Str("Leaflet")),
  ("6", PrintValue::Str("Media")),
  ("7", PrintValue::Str("Lead Artist")),
  ("8", PrintValue::Str("Artist")),
  ("9", PrintValue::Str("Conductor")),
  ("10", PrintValue::Str("Band")),
  ("11", PrintValue::Str("Composer")),
  ("12", PrintValue::Str("Lyricist")),
  ("13", PrintValue::Str("Recording Studio or Location")),
  ("14", PrintValue::Str("Recording Session")),
  ("15", PrintValue::Str("Performance")),
  ("16", PrintValue::Str("Capture from Movie or Video")),
  ("17", PrintValue::Str("Bright(ly) Colored Fish")),
  ("18", PrintValue::Str("Illustration")),
  ("19", PrintValue::Str("Band Logo")),
  ("20", PrintValue::Str("Publisher Logo")),
];
static V2_2_COMPILATION_MAP: &[(&str, PrintValue)] =
  &[("0", PrintValue::Str("No")), ("1", PrintValue::Str("Yes"))];

static V2_2_PLAYCOUNTER: TagDef =
  TagDef::new("PlayCounter", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_COMMENT: TagDef = TagDef::new("Comment", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_GROUPING: TagDef = TagDef::new("Grouping", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_INVOLVEDPEOPLE: TagDef = TagDef::new(
  "InvolvedPeople",
  "ID3v2_2",
  ValueConv::None,
  PrintConv::None,
);
static V2_2_ITUNESU: TagDef = TagDef::new("iTunesU", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_MOVEMENTNUMBER: TagDef = TagDef::new(
  "MovementNumber",
  "ID3v2_2",
  ValueConv::None,
  PrintConv::None,
);
static V2_2_MOVEMENTNAME: TagDef =
  TagDef::new("MovementName", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_PODCAST: TagDef = TagDef::new("Podcast", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_PICTURE: TagDef = TagDef::new("Picture", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_PICTUREFORMAT: TagDef =
  TagDef::new("PictureFormat", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_PICTURETYPE: TagDef = TagDef::new(
  "PictureType",
  "ID3v2_2",
  ValueConv::None,
  PrintConv::Hash(PrintConvHash::direct(&V2_2_PICTURETYPE_MAP)),
);
static V2_2_PICTUREDESCRIPTION: TagDef = TagDef::new(
  "PictureDescription",
  "ID3v2_2",
  ValueConv::None,
  PrintConv::None,
);
static V2_2_POPULARIMETER: TagDef =
  TagDef::new("Popularimeter", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_RELATIVEVOLUMEADJUSTMENT: TagDef = TagDef::new(
  "RelativeVolumeAdjustment",
  "ID3v2_2",
  ValueConv::None,
  PrintConv::None,
);
static V2_2_ALBUM: TagDef = TagDef::new("Album", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_BEATSPERMINUTE: TagDef = TagDef::new(
  "BeatsPerMinute",
  "ID3v2_2",
  ValueConv::None,
  PrintConv::None,
);
static V2_2_COMPOSER: TagDef = TagDef::new("Composer", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_GENRE: TagDef = TagDef::new("Genre", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_COMPILATION: TagDef = TagDef::new(
  "Compilation",
  "ID3v2_2",
  ValueConv::None,
  PrintConv::Hash(PrintConvHash::direct(&V2_2_COMPILATION_MAP)),
);
static V2_2_COPYRIGHT: TagDef =
  TagDef::new("Copyright", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_DATE: TagDef = TagDef::new("Date", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_PLAYLISTDELAY: TagDef =
  TagDef::new("PlaylistDelay", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_ENCODEDBY: TagDef =
  TagDef::new("EncodedBy", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_FILETYPE: TagDef = TagDef::new("FileType", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_TIME: TagDef = TagDef::new("Time", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_INITIALKEY: TagDef =
  TagDef::new("InitialKey", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_LANGUAGE: TagDef = TagDef::new("Language", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_LENGTH: TagDef = TagDef::new("Length", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_MEDIA: TagDef = TagDef::new("Media", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_ORIGINALARTIST: TagDef = TagDef::new(
  "OriginalArtist",
  "ID3v2_2",
  ValueConv::None,
  PrintConv::None,
);
static V2_2_ORIGINALFILENAME: TagDef = TagDef::new(
  "OriginalFileName",
  "ID3v2_2",
  ValueConv::None,
  PrintConv::None,
);
static V2_2_ORIGINALLYRICIST: TagDef = TagDef::new(
  "OriginalLyricist",
  "ID3v2_2",
  ValueConv::None,
  PrintConv::None,
);
static V2_2_ORIGINALRELEASEYEAR: TagDef = TagDef::new(
  "OriginalReleaseYear",
  "ID3v2_2",
  ValueConv::None,
  PrintConv::None,
);
static V2_2_ORIGINALALBUM: TagDef =
  TagDef::new("OriginalAlbum", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_ARTIST: TagDef = TagDef::new("Artist", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_BAND: TagDef = TagDef::new("Band", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_CONDUCTOR: TagDef =
  TagDef::new("Conductor", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_INTERPRETEDBY: TagDef =
  TagDef::new("InterpretedBy", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_PARTOFSET: TagDef =
  TagDef::new("PartOfSet", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_PUBLISHER: TagDef =
  TagDef::new("Publisher", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_ISRC: TagDef = TagDef::new("ISRC", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_RECORDINGDATES: TagDef = TagDef::new(
  "RecordingDates",
  "ID3v2_2",
  ValueConv::None,
  PrintConv::None,
);
static V2_2_TRACK: TagDef = TagDef::new("Track", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_ALBUMARTISTSORTORDER: TagDef = TagDef::new(
  "AlbumArtistSortOrder",
  "ID3v2_2",
  ValueConv::None,
  PrintConv::None,
);
static V2_2_ALBUMSORTORDER: TagDef = TagDef::new(
  "AlbumSortOrder",
  "ID3v2_2",
  ValueConv::None,
  PrintConv::None,
);
static V2_2_COMPOSERSORTORDER: TagDef = TagDef::new(
  "ComposerSortOrder",
  "ID3v2_2",
  ValueConv::None,
  PrintConv::None,
);
static V2_2_SIZE: TagDef = TagDef::new("Size", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_PERFORMERSORTORDER: TagDef = TagDef::new(
  "PerformerSortOrder",
  "ID3v2_2",
  ValueConv::None,
  PrintConv::None,
);
static V2_2_ENCODERSETTINGS: TagDef = TagDef::new(
  "EncoderSettings",
  "ID3v2_2",
  ValueConv::None,
  PrintConv::None,
);
static V2_2_TITLESORTORDER: TagDef = TagDef::new(
  "TitleSortOrder",
  "ID3v2_2",
  ValueConv::None,
  PrintConv::None,
);
static V2_2_TITLE: TagDef = TagDef::new("Title", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_SUBTITLE: TagDef = TagDef::new("Subtitle", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_LYRICIST: TagDef = TagDef::new("Lyricist", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_USERDEFINEDTEXT: TagDef = TagDef::new(
  "UserDefinedText",
  "ID3v2_2",
  ValueConv::None,
  PrintConv::None,
);
static V2_2_YEAR: TagDef = TagDef::new("Year", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_LYRICS: TagDef = TagDef::new("Lyrics", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_FILEURL: TagDef = TagDef::new("FileURL", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_ARTISTURL: TagDef =
  TagDef::new("ArtistURL", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_SOURCEURL: TagDef =
  TagDef::new("SourceURL", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_COMMERCIALURL: TagDef =
  TagDef::new("CommercialURL", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_COPYRIGHTURL: TagDef =
  TagDef::new("CopyrightURL", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_PUBLISHERURL: TagDef =
  TagDef::new("PublisherURL", "ID3v2_2", ValueConv::None, PrintConv::None);
static V2_2_USERDEFINEDURL: TagDef = TagDef::new(
  "UserDefinedURL",
  "ID3v2_2",
  ValueConv::None,
  PrintConv::None,
);

/// `ID3::v2_2` (g0 `ID3`, g1 `ID3v2_2`) — 64 tags.
pub fn get(id: TagId) -> Option<&'static TagDef> {
  match id {
    TagId::Str("CNT") => Some(&V2_2_PLAYCOUNTER),
    TagId::Str("COM") => Some(&V2_2_COMMENT),
    TagId::Str("GP1") => Some(&V2_2_GROUPING),
    TagId::Str("IPL") => Some(&V2_2_INVOLVEDPEOPLE),
    TagId::Str("ITU") => Some(&V2_2_ITUNESU),
    TagId::Str("MVI") => Some(&V2_2_MOVEMENTNUMBER),
    TagId::Str("MVN") => Some(&V2_2_MOVEMENTNAME),
    TagId::Str("PCS") => Some(&V2_2_PODCAST),
    TagId::Str("PIC") => Some(&V2_2_PICTURE),
    TagId::Str("PIC-1") => Some(&V2_2_PICTUREFORMAT),
    TagId::Str("PIC-2") => Some(&V2_2_PICTURETYPE),
    TagId::Str("PIC-3") => Some(&V2_2_PICTUREDESCRIPTION),
    TagId::Str("POP") => Some(&V2_2_POPULARIMETER),
    TagId::Str("RVA") => Some(&V2_2_RELATIVEVOLUMEADJUSTMENT),
    TagId::Str("TAL") => Some(&V2_2_ALBUM),
    TagId::Str("TBP") => Some(&V2_2_BEATSPERMINUTE),
    TagId::Str("TCM") => Some(&V2_2_COMPOSER),
    TagId::Str("TCO") => Some(&V2_2_GENRE),
    TagId::Str("TCP") => Some(&V2_2_COMPILATION),
    TagId::Str("TCR") => Some(&V2_2_COPYRIGHT),
    TagId::Str("TDA") => Some(&V2_2_DATE),
    TagId::Str("TDY") => Some(&V2_2_PLAYLISTDELAY),
    TagId::Str("TEN") => Some(&V2_2_ENCODEDBY),
    TagId::Str("TFT") => Some(&V2_2_FILETYPE),
    TagId::Str("TIM") => Some(&V2_2_TIME),
    TagId::Str("TKE") => Some(&V2_2_INITIALKEY),
    TagId::Str("TLA") => Some(&V2_2_LANGUAGE),
    TagId::Str("TLE") => Some(&V2_2_LENGTH),
    TagId::Str("TMT") => Some(&V2_2_MEDIA),
    TagId::Str("TOA") => Some(&V2_2_ORIGINALARTIST),
    TagId::Str("TOF") => Some(&V2_2_ORIGINALFILENAME),
    TagId::Str("TOL") => Some(&V2_2_ORIGINALLYRICIST),
    TagId::Str("TOR") => Some(&V2_2_ORIGINALRELEASEYEAR),
    TagId::Str("TOT") => Some(&V2_2_ORIGINALALBUM),
    TagId::Str("TP1") => Some(&V2_2_ARTIST),
    TagId::Str("TP2") => Some(&V2_2_BAND),
    TagId::Str("TP3") => Some(&V2_2_CONDUCTOR),
    TagId::Str("TP4") => Some(&V2_2_INTERPRETEDBY),
    TagId::Str("TPA") => Some(&V2_2_PARTOFSET),
    TagId::Str("TPB") => Some(&V2_2_PUBLISHER),
    TagId::Str("TRC") => Some(&V2_2_ISRC),
    TagId::Str("TRD") => Some(&V2_2_RECORDINGDATES),
    TagId::Str("TRK") => Some(&V2_2_TRACK),
    TagId::Str("TS2") => Some(&V2_2_ALBUMARTISTSORTORDER),
    TagId::Str("TSA") => Some(&V2_2_ALBUMSORTORDER),
    TagId::Str("TSC") => Some(&V2_2_COMPOSERSORTORDER),
    TagId::Str("TSI") => Some(&V2_2_SIZE),
    TagId::Str("TSP") => Some(&V2_2_PERFORMERSORTORDER),
    TagId::Str("TSS") => Some(&V2_2_ENCODERSETTINGS),
    TagId::Str("TST") => Some(&V2_2_TITLESORTORDER),
    TagId::Str("TT1") => Some(&V2_2_GROUPING),
    TagId::Str("TT2") => Some(&V2_2_TITLE),
    TagId::Str("TT3") => Some(&V2_2_SUBTITLE),
    TagId::Str("TXT") => Some(&V2_2_LYRICIST),
    TagId::Str("TXX") => Some(&V2_2_USERDEFINEDTEXT),
    TagId::Str("TYE") => Some(&V2_2_YEAR),
    TagId::Str("ULT") => Some(&V2_2_LYRICS),
    TagId::Str("WAF") => Some(&V2_2_FILEURL),
    TagId::Str("WAR") => Some(&V2_2_ARTISTURL),
    TagId::Str("WAS") => Some(&V2_2_SOURCEURL),
    TagId::Str("WCM") => Some(&V2_2_COMMERCIALURL),
    TagId::Str("WCP") => Some(&V2_2_COPYRIGHTURL),
    TagId::Str("WPB") => Some(&V2_2_PUBLISHERURL),
    TagId::Str("WXX") => Some(&V2_2_USERDEFINEDURL),
    _ => None,
  }
}
