// generated by xtask gen-tables from exiftool -listx 13.59 — DO NOT EDIT
// (regenerate with `cargo xtask gen-tables --kind tagdef --module ID3v2_3 \
//    --out <path>`)
// source table: ID3::v2_3

use crate::tagtable::{PrintConv, PrintConvHash, PrintValue, TagDef, TagId, ValueConv};

static V2_3_PICTURETYPE_MAP: &[(&str, PrintValue)] = &[
  ("0", PrintValue::Str("Other")),
  ("1", PrintValue::Str("32x32 PNG Icon")),
  ("2", PrintValue::Str("Other Icon")),
  ("3", PrintValue::Str("Front Cover")),
  ("4", PrintValue::Str("Back Cover")),
  ("5", PrintValue::Str("Leaflet")),
  ("6", PrintValue::Str("Media")),
  ("7", PrintValue::Str("Lead Artist")),
  ("8", PrintValue::Str("Artist")),
  ("9", PrintValue::Str("Conductor")),
  ("10", PrintValue::Str("Band")),
  ("11", PrintValue::Str("Composer")),
  ("12", PrintValue::Str("Lyricist")),
  ("13", PrintValue::Str("Recording Studio or Location")),
  ("14", PrintValue::Str("Recording Session")),
  ("15", PrintValue::Str("Performance")),
  ("16", PrintValue::Str("Capture from Movie or Video")),
  ("17", PrintValue::Str("Bright(ly) Colored Fish")),
  ("18", PrintValue::Str("Illustration")),
  ("19", PrintValue::Str("Band Logo")),
  ("20", PrintValue::Str("Publisher Logo")),
];
static V2_3_COMPILATION_MAP: &[(&str, PrintValue)] =
  &[("0", PrintValue::Str("No")), ("1", PrintValue::Str("Yes"))];

static V2_3_PICTURE: TagDef = TagDef::new("Picture", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_PICTUREMIMETYPE: TagDef = TagDef::new(
  "PictureMIMEType",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_PICTURETYPE: TagDef = TagDef::new(
  "PictureType",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::Hash(PrintConvHash::direct(&V2_3_PICTURETYPE_MAP)),
);
static V2_3_PICTUREDESCRIPTION: TagDef = TagDef::new(
  "PictureDescription",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_COMMENT: TagDef = TagDef::new("Comment", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_GROUPING: TagDef = TagDef::new("Grouping", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_INVOLVEDPEOPLE: TagDef = TagDef::new(
  "InvolvedPeople",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_ITUNESU: TagDef = TagDef::new("iTunesU", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_MUSICCDIDENTIFIER: TagDef = TagDef::new(
  "MusicCDIdentifier",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_MOVEMENTNUMBER: TagDef = TagDef::new(
  "MovementNumber",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_MOVEMENTNAME: TagDef =
  TagDef::new("MovementName", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_OWNERSHIP: TagDef =
  TagDef::new("Ownership", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_PLAYCOUNTER: TagDef =
  TagDef::new("PlayCounter", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_PODCAST: TagDef = TagDef::new("Podcast", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_POPULARIMETER: TagDef =
  TagDef::new("Popularimeter", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_ALBUM: TagDef = TagDef::new("Album", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_BEATSPERMINUTE: TagDef = TagDef::new(
  "BeatsPerMinute",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_PODCASTCATEGORY: TagDef = TagDef::new(
  "PodcastCategory",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_COMPILATION: TagDef = TagDef::new(
  "Compilation",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::Hash(PrintConvHash::direct(&V2_3_COMPILATION_MAP)),
);
static V2_3_COMPOSER: TagDef = TagDef::new("Composer", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_GENRE: TagDef = TagDef::new("Genre", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_COPYRIGHT: TagDef =
  TagDef::new("Copyright", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_DATE: TagDef = TagDef::new("Date", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_PODCASTDESCRIPTION: TagDef = TagDef::new(
  "PodcastDescription",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_PLAYLISTDELAY: TagDef =
  TagDef::new("PlaylistDelay", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_ENCODEDBY: TagDef =
  TagDef::new("EncodedBy", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_LYRICIST: TagDef = TagDef::new("Lyricist", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_FILETYPE: TagDef = TagDef::new("FileType", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_PODCASTID: TagDef =
  TagDef::new("PodcastID", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_TIME: TagDef = TagDef::new("Time", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_TITLE: TagDef = TagDef::new("Title", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_SUBTITLE: TagDef = TagDef::new("Subtitle", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_INITIALKEY: TagDef =
  TagDef::new("InitialKey", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_PODCASTKEYWORDS: TagDef = TagDef::new(
  "PodcastKeywords",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_LANGUAGE: TagDef = TagDef::new("Language", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_LENGTH: TagDef = TagDef::new("Length", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_MEDIA: TagDef = TagDef::new("Media", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_ORIGINALALBUM: TagDef =
  TagDef::new("OriginalAlbum", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_ORIGINALFILENAME: TagDef = TagDef::new(
  "OriginalFileName",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_ORIGINALLYRICIST: TagDef = TagDef::new(
  "OriginalLyricist",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_ORIGINALARTIST: TagDef = TagDef::new(
  "OriginalArtist",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_ORIGINALRELEASEYEAR: TagDef = TagDef::new(
  "OriginalReleaseYear",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_FILEOWNER: TagDef =
  TagDef::new("FileOwner", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_ARTIST: TagDef = TagDef::new("Artist", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_BAND: TagDef = TagDef::new("Band", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_CONDUCTOR: TagDef =
  TagDef::new("Conductor", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_INTERPRETEDBY: TagDef =
  TagDef::new("InterpretedBy", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_PARTOFSET: TagDef =
  TagDef::new("PartOfSet", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_PUBLISHER: TagDef =
  TagDef::new("Publisher", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_TRACK: TagDef = TagDef::new("Track", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_RECORDINGDATES: TagDef = TagDef::new(
  "RecordingDates",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_INTERNETRADIOSTATIONNAME: TagDef = TagDef::new(
  "InternetRadioStationName",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_INTERNETRADIOSTATIONOWNER: TagDef = TagDef::new(
  "InternetRadioStationOwner",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_SIZE: TagDef = TagDef::new("Size", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_ALBUMARTISTSORTORDER: TagDef = TagDef::new(
  "AlbumArtistSortOrder",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_COMPOSERSORTORDER: TagDef = TagDef::new(
  "ComposerSortOrder",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_ISRC: TagDef = TagDef::new("ISRC", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_ENCODERSETTINGS: TagDef = TagDef::new(
  "EncoderSettings",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_USERDEFINEDTEXT: TagDef = TagDef::new(
  "UserDefinedText",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_YEAR: TagDef = TagDef::new("Year", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_TERMSOFUSE: TagDef =
  TagDef::new("TermsOfUse", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_LYRICS: TagDef = TagDef::new("Lyrics", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_COMMERCIALURL: TagDef =
  TagDef::new("CommercialURL", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_COPYRIGHTURL: TagDef =
  TagDef::new("CopyrightURL", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_PODCASTURL: TagDef =
  TagDef::new("PodcastURL", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_FILEURL: TagDef = TagDef::new("FileURL", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_ARTISTURL: TagDef =
  TagDef::new("ArtistURL", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_SOURCEURL: TagDef =
  TagDef::new("SourceURL", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_INTERNETRADIOSTATIONURL: TagDef = TagDef::new(
  "InternetRadioStationURL",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_PAYMENTURL: TagDef =
  TagDef::new("PaymentURL", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_PUBLISHERURL: TagDef =
  TagDef::new("PublisherURL", "ID3v2_3", ValueConv::None, PrintConv::None);
static V2_3_USERDEFINEDURL: TagDef = TagDef::new(
  "UserDefinedURL",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_ORIGINALRELEASETIME: TagDef = TagDef::new(
  "OriginalReleaseTime",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_ALBUMSORTORDER: TagDef = TagDef::new(
  "AlbumSortOrder",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_PERFORMERSORTORDER: TagDef = TagDef::new(
  "PerformerSortOrder",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);
static V2_3_TITLESORTORDER: TagDef = TagDef::new(
  "TitleSortOrder",
  "ID3v2_3",
  ValueConv::None,
  PrintConv::None,
);

/// `ID3::v2_3` (g0 `ID3`, g1 `ID3v2_3`) — 77 tags.
pub fn get(id: TagId) -> Option<&'static TagDef> {
  match id {
    TagId::Str("APIC") => Some(&V2_3_PICTURE),
    TagId::Str("APIC-1") => Some(&V2_3_PICTUREMIMETYPE),
    TagId::Str("APIC-2") => Some(&V2_3_PICTURETYPE),
    TagId::Str("APIC-3") => Some(&V2_3_PICTUREDESCRIPTION),
    TagId::Str("COMM") => Some(&V2_3_COMMENT),
    TagId::Str("GRP1") => Some(&V2_3_GROUPING),
    TagId::Str("IPLS") => Some(&V2_3_INVOLVEDPEOPLE),
    TagId::Str("ITNU") => Some(&V2_3_ITUNESU),
    TagId::Str("MCDI") => Some(&V2_3_MUSICCDIDENTIFIER),
    TagId::Str("MVIN") => Some(&V2_3_MOVEMENTNUMBER),
    TagId::Str("MVNM") => Some(&V2_3_MOVEMENTNAME),
    TagId::Str("OWNE") => Some(&V2_3_OWNERSHIP),
    TagId::Str("PCNT") => Some(&V2_3_PLAYCOUNTER),
    TagId::Str("PCST") => Some(&V2_3_PODCAST),
    TagId::Str("POPM") => Some(&V2_3_POPULARIMETER),
    TagId::Str("TALB") => Some(&V2_3_ALBUM),
    TagId::Str("TBPM") => Some(&V2_3_BEATSPERMINUTE),
    TagId::Str("TCAT") => Some(&V2_3_PODCASTCATEGORY),
    TagId::Str("TCMP") => Some(&V2_3_COMPILATION),
    TagId::Str("TCOM") => Some(&V2_3_COMPOSER),
    TagId::Str("TCON") => Some(&V2_3_GENRE),
    TagId::Str("TCOP") => Some(&V2_3_COPYRIGHT),
    TagId::Str("TDAT") => Some(&V2_3_DATE),
    TagId::Str("TDES") => Some(&V2_3_PODCASTDESCRIPTION),
    TagId::Str("TDLY") => Some(&V2_3_PLAYLISTDELAY),
    TagId::Str("TENC") => Some(&V2_3_ENCODEDBY),
    TagId::Str("TEXT") => Some(&V2_3_LYRICIST),
    TagId::Str("TFLT") => Some(&V2_3_FILETYPE),
    TagId::Str("TGID") => Some(&V2_3_PODCASTID),
    TagId::Str("TIME") => Some(&V2_3_TIME),
    TagId::Str("TIT1") => Some(&V2_3_GROUPING),
    TagId::Str("TIT2") => Some(&V2_3_TITLE),
    TagId::Str("TIT3") => Some(&V2_3_SUBTITLE),
    TagId::Str("TKEY") => Some(&V2_3_INITIALKEY),
    TagId::Str("TKWD") => Some(&V2_3_PODCASTKEYWORDS),
    TagId::Str("TLAN") => Some(&V2_3_LANGUAGE),
    TagId::Str("TLEN") => Some(&V2_3_LENGTH),
    TagId::Str("TMED") => Some(&V2_3_MEDIA),
    TagId::Str("TOAL") => Some(&V2_3_ORIGINALALBUM),
    TagId::Str("TOFN") => Some(&V2_3_ORIGINALFILENAME),
    TagId::Str("TOLY") => Some(&V2_3_ORIGINALLYRICIST),
    TagId::Str("TOPE") => Some(&V2_3_ORIGINALARTIST),
    TagId::Str("TORY") => Some(&V2_3_ORIGINALRELEASEYEAR),
    TagId::Str("TOWN") => Some(&V2_3_FILEOWNER),
    TagId::Str("TPE1") => Some(&V2_3_ARTIST),
    TagId::Str("TPE2") => Some(&V2_3_BAND),
    TagId::Str("TPE3") => Some(&V2_3_CONDUCTOR),
    TagId::Str("TPE4") => Some(&V2_3_INTERPRETEDBY),
    TagId::Str("TPOS") => Some(&V2_3_PARTOFSET),
    TagId::Str("TPUB") => Some(&V2_3_PUBLISHER),
    TagId::Str("TRCK") => Some(&V2_3_TRACK),
    TagId::Str("TRDA") => Some(&V2_3_RECORDINGDATES),
    TagId::Str("TRSN") => Some(&V2_3_INTERNETRADIOSTATIONNAME),
    TagId::Str("TRSO") => Some(&V2_3_INTERNETRADIOSTATIONOWNER),
    TagId::Str("TSIZ") => Some(&V2_3_SIZE),
    TagId::Str("TSO2") => Some(&V2_3_ALBUMARTISTSORTORDER),
    TagId::Str("TSOC") => Some(&V2_3_COMPOSERSORTORDER),
    TagId::Str("TSRC") => Some(&V2_3_ISRC),
    TagId::Str("TSSE") => Some(&V2_3_ENCODERSETTINGS),
    TagId::Str("TXXX") => Some(&V2_3_USERDEFINEDTEXT),
    TagId::Str("TYER") => Some(&V2_3_YEAR),
    TagId::Str("USER") => Some(&V2_3_TERMSOFUSE),
    TagId::Str("USLT") => Some(&V2_3_LYRICS),
    TagId::Str("WCOM") => Some(&V2_3_COMMERCIALURL),
    TagId::Str("WCOP") => Some(&V2_3_COPYRIGHTURL),
    TagId::Str("WFED") => Some(&V2_3_PODCASTURL),
    TagId::Str("WOAF") => Some(&V2_3_FILEURL),
    TagId::Str("WOAR") => Some(&V2_3_ARTISTURL),
    TagId::Str("WOAS") => Some(&V2_3_SOURCEURL),
    TagId::Str("WORS") => Some(&V2_3_INTERNETRADIOSTATIONURL),
    TagId::Str("WPAY") => Some(&V2_3_PAYMENTURL),
    TagId::Str("WPUB") => Some(&V2_3_PUBLISHERURL),
    TagId::Str("WXXX") => Some(&V2_3_USERDEFINEDURL),
    TagId::Str("XDOR") => Some(&V2_3_ORIGINALRELEASETIME),
    TagId::Str("XSOA") => Some(&V2_3_ALBUMSORTORDER),
    TagId::Str("XSOP") => Some(&V2_3_PERFORMERSORTORDER),
    TagId::Str("XSOT") => Some(&V2_3_TITLESORTORDER),
    _ => None,
  }
}
