// generated by xtask gen-tables from exiftool -listx 13.59 — DO NOT EDIT
// (regenerate with `cargo xtask gen-tables --kind tagdef --module ID3v2_4 \
//    --out <path>`)
// source table: ID3::v2_4

use crate::tagtable::{PrintConv, PrintConvHash, PrintValue, TagDef, TagId, ValueConv};

static V2_4_PICTURETYPE_MAP: &[(&str, PrintValue)] = &[
  ("0", PrintValue::Str("Other")),
  ("1", PrintValue::Str("32x32 PNG Icon")),
  ("2", PrintValue::Str("Other Icon")),
  ("3", PrintValue::Str("Front Cover")),
  ("4", PrintValue::Str("Back Cover")),
  ("5", PrintValue::Str("Leaflet")),
  ("6", PrintValue::Str("Media")),
  ("7", PrintValue::Str("Lead Artist")),
  ("8", PrintValue::Str("Artist")),
  ("9", PrintValue::Str("Conductor")),
  ("10", PrintValue::Str("Band")),
  ("11", PrintValue::Str("Composer")),
  ("12", PrintValue::Str("Lyricist")),
  ("13", PrintValue::Str("Recording Studio or Location")),
  ("14", PrintValue::Str("Recording Session")),
  ("15", PrintValue::Str("Performance")),
  ("16", PrintValue::Str("Capture from Movie or Video")),
  ("17", PrintValue::Str("Bright(ly) Colored Fish")),
  ("18", PrintValue::Str("Illustration")),
  ("19", PrintValue::Str("Band Logo")),
  ("20", PrintValue::Str("Publisher Logo")),
];
static V2_4_COMPILATION_MAP: &[(&str, PrintValue)] =
  &[("0", PrintValue::Str("No")), ("1", PrintValue::Str("Yes"))];

static V2_4_PICTURE: TagDef = TagDef::new("Picture", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_PICTUREMIMETYPE: TagDef = TagDef::new(
  "PictureMIMEType",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_PICTURETYPE: TagDef = TagDef::new(
  "PictureType",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::Hash(PrintConvHash::direct(&V2_4_PICTURETYPE_MAP)),
);
static V2_4_PICTUREDESCRIPTION: TagDef = TagDef::new(
  "PictureDescription",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_COMMENT: TagDef = TagDef::new("Comment", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_GROUPING: TagDef = TagDef::new("Grouping", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_ITUNESU: TagDef = TagDef::new("iTunesU", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_MUSICCDIDENTIFIER: TagDef = TagDef::new(
  "MusicCDIdentifier",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_MOVEMENTNUMBER: TagDef = TagDef::new(
  "MovementNumber",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_MOVEMENTNAME: TagDef =
  TagDef::new("MovementName", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_OWNERSHIP: TagDef =
  TagDef::new("Ownership", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_PLAYCOUNTER: TagDef =
  TagDef::new("PlayCounter", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_PODCAST: TagDef = TagDef::new("Podcast", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_POPULARIMETER: TagDef =
  TagDef::new("Popularimeter", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_RELATIVEVOLUMEADJUSTMENT: TagDef = TagDef::new(
  "RelativeVolumeAdjustment",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_ALBUM: TagDef = TagDef::new("Album", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_BEATSPERMINUTE: TagDef = TagDef::new(
  "BeatsPerMinute",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_PODCASTCATEGORY: TagDef = TagDef::new(
  "PodcastCategory",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_COMPILATION: TagDef = TagDef::new(
  "Compilation",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::Hash(PrintConvHash::direct(&V2_4_COMPILATION_MAP)),
);
static V2_4_COMPOSER: TagDef = TagDef::new("Composer", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_GENRE: TagDef = TagDef::new("Genre", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_COPYRIGHT: TagDef =
  TagDef::new("Copyright", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_ENCODINGTIME: TagDef =
  TagDef::new("EncodingTime", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_PODCASTDESCRIPTION: TagDef = TagDef::new(
  "PodcastDescription",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_PLAYLISTDELAY: TagDef =
  TagDef::new("PlaylistDelay", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_ORIGINALRELEASETIME: TagDef = TagDef::new(
  "OriginalReleaseTime",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_RECORDINGTIME: TagDef =
  TagDef::new("RecordingTime", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_RELEASETIME: TagDef =
  TagDef::new("ReleaseTime", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_TAGGINGTIME: TagDef =
  TagDef::new("TaggingTime", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_ENCODEDBY: TagDef =
  TagDef::new("EncodedBy", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_LYRICIST: TagDef = TagDef::new("Lyricist", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_FILETYPE: TagDef = TagDef::new("FileType", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_PODCASTID: TagDef =
  TagDef::new("PodcastID", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_INVOLVEDPEOPLE: TagDef = TagDef::new(
  "InvolvedPeople",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_TITLE: TagDef = TagDef::new("Title", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_SUBTITLE: TagDef = TagDef::new("Subtitle", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_INITIALKEY: TagDef =
  TagDef::new("InitialKey", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_PODCASTKEYWORDS: TagDef = TagDef::new(
  "PodcastKeywords",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_LANGUAGE: TagDef = TagDef::new("Language", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_LENGTH: TagDef = TagDef::new("Length", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_MUSICIANCREDITS: TagDef = TagDef::new(
  "MusicianCredits",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_MEDIA: TagDef = TagDef::new("Media", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_MOOD: TagDef = TagDef::new("Mood", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_ORIGINALALBUM: TagDef =
  TagDef::new("OriginalAlbum", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_ORIGINALFILENAME: TagDef = TagDef::new(
  "OriginalFileName",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_ORIGINALLYRICIST: TagDef = TagDef::new(
  "OriginalLyricist",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_ORIGINALARTIST: TagDef = TagDef::new(
  "OriginalArtist",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_FILEOWNER: TagDef =
  TagDef::new("FileOwner", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_ARTIST: TagDef = TagDef::new("Artist", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_BAND: TagDef = TagDef::new("Band", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_CONDUCTOR: TagDef =
  TagDef::new("Conductor", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_INTERPRETEDBY: TagDef =
  TagDef::new("InterpretedBy", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_PARTOFSET: TagDef =
  TagDef::new("PartOfSet", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_PRODUCEDNOTICE: TagDef = TagDef::new(
  "ProducedNotice",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_PUBLISHER: TagDef =
  TagDef::new("Publisher", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_TRACK: TagDef = TagDef::new("Track", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_INTERNETRADIOSTATIONNAME: TagDef = TagDef::new(
  "InternetRadioStationName",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_INTERNETRADIOSTATIONOWNER: TagDef = TagDef::new(
  "InternetRadioStationOwner",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_ALBUMARTISTSORTORDER: TagDef = TagDef::new(
  "AlbumArtistSortOrder",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_ALBUMSORTORDER: TagDef = TagDef::new(
  "AlbumSortOrder",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_COMPOSERSORTORDER: TagDef = TagDef::new(
  "ComposerSortOrder",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_PERFORMERSORTORDER: TagDef = TagDef::new(
  "PerformerSortOrder",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_TITLESORTORDER: TagDef = TagDef::new(
  "TitleSortOrder",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_ISRC: TagDef = TagDef::new("ISRC", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_ENCODERSETTINGS: TagDef = TagDef::new(
  "EncoderSettings",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_SETSUBTITLE: TagDef =
  TagDef::new("SetSubtitle", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_USERDEFINEDTEXT: TagDef = TagDef::new(
  "UserDefinedText",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_TERMSOFUSE: TagDef =
  TagDef::new("TermsOfUse", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_LYRICS: TagDef = TagDef::new("Lyrics", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_COMMERCIALURL: TagDef =
  TagDef::new("CommercialURL", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_COPYRIGHTURL: TagDef =
  TagDef::new("CopyrightURL", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_PODCASTURL: TagDef =
  TagDef::new("PodcastURL", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_FILEURL: TagDef = TagDef::new("FileURL", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_ARTISTURL: TagDef =
  TagDef::new("ArtistURL", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_SOURCEURL: TagDef =
  TagDef::new("SourceURL", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_INTERNETRADIOSTATIONURL: TagDef = TagDef::new(
  "InternetRadioStationURL",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);
static V2_4_PAYMENTURL: TagDef =
  TagDef::new("PaymentURL", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_PUBLISHERURL: TagDef =
  TagDef::new("PublisherURL", "ID3v2_4", ValueConv::None, PrintConv::None);
static V2_4_USERDEFINEDURL: TagDef = TagDef::new(
  "UserDefinedURL",
  "ID3v2_4",
  ValueConv::None,
  PrintConv::None,
);

/// `ID3::v2_4` (g0 `ID3`, g1 `ID3v2_4`) — 84 tags.
pub fn get(id: TagId) -> Option<&'static TagDef> {
  match id {
    TagId::Str("APIC") => Some(&V2_4_PICTURE),
    TagId::Str("APIC-1") => Some(&V2_4_PICTUREMIMETYPE),
    TagId::Str("APIC-2") => Some(&V2_4_PICTURETYPE),
    TagId::Str("APIC-3") => Some(&V2_4_PICTUREDESCRIPTION),
    TagId::Str("COMM") => Some(&V2_4_COMMENT),
    TagId::Str("GRP1") => Some(&V2_4_GROUPING),
    TagId::Str("ITNU") => Some(&V2_4_ITUNESU),
    TagId::Str("MCDI") => Some(&V2_4_MUSICCDIDENTIFIER),
    TagId::Str("MVIN") => Some(&V2_4_MOVEMENTNUMBER),
    TagId::Str("MVNM") => Some(&V2_4_MOVEMENTNAME),
    TagId::Str("OWNE") => Some(&V2_4_OWNERSHIP),
    TagId::Str("PCNT") => Some(&V2_4_PLAYCOUNTER),
    TagId::Str("PCST") => Some(&V2_4_PODCAST),
    TagId::Str("POPM") => Some(&V2_4_POPULARIMETER),
    TagId::Str("RVA2") => Some(&V2_4_RELATIVEVOLUMEADJUSTMENT),
    TagId::Str("TALB") => Some(&V2_4_ALBUM),
    TagId::Str("TBPM") => Some(&V2_4_BEATSPERMINUTE),
    TagId::Str("TCAT") => Some(&V2_4_PODCASTCATEGORY),
    TagId::Str("TCMP") => Some(&V2_4_COMPILATION),
    TagId::Str("TCOM") => Some(&V2_4_COMPOSER),
    TagId::Str("TCON") => Some(&V2_4_GENRE),
    TagId::Str("TCOP") => Some(&V2_4_COPYRIGHT),
    TagId::Str("TDEN") => Some(&V2_4_ENCODINGTIME),
    TagId::Str("TDES") => Some(&V2_4_PODCASTDESCRIPTION),
    TagId::Str("TDLY") => Some(&V2_4_PLAYLISTDELAY),
    TagId::Str("TDOR") => Some(&V2_4_ORIGINALRELEASETIME),
    TagId::Str("TDRC") => Some(&V2_4_RECORDINGTIME),
    TagId::Str("TDRL") => Some(&V2_4_RELEASETIME),
    TagId::Str("TDTG") => Some(&V2_4_TAGGINGTIME),
    TagId::Str("TENC") => Some(&V2_4_ENCODEDBY),
    TagId::Str("TEXT") => Some(&V2_4_LYRICIST),
    TagId::Str("TFLT") => Some(&V2_4_FILETYPE),
    TagId::Str("TGID") => Some(&V2_4_PODCASTID),
    TagId::Str("TIPL") => Some(&V2_4_INVOLVEDPEOPLE),
    TagId::Str("TIT1") => Some(&V2_4_GROUPING),
    TagId::Str("TIT2") => Some(&V2_4_TITLE),
    TagId::Str("TIT3") => Some(&V2_4_SUBTITLE),
    TagId::Str("TKEY") => Some(&V2_4_INITIALKEY),
    TagId::Str("TKWD") => Some(&V2_4_PODCASTKEYWORDS),
    TagId::Str("TLAN") => Some(&V2_4_LANGUAGE),
    TagId::Str("TLEN") => Some(&V2_4_LENGTH),
    TagId::Str("TMCL") => Some(&V2_4_MUSICIANCREDITS),
    TagId::Str("TMED") => Some(&V2_4_MEDIA),
    TagId::Str("TMOO") => Some(&V2_4_MOOD),
    TagId::Str("TOAL") => Some(&V2_4_ORIGINALALBUM),
    TagId::Str("TOFN") => Some(&V2_4_ORIGINALFILENAME),
    TagId::Str("TOLY") => Some(&V2_4_ORIGINALLYRICIST),
    TagId::Str("TOPE") => Some(&V2_4_ORIGINALARTIST),
    TagId::Str("TOWN") => Some(&V2_4_FILEOWNER),
    TagId::Str("TPE1") => Some(&V2_4_ARTIST),
    TagId::Str("TPE2") => Some(&V2_4_BAND),
    TagId::Str("TPE3") => Some(&V2_4_CONDUCTOR),
    TagId::Str("TPE4") => Some(&V2_4_INTERPRETEDBY),
    TagId::Str("TPOS") => Some(&V2_4_PARTOFSET),
    TagId::Str("TPRO") => Some(&V2_4_PRODUCEDNOTICE),
    TagId::Str("TPUB") => Some(&V2_4_PUBLISHER),
    TagId::Str("TRCK") => Some(&V2_4_TRACK),
    TagId::Str("TRSN") => Some(&V2_4_INTERNETRADIOSTATIONNAME),
    TagId::Str("TRSO") => Some(&V2_4_INTERNETRADIOSTATIONOWNER),
    TagId::Str("TSO2") => Some(&V2_4_ALBUMARTISTSORTORDER),
    TagId::Str("TSOA") => Some(&V2_4_ALBUMSORTORDER),
    TagId::Str("TSOC") => Some(&V2_4_COMPOSERSORTORDER),
    TagId::Str("TSOP") => Some(&V2_4_PERFORMERSORTORDER),
    TagId::Str("TSOT") => Some(&V2_4_TITLESORTORDER),
    TagId::Str("TSRC") => Some(&V2_4_ISRC),
    TagId::Str("TSSE") => Some(&V2_4_ENCODERSETTINGS),
    TagId::Str("TSST") => Some(&V2_4_SETSUBTITLE),
    TagId::Str("TXXX") => Some(&V2_4_USERDEFINEDTEXT),
    TagId::Str("USER") => Some(&V2_4_TERMSOFUSE),
    TagId::Str("USLT") => Some(&V2_4_LYRICS),
    TagId::Str("WCOM") => Some(&V2_4_COMMERCIALURL),
    TagId::Str("WCOP") => Some(&V2_4_COPYRIGHTURL),
    TagId::Str("WFED") => Some(&V2_4_PODCASTURL),
    TagId::Str("WOAF") => Some(&V2_4_FILEURL),
    TagId::Str("WOAR") => Some(&V2_4_ARTISTURL),
    TagId::Str("WOAS") => Some(&V2_4_SOURCEURL),
    TagId::Str("WORS") => Some(&V2_4_INTERNETRADIOSTATIONURL),
    TagId::Str("WPAY") => Some(&V2_4_PAYMENTURL),
    TagId::Str("WPUB") => Some(&V2_4_PUBLISHERURL),
    TagId::Str("WXXX") => Some(&V2_4_USERDEFINEDURL),
    TagId::Str("XDOR") => Some(&V2_4_ORIGINALRELEASETIME),
    TagId::Str("XSOA") => Some(&V2_4_ALBUMSORTORDER),
    TagId::Str("XSOP") => Some(&V2_4_PERFORMERSORTORDER),
    TagId::Str("XSOT") => Some(&V2_4_TITLESORTORDER),
    _ => None,
  }
}
