// SPDX-License-Identifier: GPL-3.0-or-later
// exifast — a 1:1 Rust port of ExifTool (Phil Harvey). See THIRD_PARTY.md.
//
// GENERATED by tools/gen_mng_tables.pl from `Image::ExifTool::MNG` (`MNG.pm`,
// $VERSION 1.00). DO NOT EDIT BY HAND — re-run the extractor against the bundled
// ExifTool to regenerate.
//
// `%MNG::Main` dispatches each MNG/JNG chunk to one of: a ProcessBinaryData
// sub-table (`MngSubTable`, decoded per-field), an inline `ValueConv` chunk
// (DISC/DROP/SEEK), a `Binary => 1` chunk (emitted as the `(Binary data N
// bytes …)` placeholder), or the shared PNG `pHYs` decoder (pHYg). Each
// sub-table's per-offset leaf descriptors carry the byte offset, element
// format/count, and (optional) int->label PrintConv slice (SORTED for
// `binary_search_by_key`, last-wins-deduplicated). The 5 conv-bearing fields
// are HAND-PORTED (`MngConv` / the inline-conv kinds), the rest declarative —
// see the module header for the survey-trap contract.

//! MNG/JNG chunk dispatch + ProcessBinaryData sub-table leaf descriptors,
//! mechanically transcribed from `%Image::ExifTool::MNG::*` (`MNG.pm`). See the
//! generator header for the contract.

#![allow(clippy::unreadable_literal)]

use super::{MngChunkKind, MngConv, MngFormat, MngLeafDef, MngSubTable};

/// Look up an MNG/JNG chunk's dispatch kind by its 4-byte id (binary search over
/// the sorted [`MNG_CHUNKS`]).
pub(super) fn lookup(chunk: &[u8; 4]) -> Option<MngChunkKind> {
  MNG_CHUNKS
    .binary_search_by_key(&chunk.as_slice(), |&(c, _)| c.as_slice())
    .ok()
    .and_then(|i| MNG_CHUNKS.get(i))
    .map(|&(_, kind)| kind)
}

/// The shared `%magMethod` PrintConv (6 entries, MNG.pm:349-356) —
/// referenced by MAGN `XMethod` + `YMethod`.
static MAG_METHOD: &[(i64, &str)] = &[
  (0, "No Magnification"),
  (1, "Pixel Replication"),
  (2, "Linear Interpolation"),
  (3, "Closest Pixel"),
  (4, "Color Linear Interpolation and Alpha Closest Pixel"),
  (5, "Color Closest Pixel and Alpha Linear Interpolation"),
];

/// `Background` offset 6 (`MandatoryBackground`) PrintConv (4 entries).
static MNG_BACKGROUND_6: &[(i64, &str)] = &[
  (0, "Color and Image Advisory"),
  (1, "Color Mandatory, Image Advisory"),
  (2, "Color Advisory, Image Mandatory"),
  (3, "Color and Image Mandatory"),
];

/// `Background` offset 9 (`BackgroundTiling`) PrintConv (2 entries).
static MNG_BACKGROUND_9: &[(i64, &str)] = &[(0, "No"), (1, "Yes")];

/// `BasisObject` offset 9 (`ColorType`) PrintConv (5 entries).
static MNG_BASISOBJECT_9: &[(i64, &str)] = &[
  (0, "Grayscale"),
  (2, "RGB"),
  (3, "Palette"),
  (4, "Grayscale with Alpha"),
  (6, "RGB with Alpha"),
];

/// `BasisObject` offset 10 (`Compression`) PrintConv (1 entries).
static MNG_BASISOBJECT_10: &[(i64, &str)] = &[(0, "Deflate/Inflate")];

/// `BasisObject` offset 11 (`Filter`) PrintConv (1 entries).
static MNG_BASISOBJECT_11: &[(i64, &str)] = &[(0, "Adaptive")];

/// `BasisObject` offset 12 (`Interlace`) PrintConv (2 entries).
static MNG_BASISOBJECT_12: &[(i64, &str)] = &[(0, "Noninterlaced"), (1, "Adam7 Interlace")];

/// `ClipObjects` offset 4 (`DeltaType`) PrintConv (2 entries).
static MNG_CLIPOBJECTS_4: &[(i64, &str)] = &[(0, "Absolute"), (1, "Relative")];

/// `CloneObject` offset 4 (`CloneType`) PrintConv (3 entries).
static MNG_CLONEOBJECT_4: &[(i64, &str)] = &[(0, "Full"), (1, "Parital"), (2, "Renumber object")];

/// `CloneObject` offset 7 (`LocalDeltaType`) PrintConv (2 entries).
static MNG_CLONEOBJECT_7: &[(i64, &str)] = &[(0, "Absolute"), (1, "Relative")];

/// `DeltaPNGHeader` offset 2 (`ImageType`) PrintConv (3 entries).
static MNG_DELTAPNGHEADER_2: &[(i64, &str)] = &[(0, "Unspecified"), (1, "PNG"), (2, "JNG")];

/// `DeltaPNGHeader` offset 3 (`DeltaType`) PrintConv (8 entries).
static MNG_DELTAPNGHEADER_3: &[(i64, &str)] = &[
  (0, "Full Replacement"),
  (1, "Pixel Addition"),
  (2, "Alpha Addition"),
  (3, "Color Addition"),
  (4, "Pixel Replacement"),
  (5, "Alpha Replacement"),
  (6, "Color Replacement"),
  (7, "No Change"),
];

/// `FramePriority` offset 0 (`DeltaType`) PrintConv (2 entries).
static MNG_FRAMEPRIORITY_0: &[(i64, &str)] = &[(0, "Absolute"), (1, "Relative")];

/// `JNGHeader` offset 8 (`ColorType`) PrintConv (4 entries).
static MNG_JNGHEADER_8: &[(i64, &str)] = &[
  (8, "Gray"),
  (10, "Color"),
  (12, "Gray Alpha"),
  (14, "Color Alpha"),
];

/// `JNGHeader` offset 10 (`Compression`) PrintConv (1 entries).
static MNG_JNGHEADER_10: &[(i64, &str)] = &[(8, "Huffman-coded baseline JPEG")];

/// `JNGHeader` offset 11 (`Interlace`) PrintConv (2 entries).
static MNG_JNGHEADER_11: &[(i64, &str)] = &[(0, "Sequential"), (8, "Progressive")];

/// `JNGHeader` offset 13 (`AlphaCompression`) PrintConv (2 entries).
static MNG_JNGHEADER_13: &[(i64, &str)] =
  &[(0, "MNG Grayscale IDAT"), (8, "JNG 8-bit Grayscale JDAA")];

/// `JNGHeader` offset 14 (`AlphaFilter`) PrintConv (1 entries).
static MNG_JNGHEADER_14: &[(i64, &str)] = &[(0, "Adaptive MNG (N/A for JPEG)")];

/// `JNGHeader` offset 15 (`AlphaInterlace`) PrintConv (1 entries).
static MNG_JNGHEADER_15: &[(i64, &str)] = &[(0, "Noninterlaced")];

/// `Loop` offset 5 (`TerminationCondition`) PrintConv (8 entries).
static MNG_LOOP_5: &[(i64, &str)] = &[
  (0, "Deterministic, not cacheable"),
  (1, "Decoder discretion, not cacheable"),
  (2, "User discretion, not cacheable"),
  (3, "External signal, not cacheable"),
  (4, "Deterministic, cacheable"),
  (5, "Decoder discretion, cacheable"),
  (6, "User discretion, cacheable"),
  (7, "External signal, cacheable"),
];

/// `MoveObjects` offset 4 (`DeltaType`) PrintConv (2 entries).
static MNG_MOVEOBJECTS_4: &[(i64, &str)] = &[(0, "Absolute"), (1, "Relative")];

/// `PasteImage` offset 2 (`TargetDeltaType`) PrintConv (2 entries).
static MNG_PASTEIMAGE_2: &[(i64, &str)] = &[(0, "Absolute"), (1, "Relative")];

/// `PasteImage` offset 13 (`CompositionMode`) PrintConv (3 entries).
static MNG_PASTEIMAGE_13: &[(i64, &str)] = &[(0, "Over"), (1, "Replace"), (2, "Under")];

/// `PasteImage` offset 14 (`Orientation`) PrintConv (5 entries).
static MNG_PASTEIMAGE_14: &[(i64, &str)] = &[
  (0, "Same as source"),
  (2, "Flipped left-right, then up-down"),
  (4, "Flipped left-right"),
  (6, "Flipped up-down"),
  (8, "Tiled"),
];

/// `PasteImage` offset 15 (`OffsetOrigin`) PrintConv (2 entries).
static MNG_PASTEIMAGE_15: &[(i64, &str)] = &[(0, "Desination Origin"), (1, "Target Origin")];

/// `PasteImage` offset 24 (`BoundaryOrigin`) PrintConv (2 entries).
static MNG_PASTEIMAGE_24: &[(i64, &str)] = &[(0, "Desination Origin"), (1, "Target Origin")];

/// `PromoteParent` offset 2 (`FillMethod`) PrintConv (2 entries).
static MNG_PROMOTEPARENT_2: &[(i64, &str)] = &[(0, "Bit Replication"), (1, "Zero Fill")];

/// `TerminationAction` offset 0 (`TerminationAction`) PrintConv (4 entries).
static MNG_TERMINATIONACTION_0: &[(i64, &str)] = &[
  (0, "Show Last Frame"),
  (1, "Display Nothing"),
  (2, "Show First Frame"),
  (3, "Repeat Sequence"),
];

/// `TerminationAction` offset 1 (`IterationEndAction`) PrintConv (3 entries).
static MNG_TERMINATIONACTION_1: &[(i64, &str)] = &[
  (0, "Show Last Frame"),
  (1, "Display Nothing"),
  (2, "Show First Frame"),
];

/// `MNG::Background` ProcessBinaryData leaves (table FORMAT int8u, increment 1).
static MNG_LEAVES_BACKGROUND: &[MngLeafDef] = &[
  MngLeafDef::new(
    0,
    "BackgroundColor",
    MngFormat::Int16u,
    3,
    None,
    MngConv::None,
  ),
  MngLeafDef::new(
    6,
    "MandatoryBackground",
    MngFormat::Int8u,
    1,
    Some(MNG_BACKGROUND_6),
    MngConv::None,
  ),
  MngLeafDef::new(
    7,
    "BackgroundImageID",
    MngFormat::Int16u,
    1,
    None,
    MngConv::None,
  ),
  MngLeafDef::new(
    9,
    "BackgroundTiling",
    MngFormat::Int8u,
    1,
    Some(MNG_BACKGROUND_9),
    MngConv::None,
  ),
];
/// `MNG::Background` ProcessBinaryData sub-table (increment 1).
static MNG_SUB_BACKGROUND: MngSubTable = MngSubTable::new(1, MNG_LEAVES_BACKGROUND);

/// `MNG::BasisObject` ProcessBinaryData leaves (table FORMAT int8u, increment 1).
static MNG_LEAVES_BASISOBJECT: &[MngLeafDef] = &[
  MngLeafDef::new(0, "ImageWidth", MngFormat::Int32u, 1, None, MngConv::None),
  MngLeafDef::new(4, "ImageHeight", MngFormat::Int32u, 1, None, MngConv::None),
  MngLeafDef::new(8, "BitDepth", MngFormat::Int8u, 1, None, MngConv::None),
  MngLeafDef::new(
    9,
    "ColorType",
    MngFormat::Int8u,
    1,
    Some(MNG_BASISOBJECT_9),
    MngConv::None,
  ),
  MngLeafDef::new(
    10,
    "Compression",
    MngFormat::Int8u,
    1,
    Some(MNG_BASISOBJECT_10),
    MngConv::None,
  ),
  MngLeafDef::new(
    11,
    "Filter",
    MngFormat::Int8u,
    1,
    Some(MNG_BASISOBJECT_11),
    MngConv::None,
  ),
  MngLeafDef::new(
    12,
    "Interlace",
    MngFormat::Int8u,
    1,
    Some(MNG_BASISOBJECT_12),
    MngConv::None,
  ),
  MngLeafDef::new(13, "RedSample", MngFormat::Int32u, 1, None, MngConv::None),
  MngLeafDef::new(17, "GreenSample", MngFormat::Int32u, 1, None, MngConv::None),
  MngLeafDef::new(21, "BlueSample", MngFormat::Int32u, 1, None, MngConv::None),
  MngLeafDef::new(25, "AlphaSample", MngFormat::Int32u, 1, None, MngConv::None),
  MngLeafDef::new(26, "Viewable", MngFormat::Int8u, 1, None, MngConv::None),
];
/// `MNG::BasisObject` ProcessBinaryData sub-table (increment 1).
static MNG_SUB_BASISOBJECT: MngSubTable = MngSubTable::new(1, MNG_LEAVES_BASISOBJECT);

/// `MNG::ClipObjects` ProcessBinaryData leaves (table FORMAT int8u, increment 1).
static MNG_LEAVES_CLIPOBJECTS: &[MngLeafDef] = &[
  MngLeafDef::new(0, "FirstObject", MngFormat::Int16u, 1, None, MngConv::None),
  MngLeafDef::new(2, "LastObject", MngFormat::Int16u, 1, None, MngConv::None),
  MngLeafDef::new(
    4,
    "DeltaType",
    MngFormat::Int8u,
    1,
    Some(MNG_CLIPOBJECTS_4),
    MngConv::None,
  ),
  MngLeafDef::new(5, "ClipBoundary", MngFormat::Int32u, 4, None, MngConv::None),
];
/// `MNG::ClipObjects` ProcessBinaryData sub-table (increment 1).
static MNG_SUB_CLIPOBJECTS: MngSubTable = MngSubTable::new(1, MNG_LEAVES_CLIPOBJECTS);

/// `MNG::CloneObject` ProcessBinaryData leaves (table FORMAT int8u, increment 1).
static MNG_LEAVES_CLONEOBJECT: &[MngLeafDef] = &[
  MngLeafDef::new(0, "SourceID", MngFormat::Int16u, 1, None, MngConv::None),
  MngLeafDef::new(2, "CloneID", MngFormat::Int16u, 1, None, MngConv::None),
  MngLeafDef::new(
    4,
    "CloneType",
    MngFormat::Int8u,
    1,
    Some(MNG_CLONEOBJECT_4),
    MngConv::None,
  ),
  MngLeafDef::new(5, "DoNotShow", MngFormat::Int8u, 1, None, MngConv::None),
  MngLeafDef::new(6, "ConcreteFlag", MngFormat::Int8u, 1, None, MngConv::None),
  MngLeafDef::new(
    7,
    "LocalDeltaType",
    MngFormat::Int8u,
    1,
    Some(MNG_CLONEOBJECT_7),
    MngConv::None,
  ),
  MngLeafDef::new(8, "DeltaXY", MngFormat::Int32u, 2, None, MngConv::None),
];
/// `MNG::CloneObject` ProcessBinaryData sub-table (increment 1).
static MNG_SUB_CLONEOBJECT: MngSubTable = MngSubTable::new(1, MNG_LEAVES_CLONEOBJECT);

/// `MNG::DefineObject` ProcessBinaryData leaves (table FORMAT int8u, increment 1).
static MNG_LEAVES_DEFINEOBJECT: &[MngLeafDef] = &[
  MngLeafDef::new(0, "ObjectID", MngFormat::Int16u, 1, None, MngConv::None),
  MngLeafDef::new(2, "DoNotShow", MngFormat::Int8u, 1, None, MngConv::None),
  MngLeafDef::new(3, "ConcreteFlag", MngFormat::Int8u, 1, None, MngConv::None),
  MngLeafDef::new(4, "XYLocation", MngFormat::Int32u, 2, None, MngConv::None),
  MngLeafDef::new(
    12,
    "ClippingBoundary",
    MngFormat::Int32u,
    4,
    None,
    MngConv::None,
  ),
];
/// `MNG::DefineObject` ProcessBinaryData sub-table (increment 1).
static MNG_SUB_DEFINEOBJECT: MngSubTable = MngSubTable::new(1, MNG_LEAVES_DEFINEOBJECT);

/// `MNG::DeltaPNGHeader` ProcessBinaryData leaves (table FORMAT int8u, increment 1).
static MNG_LEAVES_DELTAPNGHEADER: &[MngLeafDef] = &[
  MngLeafDef::new(0, "ObjectID", MngFormat::Int16u, 1, None, MngConv::None),
  MngLeafDef::new(
    2,
    "ImageType",
    MngFormat::Int8u,
    1,
    Some(MNG_DELTAPNGHEADER_2),
    MngConv::None,
  ),
  MngLeafDef::new(
    3,
    "DeltaType",
    MngFormat::Int8u,
    1,
    Some(MNG_DELTAPNGHEADER_3),
    MngConv::None,
  ),
  MngLeafDef::new(4, "BlockSize", MngFormat::Int32u, 2, None, MngConv::None),
  MngLeafDef::new(
    12,
    "BlockLocation",
    MngFormat::Int32u,
    2,
    None,
    MngConv::None,
  ),
];
/// `MNG::DeltaPNGHeader` ProcessBinaryData sub-table (increment 1).
static MNG_SUB_DELTAPNGHEADER: MngSubTable = MngSubTable::new(1, MNG_LEAVES_DELTAPNGHEADER);

/// `MNG::ExportImage` ProcessBinaryData leaves (table FORMAT int8u, increment 1).
static MNG_LEAVES_EXPORTIMAGE: &[MngLeafDef] = &[
  MngLeafDef::new(0, "SnapshotID", MngFormat::Int16u, 1, None, MngConv::None),
  MngLeafDef::new(2, "SnapshotName", MngFormat::Strng, 0, None, MngConv::None),
];
/// `MNG::ExportImage` ProcessBinaryData sub-table (increment 1).
static MNG_SUB_EXPORTIMAGE: MngSubTable = MngSubTable::new(1, MNG_LEAVES_EXPORTIMAGE);

/// `MNG::FramePriority` ProcessBinaryData leaves (table FORMAT int8u, increment 1).
static MNG_LEAVES_FRAMEPRIORITY: &[MngLeafDef] = &[
  MngLeafDef::new(
    0,
    "DeltaType",
    MngFormat::Int8u,
    1,
    Some(MNG_FRAMEPRIORITY_0),
    MngConv::None,
  ),
  MngLeafDef::new(2, "Priority", MngFormat::Int8u, 1, None, MngConv::None),
];
/// `MNG::FramePriority` ProcessBinaryData sub-table (increment 1).
static MNG_SUB_FRAMEPRIORITY: MngSubTable = MngSubTable::new(1, MNG_LEAVES_FRAMEPRIORITY);

/// `MNG::JNGHeader` ProcessBinaryData leaves (table FORMAT int8u, increment 1).
static MNG_LEAVES_JNGHEADER: &[MngLeafDef] = &[
  MngLeafDef::new(0, "ImageWidth", MngFormat::Int32u, 1, None, MngConv::None),
  MngLeafDef::new(4, "ImageHeight", MngFormat::Int32u, 1, None, MngConv::None),
  MngLeafDef::new(
    8,
    "ColorType",
    MngFormat::Int8u,
    1,
    Some(MNG_JNGHEADER_8),
    MngConv::None,
  ),
  MngLeafDef::new(9, "BitDepth", MngFormat::Int8u, 1, None, MngConv::None),
  MngLeafDef::new(
    10,
    "Compression",
    MngFormat::Int8u,
    1,
    Some(MNG_JNGHEADER_10),
    MngConv::None,
  ),
  MngLeafDef::new(
    11,
    "Interlace",
    MngFormat::Int8u,
    1,
    Some(MNG_JNGHEADER_11),
    MngConv::None,
  ),
  MngLeafDef::new(
    12,
    "AlphaBitDepth",
    MngFormat::Int8u,
    1,
    None,
    MngConv::None,
  ),
  MngLeafDef::new(
    13,
    "AlphaCompression",
    MngFormat::Int8u,
    1,
    Some(MNG_JNGHEADER_13),
    MngConv::None,
  ),
  MngLeafDef::new(
    14,
    "AlphaFilter",
    MngFormat::Int8u,
    1,
    Some(MNG_JNGHEADER_14),
    MngConv::None,
  ),
  MngLeafDef::new(
    15,
    "AlphaInterlace",
    MngFormat::Int8u,
    1,
    Some(MNG_JNGHEADER_15),
    MngConv::None,
  ),
];
/// `MNG::JNGHeader` ProcessBinaryData sub-table (increment 1).
static MNG_SUB_JNGHEADER: MngSubTable = MngSubTable::new(1, MNG_LEAVES_JNGHEADER);

/// `MNG::Loop` ProcessBinaryData leaves (table FORMAT int8u, increment 1).
static MNG_LEAVES_LOOP: &[MngLeafDef] = &[
  MngLeafDef::new(0, "NestLevel", MngFormat::Int8u, 1, None, MngConv::None),
  MngLeafDef::new(
    1,
    "IterationCount",
    MngFormat::Int32u,
    1,
    None,
    MngConv::None,
  ),
  MngLeafDef::new(
    5,
    "TerminationCondition",
    MngFormat::Int8u,
    1,
    Some(MNG_LOOP_5),
    MngConv::None,
  ),
  MngLeafDef::new(
    6,
    "IterationMinMax",
    MngFormat::Int32u,
    2,
    None,
    MngConv::None,
  ),
  MngLeafDef::new(
    14,
    "SignalNumber",
    MngFormat::Int32u,
    1,
    None,
    MngConv::None,
  ),
];
/// `MNG::Loop` ProcessBinaryData sub-table (increment 1).
static MNG_SUB_LOOP: MngSubTable = MngSubTable::new(1, MNG_LEAVES_LOOP);

/// `MNG::MNGHeader` ProcessBinaryData leaves (table FORMAT int32u, increment 4).
static MNG_LEAVES_MNGHEADER: &[MngLeafDef] = &[
  MngLeafDef::new(0, "ImageWidth", MngFormat::Int32u, 1, None, MngConv::None),
  MngLeafDef::new(1, "ImageHeight", MngFormat::Int32u, 1, None, MngConv::None),
  MngLeafDef::new(
    2,
    "TicksPerSecond",
    MngFormat::Int32u,
    1,
    None,
    MngConv::None,
  ),
  MngLeafDef::new(
    3,
    "NominalLayerCount",
    MngFormat::Int32u,
    1,
    None,
    MngConv::None,
  ),
  MngLeafDef::new(
    4,
    "NominalFrameCount",
    MngFormat::Int32u,
    1,
    None,
    MngConv::None,
  ),
  MngLeafDef::new(
    5,
    "NominalPlayTime",
    MngFormat::Int32u,
    1,
    None,
    MngConv::None,
  ),
  MngLeafDef::new(
    6,
    "SimplicityProfile",
    MngFormat::Int32u,
    1,
    None,
    MngConv::SimplicityProfile,
  ),
];
/// `MNG::MNGHeader` ProcessBinaryData sub-table (increment 4).
static MNG_SUB_MNGHEADER: MngSubTable = MngSubTable::new(4, MNG_LEAVES_MNGHEADER);

/// `MNG::MagnifyObject` ProcessBinaryData leaves (table FORMAT int8u, increment 1).
static MNG_LEAVES_MAGNIFYOBJECT: &[MngLeafDef] = &[
  MngLeafDef::new(
    0,
    "FirstObjectID",
    MngFormat::Int16u,
    1,
    None,
    MngConv::None,
  ),
  MngLeafDef::new(2, "LastObjectID", MngFormat::Int16u, 1, None, MngConv::None),
  MngLeafDef::new(
    4,
    "XMethod",
    MngFormat::Int8u,
    1,
    Some(MAG_METHOD),
    MngConv::None,
  ),
  MngLeafDef::new(5, "XMag", MngFormat::Int16u, 1, None, MngConv::None),
  MngLeafDef::new(7, "YMag", MngFormat::Int16u, 1, None, MngConv::None),
  MngLeafDef::new(9, "LeftMag", MngFormat::Int16u, 1, None, MngConv::None),
  MngLeafDef::new(11, "RightMag", MngFormat::Int16u, 1, None, MngConv::None),
  MngLeafDef::new(13, "TopMag", MngFormat::Int16u, 1, None, MngConv::None),
  MngLeafDef::new(15, "BottomMag", MngFormat::Int16u, 1, None, MngConv::None),
  MngLeafDef::new(
    17,
    "YMethod",
    MngFormat::Int8u,
    1,
    Some(MAG_METHOD),
    MngConv::None,
  ),
];
/// `MNG::MagnifyObject` ProcessBinaryData sub-table (increment 1).
static MNG_SUB_MAGNIFYOBJECT: MngSubTable = MngSubTable::new(1, MNG_LEAVES_MAGNIFYOBJECT);

/// `MNG::MoveObjects` ProcessBinaryData leaves (table FORMAT int8u, increment 1).
static MNG_LEAVES_MOVEOBJECTS: &[MngLeafDef] = &[
  MngLeafDef::new(0, "FirstObject", MngFormat::Int16u, 1, None, MngConv::None),
  MngLeafDef::new(2, "LastObject", MngFormat::Int16u, 1, None, MngConv::None),
  MngLeafDef::new(
    4,
    "DeltaType",
    MngFormat::Int8u,
    1,
    Some(MNG_MOVEOBJECTS_4),
    MngConv::None,
  ),
  MngLeafDef::new(5, "DeltaXY", MngFormat::Int32u, 2, None, MngConv::None),
];
/// `MNG::MoveObjects` ProcessBinaryData sub-table (increment 1).
static MNG_SUB_MOVEOBJECTS: MngSubTable = MngSubTable::new(1, MNG_LEAVES_MOVEOBJECTS);

/// `MNG::PasteImage` ProcessBinaryData leaves (table FORMAT int8u, increment 1).
static MNG_LEAVES_PASTEIMAGE: &[MngLeafDef] = &[
  MngLeafDef::new(
    0,
    "DestinationID",
    MngFormat::Int16u,
    1,
    None,
    MngConv::None,
  ),
  MngLeafDef::new(
    2,
    "TargetDeltaType",
    MngFormat::Int8u,
    1,
    Some(MNG_PASTEIMAGE_2),
    MngConv::None,
  ),
  MngLeafDef::new(3, "TargetXY", MngFormat::Int32u, 2, None, MngConv::None),
  MngLeafDef::new(11, "SourceID", MngFormat::Int16u, 1, None, MngConv::None),
  MngLeafDef::new(
    13,
    "CompositionMode",
    MngFormat::Int8u,
    1,
    Some(MNG_PASTEIMAGE_13),
    MngConv::None,
  ),
  MngLeafDef::new(
    14,
    "Orientation",
    MngFormat::Int8u,
    1,
    Some(MNG_PASTEIMAGE_14),
    MngConv::None,
  ),
  MngLeafDef::new(
    15,
    "OffsetOrigin",
    MngFormat::Int8u,
    1,
    Some(MNG_PASTEIMAGE_15),
    MngConv::None,
  ),
  MngLeafDef::new(16, "OffsetXY", MngFormat::Int32u, 2, None, MngConv::None),
  MngLeafDef::new(
    24,
    "BoundaryOrigin",
    MngFormat::Int8u,
    1,
    Some(MNG_PASTEIMAGE_24),
    MngConv::None,
  ),
  MngLeafDef::new(
    25,
    "PastClippingBoundary",
    MngFormat::Int32u,
    4,
    None,
    MngConv::None,
  ),
];
/// `MNG::PasteImage` ProcessBinaryData sub-table (increment 1).
static MNG_SUB_PASTEIMAGE: MngSubTable = MngSubTable::new(1, MNG_LEAVES_PASTEIMAGE);

/// `MNG::PromoteParent` ProcessBinaryData leaves (table FORMAT int8u, increment 1).
static MNG_LEAVES_PROMOTEPARENT: &[MngLeafDef] = &[
  MngLeafDef::new(0, "NewColorType", MngFormat::Int8u, 1, None, MngConv::None),
  MngLeafDef::new(1, "NewBitDepth", MngFormat::Int8u, 1, None, MngConv::None),
  MngLeafDef::new(
    2,
    "FillMethod",
    MngFormat::Int8u,
    1,
    Some(MNG_PROMOTEPARENT_2),
    MngConv::None,
  ),
];
/// `MNG::PromoteParent` ProcessBinaryData sub-table (increment 1).
static MNG_SUB_PROMOTEPARENT: MngSubTable = MngSubTable::new(1, MNG_LEAVES_PROMOTEPARENT);

/// `MNG::ShowObjects` ProcessBinaryData leaves (table FORMAT int8u, increment 1).
static MNG_LEAVES_SHOWOBJECTS: &[MngLeafDef] = &[
  MngLeafDef::new(0, "FirstObject", MngFormat::Int16u, 1, None, MngConv::None),
  MngLeafDef::new(2, "LastObject", MngFormat::Int16u, 1, None, MngConv::None),
  MngLeafDef::new(4, "ShowMode", MngFormat::Int8u, 1, None, MngConv::None),
];
/// `MNG::ShowObjects` ProcessBinaryData sub-table (increment 1).
static MNG_SUB_SHOWOBJECTS: MngSubTable = MngSubTable::new(1, MNG_LEAVES_SHOWOBJECTS);

/// `MNG::TerminationAction` ProcessBinaryData leaves (table FORMAT int8u, increment 1).
static MNG_LEAVES_TERMINATIONACTION: &[MngLeafDef] = &[
  MngLeafDef::new(
    0,
    "TerminationAction",
    MngFormat::Int8u,
    1,
    Some(MNG_TERMINATIONACTION_0),
    MngConv::None,
  ),
  MngLeafDef::new(
    1,
    "IterationEndAction",
    MngFormat::Int8u,
    1,
    Some(MNG_TERMINATIONACTION_1),
    MngConv::None,
  ),
  MngLeafDef::new(2, "Delay", MngFormat::Int32u, 1, None, MngConv::None),
  MngLeafDef::new(6, "IterationMax", MngFormat::Int32u, 1, None, MngConv::None),
];
/// `MNG::TerminationAction` ProcessBinaryData sub-table (increment 1).
static MNG_SUB_TERMINATIONACTION: MngSubTable = MngSubTable::new(1, MNG_LEAVES_TERMINATIONACTION);

/// Every `%MNG::Main` chunk, SORTED by 4-byte chunk id for binary search.
pub(super) static MNG_CHUNKS: &[(&[u8; 4], MngChunkKind)] = &[
  (b"BACK", MngChunkKind::Sub(&MNG_SUB_BACKGROUND)),
  (b"BASI", MngChunkKind::Sub(&MNG_SUB_BASISOBJECT)),
  (b"CLIP", MngChunkKind::Sub(&MNG_SUB_CLIPOBJECTS)),
  (b"CLON", MngChunkKind::Sub(&MNG_SUB_CLONEOBJECT)),
  (b"DBYK", MngChunkKind::Binary("DropByKeyword")),
  (b"DEFI", MngChunkKind::Sub(&MNG_SUB_DEFINEOBJECT)),
  (b"DHDR", MngChunkKind::Sub(&MNG_SUB_DELTAPNGHEADER)),
  (
    b"DISC",
    MngChunkKind::Inline("DiscardObjects", MngConv::DiscardObjects),
  ),
  (
    b"DROP",
    MngChunkKind::Inline("DropChunks", MngConv::DropChunks),
  ),
  (b"FRAM", MngChunkKind::Binary("Frame")),
  (b"JHDR", MngChunkKind::Sub(&MNG_SUB_JNGHEADER)),
  (b"LOOP", MngChunkKind::Sub(&MNG_SUB_LOOP)),
  (b"MAGN", MngChunkKind::Sub(&MNG_SUB_MAGNIFYOBJECT)),
  (b"MHDR", MngChunkKind::Sub(&MNG_SUB_MNGHEADER)),
  (b"MOVE", MngChunkKind::Sub(&MNG_SUB_MOVEOBJECTS)),
  (b"ORDR", MngChunkKind::Binary("OrderingRestrictions")),
  (b"PAST", MngChunkKind::Sub(&MNG_SUB_PASTEIMAGE)),
  (b"PPLT", MngChunkKind::Binary("PartialPalette")),
  (b"PROM", MngChunkKind::Sub(&MNG_SUB_PROMOTEPARENT)),
  (b"SAVE", MngChunkKind::Binary("SaveObjects")),
  (
    b"SEEK",
    MngChunkKind::Inline("SeekPoint", MngConv::SeekPoint),
  ),
  (b"SHOW", MngChunkKind::Sub(&MNG_SUB_SHOWOBJECTS)),
  (b"TERM", MngChunkKind::Sub(&MNG_SUB_TERMINATIONACTION)),
  (b"eXPi", MngChunkKind::Sub(&MNG_SUB_EXPORTIMAGE)),
  (b"fPRI", MngChunkKind::Sub(&MNG_SUB_FRAMEPRIORITY)),
  (b"nEED", MngChunkKind::Binary("ResourcesNeeded")),
  (b"pHYg", MngChunkKind::Phys),
];
