// generated by xtask gen-tables from exiftool -listx 13.59 — DO NOT EDIT
// (regenerate with `cargo xtask gen-tables --kind exif --module GPS::Main \
//    --out <path>`)
// source table: GPS::Main
//
// Step-A BYTE-IDENTICAL shadow of the hand table — emits ONLY the ported
// hand id set, each resolved to the SAME conv the hand table carries. A
// child module of the hand table (`super::*` const refs resolve there).

use super::{Conv, GpsConv, GpsTag};

static EXIF_GPSVERSIONID: GpsTag = GpsTag {
  id: 0x0000,
  name: "GPSVersionID",
  conv: GpsConv::VersionId,
};
static EXIF_GPSLATITUDEREF: GpsTag = GpsTag {
  id: 0x0001,
  name: "GPSLatitudeRef",
  conv: GpsConv::StrLabel(&[("N", "North"), ("S", "South")]),
};
static EXIF_GPSLATITUDE: GpsTag = GpsTag {
  id: 0x0002,
  name: "GPSLatitude",
  conv: GpsConv::Coordinate,
};
static EXIF_GPSLONGITUDEREF: GpsTag = GpsTag {
  id: 0x0003,
  name: "GPSLongitudeRef",
  conv: GpsConv::StrLabel(&[("E", "East"), ("W", "West")]),
};
static EXIF_GPSLONGITUDE: GpsTag = GpsTag {
  id: 0x0004,
  name: "GPSLongitude",
  conv: GpsConv::Coordinate,
};
static EXIF_GPSALTITUDEREF: GpsTag = GpsTag {
  id: 0x0005,
  name: "GPSAltitudeRef",
  conv: GpsConv::Plain(Conv::IntLabel(&[
    (0, "Above Sea Level"),
    (1, "Below Sea Level"),
    (2, "Positive Sea Level (sea-level ref)"),
    (3, "Negative Sea Level (sea-level ref)"),
  ])),
};
static EXIF_GPSALTITUDE: GpsTag = GpsTag {
  id: 0x0006,
  name: "GPSAltitude",
  conv: GpsConv::Plain(Conv::MetersSuffix),
};
static EXIF_GPSTIMESTAMP: GpsTag = GpsTag {
  id: 0x0007,
  name: "GPSTimeStamp",
  conv: GpsConv::TimeStamp,
};
static EXIF_GPSSATELLITES: GpsTag = GpsTag {
  id: 0x0008,
  name: "GPSSatellites",
  conv: GpsConv::Plain(Conv::None),
};
static EXIF_GPSSTATUS: GpsTag = GpsTag {
  id: 0x0009,
  name: "GPSStatus",
  conv: GpsConv::StrLabel(&[("A", "Measurement Active"), ("V", "Measurement Void")]),
};
static EXIF_GPSMEASUREMODE: GpsTag = GpsTag {
  id: 0x000a,
  name: "GPSMeasureMode",
  conv: GpsConv::StrLabel(super::GPS_MEASURE_MODE),
};
static EXIF_GPSDOP: GpsTag = GpsTag {
  id: 0x000b,
  name: "GPSDOP",
  conv: GpsConv::Plain(Conv::None),
};
static EXIF_GPSSPEEDREF: GpsTag = GpsTag {
  id: 0x000c,
  name: "GPSSpeedRef",
  conv: GpsConv::StrLabel(&[("K", "km/h"), ("M", "mph"), ("N", "knots")]),
};
static EXIF_GPSSPEED: GpsTag = GpsTag {
  id: 0x000d,
  name: "GPSSpeed",
  conv: GpsConv::Plain(Conv::None),
};
static EXIF_GPSTRACKREF: GpsTag = GpsTag {
  id: 0x000e,
  name: "GPSTrackRef",
  conv: GpsConv::StrLabel(&[("M", "Magnetic North"), ("T", "True North")]),
};
static EXIF_GPSTRACK: GpsTag = GpsTag {
  id: 0x000f,
  name: "GPSTrack",
  conv: GpsConv::Plain(Conv::None),
};
static EXIF_GPSIMGDIRECTIONREF: GpsTag = GpsTag {
  id: 0x0010,
  name: "GPSImgDirectionRef",
  conv: GpsConv::StrLabel(&[("M", "Magnetic North"), ("T", "True North")]),
};
static EXIF_GPSIMGDIRECTION: GpsTag = GpsTag {
  id: 0x0011,
  name: "GPSImgDirection",
  conv: GpsConv::Plain(Conv::None),
};
static EXIF_GPSMAPDATUM: GpsTag = GpsTag {
  id: 0x0012,
  name: "GPSMapDatum",
  conv: GpsConv::Plain(Conv::None),
};
static EXIF_GPSDESTLATITUDEREF: GpsTag = GpsTag {
  id: 0x0013,
  name: "GPSDestLatitudeRef",
  conv: GpsConv::StrLabel(&[("N", "North"), ("S", "South")]),
};
static EXIF_GPSDESTLATITUDE: GpsTag = GpsTag {
  id: 0x0014,
  name: "GPSDestLatitude",
  conv: GpsConv::Coordinate,
};
static EXIF_GPSDESTLONGITUDEREF: GpsTag = GpsTag {
  id: 0x0015,
  name: "GPSDestLongitudeRef",
  conv: GpsConv::StrLabel(&[("E", "East"), ("W", "West")]),
};
static EXIF_GPSDESTLONGITUDE: GpsTag = GpsTag {
  id: 0x0016,
  name: "GPSDestLongitude",
  conv: GpsConv::Coordinate,
};
static EXIF_GPSDESTBEARINGREF: GpsTag = GpsTag {
  id: 0x0017,
  name: "GPSDestBearingRef",
  conv: GpsConv::StrLabel(&[("M", "Magnetic North"), ("T", "True North")]),
};
static EXIF_GPSDESTBEARING: GpsTag = GpsTag {
  id: 0x0018,
  name: "GPSDestBearing",
  conv: GpsConv::Plain(Conv::None),
};
static EXIF_GPSDESTDISTANCEREF: GpsTag = GpsTag {
  id: 0x0019,
  name: "GPSDestDistanceRef",
  conv: GpsConv::StrLabel(&[("K", "Kilometers"), ("M", "Miles"), ("N", "Nautical Miles")]),
};
static EXIF_GPSDESTDISTANCE: GpsTag = GpsTag {
  id: 0x001a,
  name: "GPSDestDistance",
  conv: GpsConv::Plain(Conv::None),
};
static EXIF_GPSPROCESSINGMETHOD: GpsTag = GpsTag {
  id: 0x001b,
  name: "GPSProcessingMethod",
  conv: GpsConv::ExifText,
};
static EXIF_GPSAREAINFORMATION: GpsTag = GpsTag {
  id: 0x001c,
  name: "GPSAreaInformation",
  conv: GpsConv::ExifText,
};
static EXIF_GPSDATESTAMP: GpsTag = GpsTag {
  id: 0x001d,
  name: "GPSDateStamp",
  conv: GpsConv::DateStamp,
};
static EXIF_GPSDIFFERENTIAL: GpsTag = GpsTag {
  id: 0x001e,
  name: "GPSDifferential",
  conv: GpsConv::Plain(Conv::IntLabel(&[
    (0, "No Correction"),
    (1, "Differential Corrected"),
  ])),
};
static EXIF_GPSHPOSITIONINGERROR: GpsTag = GpsTag {
  id: 0x001f,
  name: "GPSHPositioningError",
  conv: GpsConv::Plain(Conv::MetersSuffix),
};

/// `GPS::Main` — the Step-A generated shadow (32 ported ids). Consulted by the
/// hand `lookup` AFTER its own table (this is a strict subset, so a hit
/// here always AGREES with the hand entry).
pub fn lookup(id: u16) -> Option<&'static GpsTag> {
  match id {
    0x0000 => Some(&EXIF_GPSVERSIONID),
    0x0001 => Some(&EXIF_GPSLATITUDEREF),
    0x0002 => Some(&EXIF_GPSLATITUDE),
    0x0003 => Some(&EXIF_GPSLONGITUDEREF),
    0x0004 => Some(&EXIF_GPSLONGITUDE),
    0x0005 => Some(&EXIF_GPSALTITUDEREF),
    0x0006 => Some(&EXIF_GPSALTITUDE),
    0x0007 => Some(&EXIF_GPSTIMESTAMP),
    0x0008 => Some(&EXIF_GPSSATELLITES),
    0x0009 => Some(&EXIF_GPSSTATUS),
    0x000a => Some(&EXIF_GPSMEASUREMODE),
    0x000b => Some(&EXIF_GPSDOP),
    0x000c => Some(&EXIF_GPSSPEEDREF),
    0x000d => Some(&EXIF_GPSSPEED),
    0x000e => Some(&EXIF_GPSTRACKREF),
    0x000f => Some(&EXIF_GPSTRACK),
    0x0010 => Some(&EXIF_GPSIMGDIRECTIONREF),
    0x0011 => Some(&EXIF_GPSIMGDIRECTION),
    0x0012 => Some(&EXIF_GPSMAPDATUM),
    0x0013 => Some(&EXIF_GPSDESTLATITUDEREF),
    0x0014 => Some(&EXIF_GPSDESTLATITUDE),
    0x0015 => Some(&EXIF_GPSDESTLONGITUDEREF),
    0x0016 => Some(&EXIF_GPSDESTLONGITUDE),
    0x0017 => Some(&EXIF_GPSDESTBEARINGREF),
    0x0018 => Some(&EXIF_GPSDESTBEARING),
    0x0019 => Some(&EXIF_GPSDESTDISTANCEREF),
    0x001a => Some(&EXIF_GPSDESTDISTANCE),
    0x001b => Some(&EXIF_GPSPROCESSINGMETHOD),
    0x001c => Some(&EXIF_GPSAREAINFORMATION),
    0x001d => Some(&EXIF_GPSDATESTAMP),
    0x001e => Some(&EXIF_GPSDIFFERENTIAL),
    0x001f => Some(&EXIF_GPSHPOSITIONINGERROR),
    _ => None,
  }
}
