// generated by xtask gen-tables from exiftool -listx 13.59 — DO NOT EDIT
// (regenerate with `cargo xtask gen-tables --kind exif --module Exif::Main \
//    --out <path>`)
// source table: Exif::Main
//
// Generated shadow of the hand table — the ported camera-relevant hand id
// set PLUS the binary-EXIF coverage-gap ids (Step B). Every SHARED id
// resolves to the SAME conv the hand table carries; the gap ids are NOT in
// the hand table, so the hand-first `lookup` falls through here and they
// emit. A child module of the hand table (`super::*` const refs resolve
// there); the hand table stays a strict SUBSET of the generated table.

use super::{Conv, ExifTag};

static EXIF_INTEROPINDEX: ExifTag = ExifTag {
  id: 0x0001,
  name: "InteropIndex",
  conv: Conv::StrLabel(super::INTEROP_INDEX),
};
static EXIF_INTEROPVERSION: ExifTag = ExifTag {
  id: 0x0002,
  name: "InteropVersion",
  conv: Conv::Version,
};
static EXIF_PROCESSINGSOFTWARE: ExifTag = ExifTag {
  id: 0x000b,
  name: "ProcessingSoftware",
  conv: Conv::None,
};
static EXIF_SUBFILETYPE: ExifTag = ExifTag {
  id: 0x00fe,
  name: "SubfileType",
  conv: Conv::IntLabel(super::SUBFILE_TYPE),
};
static EXIF_IMAGEWIDTH: ExifTag = ExifTag {
  id: 0x0100,
  name: "ImageWidth",
  conv: Conv::None,
};
static EXIF_IMAGEHEIGHT: ExifTag = ExifTag {
  id: 0x0101,
  name: "ImageHeight",
  conv: Conv::None,
};
static EXIF_BITSPERSAMPLE: ExifTag = ExifTag {
  id: 0x0102,
  name: "BitsPerSample",
  conv: Conv::None,
};
static EXIF_COMPRESSION: ExifTag = ExifTag {
  id: 0x0103,
  name: "Compression",
  conv: Conv::IntLabel(super::COMPRESSION),
};
static EXIF_PHOTOMETRICINTERPRETATION: ExifTag = ExifTag {
  id: 0x0106,
  name: "PhotometricInterpretation",
  conv: Conv::IntLabel(super::PHOTOMETRIC),
};
static EXIF_DOCUMENTNAME: ExifTag = ExifTag {
  id: 0x010d,
  name: "DocumentName",
  conv: Conv::None,
};
static EXIF_IMAGEDESCRIPTION: ExifTag = ExifTag {
  id: 0x010e,
  name: "ImageDescription",
  conv: Conv::None,
};
static EXIF_MAKE: ExifTag = ExifTag {
  id: 0x010f,
  name: "Make",
  conv: Conv::TrimTrailingWhitespace,
};
static EXIF_MODEL: ExifTag = ExifTag {
  id: 0x0110,
  name: "Model",
  conv: Conv::TrimTrailingWhitespace,
};
static EXIF_STRIPOFFSETS: ExifTag = ExifTag {
  id: 0x0111,
  name: "StripOffsets",
  conv: Conv::None,
};
static EXIF_ORIENTATION: ExifTag = ExifTag {
  id: 0x0112,
  name: "Orientation",
  conv: Conv::IntLabel(&[
    (1, "Horizontal (normal)"),
    (2, "Mirror horizontal"),
    (3, "Rotate 180"),
    (4, "Mirror vertical"),
    (5, "Mirror horizontal and rotate 270 CW"),
    (6, "Rotate 90 CW"),
    (7, "Mirror horizontal and rotate 90 CW"),
    (8, "Rotate 270 CW"),
  ]),
};
static EXIF_SAMPLESPERPIXEL: ExifTag = ExifTag {
  id: 0x0115,
  name: "SamplesPerPixel",
  conv: Conv::None,
};
static EXIF_ROWSPERSTRIP: ExifTag = ExifTag {
  id: 0x0116,
  name: "RowsPerStrip",
  conv: Conv::None,
};
static EXIF_STRIPBYTECOUNTS: ExifTag = ExifTag {
  id: 0x0117,
  name: "StripByteCounts",
  conv: Conv::None,
};
static EXIF_XRESOLUTION: ExifTag = ExifTag {
  id: 0x011a,
  name: "XResolution",
  conv: Conv::None,
};
static EXIF_YRESOLUTION: ExifTag = ExifTag {
  id: 0x011b,
  name: "YResolution",
  conv: Conv::None,
};
static EXIF_PLANARCONFIGURATION: ExifTag = ExifTag {
  id: 0x011c,
  name: "PlanarConfiguration",
  conv: Conv::IntLabel(&[(1, "Chunky"), (2, "Planar")]),
};
static EXIF_RESOLUTIONUNIT: ExifTag = ExifTag {
  id: 0x0128,
  name: "ResolutionUnit",
  conv: Conv::IntLabel(&[(1, "None"), (2, "inches"), (3, "cm")]),
};
static EXIF_SOFTWARE: ExifTag = ExifTag {
  id: 0x0131,
  name: "Software",
  conv: Conv::TrimTrailingWhitespace,
};
static EXIF_MODIFYDATE: ExifTag = ExifTag {
  id: 0x0132,
  name: "ModifyDate",
  conv: Conv::DateTime,
};
static EXIF_ARTIST: ExifTag = ExifTag {
  id: 0x013b,
  name: "Artist",
  conv: Conv::TrimTrailingWhitespace,
};
static EXIF_HOSTCOMPUTER: ExifTag = ExifTag {
  id: 0x013c,
  name: "HostComputer",
  conv: Conv::None,
};
static EXIF_PREDICTOR: ExifTag = ExifTag {
  id: 0x013d,
  name: "Predictor",
  conv: Conv::IntLabel(super::PREDICTOR),
};
static EXIF_WHITEPOINT: ExifTag = ExifTag {
  id: 0x013e,
  name: "WhitePoint",
  conv: Conv::None,
};
static EXIF_PRIMARYCHROMATICITIES: ExifTag = ExifTag {
  id: 0x013f,
  name: "PrimaryChromaticities",
  conv: Conv::None,
};
static EXIF_THUMBNAILOFFSET: ExifTag = ExifTag {
  id: 0x0201,
  name: "ThumbnailOffset",
  conv: Conv::None,
};
static EXIF_THUMBNAILLENGTH: ExifTag = ExifTag {
  id: 0x0202,
  name: "ThumbnailLength",
  conv: Conv::None,
};
static EXIF_YCBCRCOEFFICIENTS: ExifTag = ExifTag {
  id: 0x0211,
  name: "YCbCrCoefficients",
  conv: Conv::None,
};
static EXIF_YCBCRPOSITIONING: ExifTag = ExifTag {
  id: 0x0213,
  name: "YCbCrPositioning",
  conv: Conv::IntLabel(&[(1, "Centered"), (2, "Co-sited")]),
};
static EXIF_REFERENCEBLACKWHITE: ExifTag = ExifTag {
  id: 0x0214,
  name: "ReferenceBlackWhite",
  conv: Conv::None,
};
static EXIF_COPYRIGHT: ExifTag = ExifTag {
  id: 0x8298,
  name: "Copyright",
  conv: Conv::None,
};
static EXIF_EXPOSURETIME: ExifTag = ExifTag {
  id: 0x829a,
  name: "ExposureTime",
  conv: Conv::ExposureTime,
};
static EXIF_FNUMBER: ExifTag = ExifTag {
  id: 0x829d,
  name: "FNumber",
  conv: Conv::FNumber,
};
static EXIF_EXPOSUREPROGRAM: ExifTag = ExifTag {
  id: 0x8822,
  name: "ExposureProgram",
  conv: Conv::IntLabel(&[
    (0, "Not Defined"),
    (1, "Manual"),
    (2, "Program AE"),
    (3, "Aperture-priority AE"),
    (4, "Shutter speed priority AE"),
    (5, "Creative (Slow speed)"),
    (6, "Action (High speed)"),
    (7, "Portrait"),
    (8, "Landscape"),
    (9, "Bulb"),
  ]),
};
static EXIF_SPECTRALSENSITIVITY: ExifTag = ExifTag {
  id: 0x8824,
  name: "SpectralSensitivity",
  conv: Conv::None,
};
static EXIF_ISO: ExifTag = ExifTag {
  id: 0x8827,
  name: "ISO",
  conv: Conv::None,
};
static EXIF_OPTO_ELECTRICCONVFACTOR: ExifTag = ExifTag {
  id: 0x8828,
  name: "Opto-ElectricConvFactor",
  conv: Conv::None,
};
static EXIF_TIMEZONEOFFSET: ExifTag = ExifTag {
  id: 0x882a,
  name: "TimeZoneOffset",
  conv: Conv::None,
};
static EXIF_SENSITIVITYTYPE: ExifTag = ExifTag {
  id: 0x8830,
  name: "SensitivityType",
  conv: Conv::None,
};
static EXIF_STANDARDOUTPUTSENSITIVITY: ExifTag = ExifTag {
  id: 0x8831,
  name: "StandardOutputSensitivity",
  conv: Conv::None,
};
static EXIF_RECOMMENDEDEXPOSUREINDEX: ExifTag = ExifTag {
  id: 0x8832,
  name: "RecommendedExposureIndex",
  conv: Conv::None,
};
static EXIF_ISOSPEED: ExifTag = ExifTag {
  id: 0x8833,
  name: "ISOSpeed",
  conv: Conv::None,
};
static EXIF_ISOSPEEDLATITUDEYYY: ExifTag = ExifTag {
  id: 0x8834,
  name: "ISOSpeedLatitudeyyy",
  conv: Conv::None,
};
static EXIF_ISOSPEEDLATITUDEZZZ: ExifTag = ExifTag {
  id: 0x8835,
  name: "ISOSpeedLatitudezzz",
  conv: Conv::None,
};
static EXIF_EXIFVERSION: ExifTag = ExifTag {
  id: 0x9000,
  name: "ExifVersion",
  conv: Conv::Version,
};
static EXIF_DATETIMEORIGINAL: ExifTag = ExifTag {
  id: 0x9003,
  name: "DateTimeOriginal",
  conv: Conv::DateTime,
};
static EXIF_CREATEDATE: ExifTag = ExifTag {
  id: 0x9004,
  name: "CreateDate",
  conv: Conv::DateTime,
};
static EXIF_OFFSETTIME: ExifTag = ExifTag {
  id: 0x9010,
  name: "OffsetTime",
  conv: Conv::None,
};
static EXIF_OFFSETTIMEORIGINAL: ExifTag = ExifTag {
  id: 0x9011,
  name: "OffsetTimeOriginal",
  conv: Conv::None,
};
static EXIF_OFFSETTIMEDIGITIZED: ExifTag = ExifTag {
  id: 0x9012,
  name: "OffsetTimeDigitized",
  conv: Conv::None,
};
static EXIF_COMPONENTSCONFIGURATION: ExifTag = ExifTag {
  id: 0x9101,
  name: "ComponentsConfiguration",
  conv: Conv::ComponentsConfiguration,
};
static EXIF_COMPRESSEDBITSPERPIXEL: ExifTag = ExifTag {
  id: 0x9102,
  name: "CompressedBitsPerPixel",
  conv: Conv::None,
};
static EXIF_SHUTTERSPEEDVALUE: ExifTag = ExifTag {
  id: 0x9201,
  name: "ShutterSpeedValue",
  conv: Conv::ShutterSpeedApex,
};
static EXIF_APERTUREVALUE: ExifTag = ExifTag {
  id: 0x9202,
  name: "ApertureValue",
  conv: Conv::ApertureApex,
};
static EXIF_BRIGHTNESSVALUE: ExifTag = ExifTag {
  id: 0x9203,
  name: "BrightnessValue",
  conv: Conv::None,
};
static EXIF_EXPOSURECOMPENSATION: ExifTag = ExifTag {
  id: 0x9204,
  name: "ExposureCompensation",
  conv: Conv::ExposureCompensation,
};
static EXIF_MAXAPERTUREVALUE: ExifTag = ExifTag {
  id: 0x9205,
  name: "MaxApertureValue",
  conv: Conv::ApertureApex,
};
static EXIF_SUBJECTDISTANCE: ExifTag = ExifTag {
  id: 0x9206,
  name: "SubjectDistance",
  conv: Conv::MetersSuffix,
};
static EXIF_METERINGMODE: ExifTag = ExifTag {
  id: 0x9207,
  name: "MeteringMode",
  conv: Conv::IntLabel(&[
    (0, "Unknown"),
    (1, "Average"),
    (2, "Center-weighted average"),
    (3, "Spot"),
    (4, "Multi-spot"),
    (5, "Multi-segment"),
    (6, "Partial"),
    (255, "Other"),
  ]),
};
static EXIF_LIGHTSOURCE: ExifTag = ExifTag {
  id: 0x9208,
  name: "LightSource",
  conv: Conv::IntLabel(super::LIGHT_SOURCE),
};
static EXIF_FLASH: ExifTag = ExifTag {
  id: 0x9209,
  name: "Flash",
  conv: Conv::IntLabelHex(super::FLASH),
};
static EXIF_FOCALLENGTH: ExifTag = ExifTag {
  id: 0x920a,
  name: "FocalLength",
  conv: Conv::FocalLengthMm,
};
static EXIF_IMAGENUMBER: ExifTag = ExifTag {
  id: 0x9211,
  name: "ImageNumber",
  conv: Conv::None,
};
static EXIF_SECURITYCLASSIFICATION: ExifTag = ExifTag {
  id: 0x9212,
  name: "SecurityClassification",
  conv: Conv::StrLabel(&[
    ("C", "Confidential"),
    ("R", "Restricted"),
    ("S", "Secret"),
    ("T", "Top Secret"),
    ("U", "Unclassified"),
  ]),
};
static EXIF_IMAGEHISTORY: ExifTag = ExifTag {
  id: 0x9213,
  name: "ImageHistory",
  conv: Conv::None,
};
static EXIF_SUBJECTAREA: ExifTag = ExifTag {
  id: 0x9214,
  name: "SubjectArea",
  conv: Conv::None,
};
static EXIF_USERCOMMENT: ExifTag = ExifTag {
  id: 0x9286,
  name: "UserComment",
  conv: Conv::ExifText,
};
static EXIF_SUBSECTIME: ExifTag = ExifTag {
  id: 0x9290,
  name: "SubSecTime",
  conv: Conv::TrimTrailingSpaces,
};
static EXIF_SUBSECTIMEORIGINAL: ExifTag = ExifTag {
  id: 0x9291,
  name: "SubSecTimeOriginal",
  conv: Conv::TrimTrailingSpaces,
};
static EXIF_SUBSECTIMEDIGITIZED: ExifTag = ExifTag {
  id: 0x9292,
  name: "SubSecTimeDigitized",
  conv: Conv::TrimTrailingSpaces,
};
static EXIF_AMBIENTTEMPERATURE: ExifTag = ExifTag {
  id: 0x9400,
  name: "AmbientTemperature",
  conv: Conv::CelsiusSuffix,
};
static EXIF_HUMIDITY: ExifTag = ExifTag {
  id: 0x9401,
  name: "Humidity",
  conv: Conv::None,
};
static EXIF_PRESSURE: ExifTag = ExifTag {
  id: 0x9402,
  name: "Pressure",
  conv: Conv::None,
};
static EXIF_WATERDEPTH: ExifTag = ExifTag {
  id: 0x9403,
  name: "WaterDepth",
  conv: Conv::None,
};
static EXIF_ACCELERATION: ExifTag = ExifTag {
  id: 0x9404,
  name: "Acceleration",
  conv: Conv::None,
};
static EXIF_CAMERAELEVATIONANGLE: ExifTag = ExifTag {
  id: 0x9405,
  name: "CameraElevationAngle",
  conv: Conv::None,
};
static EXIF_FLASHPIXVERSION: ExifTag = ExifTag {
  id: 0xa000,
  name: "FlashpixVersion",
  conv: Conv::Version,
};
static EXIF_COLORSPACE: ExifTag = ExifTag {
  id: 0xa001,
  name: "ColorSpace",
  conv: Conv::IntLabelHex(super::COLOR_SPACE),
};
static EXIF_EXIFIMAGEWIDTH: ExifTag = ExifTag {
  id: 0xa002,
  name: "ExifImageWidth",
  conv: Conv::None,
};
static EXIF_EXIFIMAGEHEIGHT: ExifTag = ExifTag {
  id: 0xa003,
  name: "ExifImageHeight",
  conv: Conv::None,
};
static EXIF_RELATEDSOUNDFILE: ExifTag = ExifTag {
  id: 0xa004,
  name: "RelatedSoundFile",
  conv: Conv::None,
};
static EXIF_FLASHENERGY: ExifTag = ExifTag {
  id: 0xa20b,
  name: "FlashEnergy",
  conv: Conv::None,
};
static EXIF_FOCALPLANEXRESOLUTION: ExifTag = ExifTag {
  id: 0xa20e,
  name: "FocalPlaneXResolution",
  conv: Conv::None,
};
static EXIF_FOCALPLANEYRESOLUTION: ExifTag = ExifTag {
  id: 0xa20f,
  name: "FocalPlaneYResolution",
  conv: Conv::None,
};
static EXIF_FOCALPLANERESOLUTIONUNIT: ExifTag = ExifTag {
  id: 0xa210,
  name: "FocalPlaneResolutionUnit",
  conv: Conv::IntLabel(super::RESOLUTION_UNIT),
};
static EXIF_SUBJECTLOCATION: ExifTag = ExifTag {
  id: 0xa214,
  name: "SubjectLocation",
  conv: Conv::None,
};
static EXIF_EXPOSUREINDEX: ExifTag = ExifTag {
  id: 0xa215,
  name: "ExposureIndex",
  conv: Conv::None,
};
static EXIF_SENSINGMETHOD: ExifTag = ExifTag {
  id: 0xa217,
  name: "SensingMethod",
  conv: Conv::IntLabel(super::SENSING_METHOD),
};
static EXIF_FILESOURCE: ExifTag = ExifTag {
  id: 0xa300,
  name: "FileSource",
  conv: Conv::IntLabel(super::FILE_SOURCE),
};
static EXIF_SCENETYPE: ExifTag = ExifTag {
  id: 0xa301,
  name: "SceneType",
  conv: Conv::IntLabel(&[(1, "Directly photographed")]),
};
static EXIF_CUSTOMRENDERED: ExifTag = ExifTag {
  id: 0xa401,
  name: "CustomRendered",
  conv: Conv::IntLabel(&[
    (0, "Normal"),
    (1, "Custom"),
    (2, "HDR (no original saved)"),
    (3, "HDR (original saved)"),
    (4, "Original (for HDR)"),
    (6, "Panorama"),
    (7, "Portrait HDR"),
    (8, "Portrait"),
  ]),
};
static EXIF_EXPOSUREMODE: ExifTag = ExifTag {
  id: 0xa402,
  name: "ExposureMode",
  conv: Conv::IntLabel(&[(0, "Auto"), (1, "Manual"), (2, "Auto bracket")]),
};
static EXIF_WHITEBALANCE: ExifTag = ExifTag {
  id: 0xa403,
  name: "WhiteBalance",
  conv: Conv::IntLabel(&[(0, "Auto"), (1, "Manual")]),
};
static EXIF_DIGITALZOOMRATIO: ExifTag = ExifTag {
  id: 0xa404,
  name: "DigitalZoomRatio",
  conv: Conv::None,
};
static EXIF_FOCALLENGTHIN35MMFORMAT: ExifTag = ExifTag {
  id: 0xa405,
  name: "FocalLengthIn35mmFormat",
  conv: Conv::FocalLength35mm,
};
static EXIF_SCENECAPTURETYPE: ExifTag = ExifTag {
  id: 0xa406,
  name: "SceneCaptureType",
  conv: Conv::IntLabel(&[
    (0, "Standard"),
    (1, "Landscape"),
    (2, "Portrait"),
    (3, "Night"),
    (4, "Other"),
  ]),
};
static EXIF_GAINCONTROL: ExifTag = ExifTag {
  id: 0xa407,
  name: "GainControl",
  conv: Conv::IntLabel(&[
    (0, "None"),
    (1, "Low gain up"),
    (2, "High gain up"),
    (3, "Low gain down"),
    (4, "High gain down"),
  ]),
};
static EXIF_CONTRAST: ExifTag = ExifTag {
  id: 0xa408,
  name: "Contrast",
  conv: Conv::IntLabel(&[(0, "Normal"), (1, "Low"), (2, "High")]),
};
static EXIF_SATURATION: ExifTag = ExifTag {
  id: 0xa409,
  name: "Saturation",
  conv: Conv::IntLabel(&[(0, "Normal"), (1, "Low"), (2, "High")]),
};
static EXIF_SHARPNESS: ExifTag = ExifTag {
  id: 0xa40a,
  name: "Sharpness",
  conv: Conv::IntLabel(super::CONTRAST),
};
static EXIF_SUBJECTDISTANCERANGE: ExifTag = ExifTag {
  id: 0xa40c,
  name: "SubjectDistanceRange",
  conv: Conv::IntLabel(&[(0, "Unknown"), (1, "Macro"), (2, "Close"), (3, "Distant")]),
};
static EXIF_IMAGEUNIQUEID: ExifTag = ExifTag {
  id: 0xa420,
  name: "ImageUniqueID",
  conv: Conv::None,
};
static EXIF_OWNERNAME: ExifTag = ExifTag {
  id: 0xa430,
  name: "OwnerName",
  conv: Conv::None,
};
static EXIF_SERIALNUMBER: ExifTag = ExifTag {
  id: 0xa431,
  name: "SerialNumber",
  conv: Conv::None,
};
static EXIF_LENSINFO: ExifTag = ExifTag {
  id: 0xa432,
  name: "LensInfo",
  conv: Conv::LensInfo,
};
static EXIF_LENSMAKE: ExifTag = ExifTag {
  id: 0xa433,
  name: "LensMake",
  conv: Conv::None,
};
static EXIF_LENSMODEL: ExifTag = ExifTag {
  id: 0xa434,
  name: "LensModel",
  conv: Conv::None,
};
static EXIF_LENSSERIALNUMBER: ExifTag = ExifTag {
  id: 0xa435,
  name: "LensSerialNumber",
  conv: Conv::None,
};
static EXIF_COMPOSITEIMAGE: ExifTag = ExifTag {
  id: 0xa460,
  name: "CompositeImage",
  conv: Conv::IntLabel(&[
    (0, "Unknown"),
    (1, "Not a Composite Image"),
    (2, "General Composite Image"),
    (3, "Composite Image Captured While Shooting"),
  ]),
};
static EXIF_COMPOSITEIMAGECOUNT: ExifTag = ExifTag {
  id: 0xa461,
  name: "CompositeImageCount",
  conv: Conv::None,
};
static EXIF_COMPOSITEIMAGEEXPOSURETIMES: ExifTag = ExifTag {
  id: 0xa462,
  name: "CompositeImageExposureTimes",
  conv: Conv::CompositeImageExposureTimes,
};

/// `Exif::Main` — the generated shadow (115 ids: the ported hand subset + the
/// binary-coverage-gap ids). Consulted by the hand `lookup` AFTER its own
/// table: a SHARED id always AGREES with the hand entry, and a gap id (NOT
/// in the hand table) is the only one this fallback actually returns.
pub fn lookup(id: u16) -> Option<&'static ExifTag> {
  match id {
    0x0001 => Some(&EXIF_INTEROPINDEX),
    0x0002 => Some(&EXIF_INTEROPVERSION),
    0x000b => Some(&EXIF_PROCESSINGSOFTWARE),
    0x00fe => Some(&EXIF_SUBFILETYPE),
    0x0100 => Some(&EXIF_IMAGEWIDTH),
    0x0101 => Some(&EXIF_IMAGEHEIGHT),
    0x0102 => Some(&EXIF_BITSPERSAMPLE),
    0x0103 => Some(&EXIF_COMPRESSION),
    0x0106 => Some(&EXIF_PHOTOMETRICINTERPRETATION),
    0x010d => Some(&EXIF_DOCUMENTNAME),
    0x010e => Some(&EXIF_IMAGEDESCRIPTION),
    0x010f => Some(&EXIF_MAKE),
    0x0110 => Some(&EXIF_MODEL),
    0x0111 => Some(&EXIF_STRIPOFFSETS),
    0x0112 => Some(&EXIF_ORIENTATION),
    0x0115 => Some(&EXIF_SAMPLESPERPIXEL),
    0x0116 => Some(&EXIF_ROWSPERSTRIP),
    0x0117 => Some(&EXIF_STRIPBYTECOUNTS),
    0x011a => Some(&EXIF_XRESOLUTION),
    0x011b => Some(&EXIF_YRESOLUTION),
    0x011c => Some(&EXIF_PLANARCONFIGURATION),
    0x0128 => Some(&EXIF_RESOLUTIONUNIT),
    0x0131 => Some(&EXIF_SOFTWARE),
    0x0132 => Some(&EXIF_MODIFYDATE),
    0x013b => Some(&EXIF_ARTIST),
    0x013c => Some(&EXIF_HOSTCOMPUTER),
    0x013d => Some(&EXIF_PREDICTOR),
    0x013e => Some(&EXIF_WHITEPOINT),
    0x013f => Some(&EXIF_PRIMARYCHROMATICITIES),
    0x0201 => Some(&EXIF_THUMBNAILOFFSET),
    0x0202 => Some(&EXIF_THUMBNAILLENGTH),
    0x0211 => Some(&EXIF_YCBCRCOEFFICIENTS),
    0x0213 => Some(&EXIF_YCBCRPOSITIONING),
    0x0214 => Some(&EXIF_REFERENCEBLACKWHITE),
    0x8298 => Some(&EXIF_COPYRIGHT),
    0x829a => Some(&EXIF_EXPOSURETIME),
    0x829d => Some(&EXIF_FNUMBER),
    0x8822 => Some(&EXIF_EXPOSUREPROGRAM),
    0x8824 => Some(&EXIF_SPECTRALSENSITIVITY),
    0x8827 => Some(&EXIF_ISO),
    0x8828 => Some(&EXIF_OPTO_ELECTRICCONVFACTOR),
    0x882a => Some(&EXIF_TIMEZONEOFFSET),
    0x8830 => Some(&EXIF_SENSITIVITYTYPE),
    0x8831 => Some(&EXIF_STANDARDOUTPUTSENSITIVITY),
    0x8832 => Some(&EXIF_RECOMMENDEDEXPOSUREINDEX),
    0x8833 => Some(&EXIF_ISOSPEED),
    0x8834 => Some(&EXIF_ISOSPEEDLATITUDEYYY),
    0x8835 => Some(&EXIF_ISOSPEEDLATITUDEZZZ),
    0x9000 => Some(&EXIF_EXIFVERSION),
    0x9003 => Some(&EXIF_DATETIMEORIGINAL),
    0x9004 => Some(&EXIF_CREATEDATE),
    0x9010 => Some(&EXIF_OFFSETTIME),
    0x9011 => Some(&EXIF_OFFSETTIMEORIGINAL),
    0x9012 => Some(&EXIF_OFFSETTIMEDIGITIZED),
    0x9101 => Some(&EXIF_COMPONENTSCONFIGURATION),
    0x9102 => Some(&EXIF_COMPRESSEDBITSPERPIXEL),
    0x9201 => Some(&EXIF_SHUTTERSPEEDVALUE),
    0x9202 => Some(&EXIF_APERTUREVALUE),
    0x9203 => Some(&EXIF_BRIGHTNESSVALUE),
    0x9204 => Some(&EXIF_EXPOSURECOMPENSATION),
    0x9205 => Some(&EXIF_MAXAPERTUREVALUE),
    0x9206 => Some(&EXIF_SUBJECTDISTANCE),
    0x9207 => Some(&EXIF_METERINGMODE),
    0x9208 => Some(&EXIF_LIGHTSOURCE),
    0x9209 => Some(&EXIF_FLASH),
    0x920a => Some(&EXIF_FOCALLENGTH),
    0x9211 => Some(&EXIF_IMAGENUMBER),
    0x9212 => Some(&EXIF_SECURITYCLASSIFICATION),
    0x9213 => Some(&EXIF_IMAGEHISTORY),
    0x9214 => Some(&EXIF_SUBJECTAREA),
    0x9286 => Some(&EXIF_USERCOMMENT),
    0x9290 => Some(&EXIF_SUBSECTIME),
    0x9291 => Some(&EXIF_SUBSECTIMEORIGINAL),
    0x9292 => Some(&EXIF_SUBSECTIMEDIGITIZED),
    0x9400 => Some(&EXIF_AMBIENTTEMPERATURE),
    0x9401 => Some(&EXIF_HUMIDITY),
    0x9402 => Some(&EXIF_PRESSURE),
    0x9403 => Some(&EXIF_WATERDEPTH),
    0x9404 => Some(&EXIF_ACCELERATION),
    0x9405 => Some(&EXIF_CAMERAELEVATIONANGLE),
    0xa000 => Some(&EXIF_FLASHPIXVERSION),
    0xa001 => Some(&EXIF_COLORSPACE),
    0xa002 => Some(&EXIF_EXIFIMAGEWIDTH),
    0xa003 => Some(&EXIF_EXIFIMAGEHEIGHT),
    0xa004 => Some(&EXIF_RELATEDSOUNDFILE),
    0xa20b => Some(&EXIF_FLASHENERGY),
    0xa20e => Some(&EXIF_FOCALPLANEXRESOLUTION),
    0xa20f => Some(&EXIF_FOCALPLANEYRESOLUTION),
    0xa210 => Some(&EXIF_FOCALPLANERESOLUTIONUNIT),
    0xa214 => Some(&EXIF_SUBJECTLOCATION),
    0xa215 => Some(&EXIF_EXPOSUREINDEX),
    0xa217 => Some(&EXIF_SENSINGMETHOD),
    0xa300 => Some(&EXIF_FILESOURCE),
    0xa301 => Some(&EXIF_SCENETYPE),
    0xa401 => Some(&EXIF_CUSTOMRENDERED),
    0xa402 => Some(&EXIF_EXPOSUREMODE),
    0xa403 => Some(&EXIF_WHITEBALANCE),
    0xa404 => Some(&EXIF_DIGITALZOOMRATIO),
    0xa405 => Some(&EXIF_FOCALLENGTHIN35MMFORMAT),
    0xa406 => Some(&EXIF_SCENECAPTURETYPE),
    0xa407 => Some(&EXIF_GAINCONTROL),
    0xa408 => Some(&EXIF_CONTRAST),
    0xa409 => Some(&EXIF_SATURATION),
    0xa40a => Some(&EXIF_SHARPNESS),
    0xa40c => Some(&EXIF_SUBJECTDISTANCERANGE),
    0xa420 => Some(&EXIF_IMAGEUNIQUEID),
    0xa430 => Some(&EXIF_OWNERNAME),
    0xa431 => Some(&EXIF_SERIALNUMBER),
    0xa432 => Some(&EXIF_LENSINFO),
    0xa433 => Some(&EXIF_LENSMAKE),
    0xa434 => Some(&EXIF_LENSMODEL),
    0xa435 => Some(&EXIF_LENSSERIALNUMBER),
    0xa460 => Some(&EXIF_COMPOSITEIMAGE),
    0xa461 => Some(&EXIF_COMPOSITEIMAGECOUNT),
    0xa462 => Some(&EXIF_COMPOSITEIMAGEEXPOSURETIMES),
    _ => None,
  }
}
