// generated by xtask gen-tables from exiftool -listx 13.59 — DO NOT EDIT
// (regenerate with `cargo xtask gen-tables --kind tagdef --module AAC \
//    --out <path>`)
// source table: AAC::Main

use crate::tagtable::{PrintConv, PrintConvHash, PrintValue, TagDef, TagId, ValueConv};

static MAIN_PROFILETYPE_MAP: &[(&str, PrintValue)] = &[
  ("0", PrintValue::Str("Main")),
  ("1", PrintValue::Str("Low Complexity")),
  ("2", PrintValue::Str("Scalable Sampling Rate")),
];
static MAIN_CHANNELS_MAP: &[(&str, PrintValue)] = &[
  ("0", PrintValue::Str("?")),
  ("1", PrintValue::I64(1)),
  ("2", PrintValue::I64(2)),
  ("3", PrintValue::I64(3)),
  ("4", PrintValue::I64(4)),
  ("5", PrintValue::I64(5)),
  ("6", PrintValue::Str("5+1")),
  ("7", PrintValue::Str("7+1")),
];

static MAIN_PROFILETYPE: TagDef = TagDef::new(
  "ProfileType",
  "AAC",
  ValueConv::None,
  PrintConv::Hash(PrintConvHash::direct(&MAIN_PROFILETYPE_MAP)),
);
static MAIN_SAMPLERATE: TagDef = TagDef::new("SampleRate", "AAC", ValueConv::None, PrintConv::None);
static MAIN_CHANNELS: TagDef = TagDef::new(
  "Channels",
  "AAC",
  ValueConv::None,
  PrintConv::Hash(PrintConvHash::direct(&MAIN_CHANNELS_MAP)),
);
static MAIN_ENCODER: TagDef = TagDef::new("Encoder", "AAC", ValueConv::None, PrintConv::None);

/// `AAC::Main` (g0 `AAC`, g1 `AAC`) — 4 tags.
pub fn get(id: TagId) -> Option<&'static TagDef> {
  match id {
    TagId::Str("Bit016-017") => Some(&MAIN_PROFILETYPE),
    TagId::Str("Bit018-021") => Some(&MAIN_SAMPLERATE),
    TagId::Str("Bit023-025") => Some(&MAIN_CHANNELS),
    TagId::Str("Encoder") => Some(&MAIN_ENCODER),
    _ => None,
  }
}
