// generated by xtask gen-tables from exiftool -listx 13.59 — DO NOT EDIT
// (regenerate with `cargo xtask gen-tables --kind tagdef --module AIFF \
//    --out <path>`)
// source table: AIFF::Common

use crate::tagtable::{PrintConv, PrintConvHash, PrintValue, TagDef, TagId, ValueConv};

static COMMON_COMPRESSIONTYPE_MAP: &[(&str, PrintValue)] = &[
  ("ACE2", PrintValue::Str("ACE 2-to-1")),
  ("ACE8", PrintValue::Str("ACE 8-to-3")),
  ("ALAW", PrintValue::Str("A-law")),
  ("G722", PrintValue::Str("G722")),
  ("G726", PrintValue::Str("G726")),
  ("G728", PrintValue::Str("G728")),
  ("GSM ", PrintValue::Str("GSM")),
  ("MAC3", PrintValue::Str("MAC 3-to-1")),
  ("MAC6", PrintValue::Str("MAC 6-to-1")),
  ("NONE", PrintValue::Str("None")),
  ("ULAW", PrintValue::Str("Mu-law")),
  ("alaw", PrintValue::Str("a-law")),
  ("sowt", PrintValue::Str("Little-endian, no compression")),
  ("ulaw", PrintValue::Str("mu-law")),
];

static COMMON_NUMCHANNELS: TagDef =
  TagDef::new("NumChannels", "AIFF", ValueConv::None, PrintConv::None);
static COMMON_NUMSAMPLEFRAMES: TagDef =
  TagDef::new("NumSampleFrames", "AIFF", ValueConv::None, PrintConv::None);
static COMMON_SAMPLESIZE: TagDef =
  TagDef::new("SampleSize", "AIFF", ValueConv::None, PrintConv::None);
static COMMON_SAMPLERATE: TagDef =
  TagDef::new("SampleRate", "AIFF", ValueConv::None, PrintConv::None);
static COMMON_COMPRESSIONTYPE: TagDef = TagDef::new(
  "CompressionType",
  "AIFF",
  ValueConv::None,
  PrintConv::Hash(PrintConvHash::direct(&COMMON_COMPRESSIONTYPE_MAP)),
);
static COMMON_COMPRESSORNAME: TagDef =
  TagDef::new("CompressorName", "AIFF", ValueConv::None, PrintConv::None);

/// `AIFF::Common` (g0 `AIFF`, g1 `AIFF`) — 6 tags.
pub fn get(id: TagId) -> Option<&'static TagDef> {
  match id {
    TagId::Int(0) => Some(&COMMON_NUMCHANNELS),
    TagId::Int(1) => Some(&COMMON_NUMSAMPLEFRAMES),
    TagId::Int(3) => Some(&COMMON_SAMPLESIZE),
    TagId::Int(4) => Some(&COMMON_SAMPLERATE),
    TagId::Int(9) => Some(&COMMON_COMPRESSIONTYPE),
    TagId::Int(11) => Some(&COMMON_COMPRESSORNAME),
    _ => None,
  }
}
