// generated by xtask gen-tables from exiftool -listx 13.59 — DO NOT EDIT
// (regenerate with `cargo xtask gen-tables --kind tagdef --module AIFF \
//    --out <path>`)
// source table: AIFF::Main

use crate::tagtable::{PrintConv, TagDef, TagId, ValueConv};

static MAIN_COPYRIGHT: TagDef = TagDef::new("Copyright", "AIFF", ValueConv::None, PrintConv::None);
static MAIN_ANNOTATION: TagDef =
  TagDef::new("Annotation", "AIFF", ValueConv::None, PrintConv::None);
static MAIN_APPLICATIONDATA: TagDef =
  TagDef::new("ApplicationData", "AIFF", ValueConv::None, PrintConv::None);
static MAIN_AUTHOR: TagDef = TagDef::new("Author", "AIFF", ValueConv::None, PrintConv::None);
static MAIN_NAME: TagDef = TagDef::new("Name", "AIFF", ValueConv::None, PrintConv::None);

/// `AIFF::Main` (g0 `AIFF`, g1 `AIFF`) — 5 tags.
pub fn get(id: TagId) -> Option<&'static TagDef> {
  match id {
    TagId::Str("(c) ") => Some(&MAIN_COPYRIGHT),
    TagId::Str("ANNO") => Some(&MAIN_ANNOTATION),
    TagId::Str("APPL") => Some(&MAIN_APPLICATIONDATA),
    TagId::Str("AUTH") => Some(&MAIN_AUTHOR),
    TagId::Str("NAME") => Some(&MAIN_NAME),
    _ => None,
  }
}
