// generated by xtask gen-tables from exiftool -listx 13.59 — DO NOT EDIT
// (regenerate with `cargo xtask gen-tables --kind tagdef --module APE \
//    --out <path>`)
// source table: APE::Main

use crate::tagtable::{PrintConv, TagDef, TagId, ValueConv};

static MAIN_ALBUM: TagDef = TagDef::new("Album", "APE", ValueConv::None, PrintConv::None);
static MAIN_ARTIST: TagDef = TagDef::new("Artist", "APE", ValueConv::None, PrintConv::None);
static MAIN_DURATION: TagDef = TagDef::new("Duration", "APE", ValueConv::None, PrintConv::None);
static MAIN_GENRE: TagDef = TagDef::new("Genre", "APE", ValueConv::None, PrintConv::None);
static MAIN_TITLE: TagDef = TagDef::new("Title", "APE", ValueConv::None, PrintConv::None);
static MAIN_TOOLNAME: TagDef = TagDef::new("ToolName", "APE", ValueConv::None, PrintConv::None);
static MAIN_TOOLVERSION: TagDef =
  TagDef::new("ToolVersion", "APE", ValueConv::None, PrintConv::None);
static MAIN_TRACK: TagDef = TagDef::new("Track", "APE", ValueConv::None, PrintConv::None);
static MAIN_YEAR: TagDef = TagDef::new("Year", "APE", ValueConv::None, PrintConv::None);

/// `APE::Main` (g0 `APE`, g1 `APE`) — 9 tags.
pub fn get(id: TagId) -> Option<&'static TagDef> {
  match id {
    TagId::Str("Album") => Some(&MAIN_ALBUM),
    TagId::Str("Artist") => Some(&MAIN_ARTIST),
    TagId::Str("DURATION") => Some(&MAIN_DURATION),
    TagId::Str("Genre") => Some(&MAIN_GENRE),
    TagId::Str("Title") => Some(&MAIN_TITLE),
    TagId::Str("Tool Name") => Some(&MAIN_TOOLNAME),
    TagId::Str("Tool Version") => Some(&MAIN_TOOLVERSION),
    TagId::Str("Track") => Some(&MAIN_TRACK),
    TagId::Str("Year") => Some(&MAIN_YEAR),
    _ => None,
  }
}
