// generated by xtask gen-tables from exiftool -listx 13.59 — DO NOT EDIT
// (regenerate with `cargo xtask gen-tables --kind tagdef --module File \
//    --out <path>`)
// source table: DSF::Main

use crate::tagtable::{PrintConv, PrintConvHash, PrintValue, TagDef, TagId, ValueConv};

static MAIN_FORMATID_MAP: &[(&str, PrintValue)] = &[("0", PrintValue::Str("DSD Raw"))];
static MAIN_CHANNELTYPE_MAP: &[(&str, PrintValue)] = &[
  ("1", PrintValue::Str("Mono")),
  ("2", PrintValue::Str("Stereo (Left, Right)")),
  ("3", PrintValue::Str("3 Channels (Left, Right, Center)")),
  ("4", PrintValue::Str("Quad (Left, Right, Back L, Back R)")),
  (
    "5",
    PrintValue::Str("4 Channels (Left, Right, Center, Bass)"),
  ),
  (
    "6",
    PrintValue::Str("5 Channels (Left, Right, Center, Back L, Back R)"),
  ),
  (
    "7",
    PrintValue::Str("5.1 Channels (Left, Right, Center, Bass, Back L, Back R)"),
  ),
];

static MAIN_FORMATVERSION: TagDef =
  TagDef::new("FormatVersion", "File", ValueConv::None, PrintConv::None);
static MAIN_FORMATID: TagDef = TagDef::new(
  "FormatID",
  "File",
  ValueConv::None,
  PrintConv::Hash(PrintConvHash::direct(&MAIN_FORMATID_MAP)),
);
static MAIN_CHANNELTYPE: TagDef = TagDef::new(
  "ChannelType",
  "File",
  ValueConv::None,
  PrintConv::Hash(PrintConvHash::direct(&MAIN_CHANNELTYPE_MAP)),
);
static MAIN_CHANNELCOUNT: TagDef =
  TagDef::new("ChannelCount", "File", ValueConv::None, PrintConv::None);
static MAIN_SAMPLERATE: TagDef =
  TagDef::new("SampleRate", "File", ValueConv::None, PrintConv::None);
static MAIN_BITSPERSAMPLE: TagDef =
  TagDef::new("BitsPerSample", "File", ValueConv::None, PrintConv::None);
static MAIN_SAMPLECOUNT: TagDef =
  TagDef::new("SampleCount", "File", ValueConv::None, PrintConv::None);
static MAIN_BLOCKSIZE: TagDef = TagDef::new("BlockSize", "File", ValueConv::None, PrintConv::None);

/// `DSF::Main` (g0 `File`, g1 `File`) — 8 tags.
pub fn get(id: TagId) -> Option<&'static TagDef> {
  match id {
    TagId::Int(3) => Some(&MAIN_FORMATVERSION),
    TagId::Int(4) => Some(&MAIN_FORMATID),
    TagId::Int(5) => Some(&MAIN_CHANNELTYPE),
    TagId::Int(6) => Some(&MAIN_CHANNELCOUNT),
    TagId::Int(7) => Some(&MAIN_SAMPLERATE),
    TagId::Int(8) => Some(&MAIN_BITSPERSAMPLE),
    TagId::Int(9) => Some(&MAIN_SAMPLECOUNT),
    TagId::Int(11) => Some(&MAIN_BLOCKSIZE),
    _ => None,
  }
}
