// generated by xtask gen-tables from exiftool -listx 13.59 — DO NOT EDIT
// (regenerate with `cargo xtask gen-tables --kind tagdef --module DV \
//    --out <path>`)
// source table: DV::Main

use crate::tagtable::{PrintConv, TagDef, TagId, ValueConv};

static MAIN_ASPECTRATIO: TagDef =
  TagDef::new("AspectRatio", "DV", ValueConv::None, PrintConv::None);
static MAIN_AUDIOBITSPERSAMPLE: TagDef =
  TagDef::new("AudioBitsPerSample", "DV", ValueConv::None, PrintConv::None);
static MAIN_AUDIOCHANNELS: TagDef =
  TagDef::new("AudioChannels", "DV", ValueConv::None, PrintConv::None);
static MAIN_AUDIOSAMPLERATE: TagDef =
  TagDef::new("AudioSampleRate", "DV", ValueConv::None, PrintConv::None);
static MAIN_COLORIMETRY: TagDef =
  TagDef::new("Colorimetry", "DV", ValueConv::None, PrintConv::None);
static MAIN_DATETIMEORIGINAL: TagDef =
  TagDef::new("DateTimeOriginal", "DV", ValueConv::None, PrintConv::None);
static MAIN_DURATION: TagDef = TagDef::new("Duration", "DV", ValueConv::None, PrintConv::None);
static MAIN_FRAMERATE: TagDef = TagDef::new("FrameRate", "DV", ValueConv::None, PrintConv::None);
static MAIN_IMAGEHEIGHT: TagDef =
  TagDef::new("ImageHeight", "DV", ValueConv::None, PrintConv::None);
static MAIN_IMAGEWIDTH: TagDef = TagDef::new("ImageWidth", "DV", ValueConv::None, PrintConv::None);
static MAIN_TOTALBITRATE: TagDef =
  TagDef::new("TotalBitrate", "DV", ValueConv::None, PrintConv::None);
static MAIN_VIDEOFORMAT: TagDef =
  TagDef::new("VideoFormat", "DV", ValueConv::None, PrintConv::None);
static MAIN_VIDEOSCANTYPE: TagDef =
  TagDef::new("VideoScanType", "DV", ValueConv::None, PrintConv::None);

/// `DV::Main` (g0 `DV`, g1 `DV`) — 13 tags.
pub fn get(id: TagId) -> Option<&'static TagDef> {
  match id {
    TagId::Str("AspectRatio") => Some(&MAIN_ASPECTRATIO),
    TagId::Str("AudioBitsPerSample") => Some(&MAIN_AUDIOBITSPERSAMPLE),
    TagId::Str("AudioChannels") => Some(&MAIN_AUDIOCHANNELS),
    TagId::Str("AudioSampleRate") => Some(&MAIN_AUDIOSAMPLERATE),
    TagId::Str("Colorimetry") => Some(&MAIN_COLORIMETRY),
    TagId::Str("DateTimeOriginal") => Some(&MAIN_DATETIMEORIGINAL),
    TagId::Str("Duration") => Some(&MAIN_DURATION),
    TagId::Str("FrameRate") => Some(&MAIN_FRAMERATE),
    TagId::Str("ImageHeight") => Some(&MAIN_IMAGEHEIGHT),
    TagId::Str("ImageWidth") => Some(&MAIN_IMAGEWIDTH),
    TagId::Str("TotalBitrate") => Some(&MAIN_TOTALBITRATE),
    TagId::Str("VideoFormat") => Some(&MAIN_VIDEOFORMAT),
    TagId::Str("VideoScanType") => Some(&MAIN_VIDEOSCANTYPE),
    _ => None,
  }
}
