// generated by xtask gen-tables from exiftool -listx 13.59 — DO NOT EDIT
// (regenerate with `cargo xtask gen-tables --kind tagdef --module FLAC \
//    --out <path>`)
// source table: FLAC::StreamInfo

use crate::tagtable::{PrintConv, TagDef, TagId, ValueConv};

static STREAMINFO_BLOCKSIZEMIN: TagDef =
  TagDef::new("BlockSizeMin", "FLAC", ValueConv::None, PrintConv::None);
static STREAMINFO_BLOCKSIZEMAX: TagDef =
  TagDef::new("BlockSizeMax", "FLAC", ValueConv::None, PrintConv::None);
static STREAMINFO_FRAMESIZEMIN: TagDef =
  TagDef::new("FrameSizeMin", "FLAC", ValueConv::None, PrintConv::None);
static STREAMINFO_FRAMESIZEMAX: TagDef =
  TagDef::new("FrameSizeMax", "FLAC", ValueConv::None, PrintConv::None);
static STREAMINFO_SAMPLERATE: TagDef =
  TagDef::new("SampleRate", "FLAC", ValueConv::None, PrintConv::None);
static STREAMINFO_CHANNELS: TagDef =
  TagDef::new("Channels", "FLAC", ValueConv::None, PrintConv::None);
static STREAMINFO_BITSPERSAMPLE: TagDef =
  TagDef::new("BitsPerSample", "FLAC", ValueConv::None, PrintConv::None);
static STREAMINFO_TOTALSAMPLES: TagDef =
  TagDef::new("TotalSamples", "FLAC", ValueConv::None, PrintConv::None);
static STREAMINFO_MD5SIGNATURE: TagDef =
  TagDef::new("MD5Signature", "FLAC", ValueConv::None, PrintConv::None);

/// `FLAC::StreamInfo` (g0 `FLAC`, g1 `FLAC`) — 9 tags.
pub fn get(id: TagId) -> Option<&'static TagDef> {
  match id {
    TagId::Str("Bit000-015") => Some(&STREAMINFO_BLOCKSIZEMIN),
    TagId::Str("Bit016-031") => Some(&STREAMINFO_BLOCKSIZEMAX),
    TagId::Str("Bit032-055") => Some(&STREAMINFO_FRAMESIZEMIN),
    TagId::Str("Bit056-079") => Some(&STREAMINFO_FRAMESIZEMAX),
    TagId::Str("Bit080-099") => Some(&STREAMINFO_SAMPLERATE),
    TagId::Str("Bit100-102") => Some(&STREAMINFO_CHANNELS),
    TagId::Str("Bit103-107") => Some(&STREAMINFO_BITSPERSAMPLE),
    TagId::Str("Bit108-143") => Some(&STREAMINFO_TOTALSAMPLES),
    TagId::Str("Bit144-271") => Some(&STREAMINFO_MD5SIGNATURE),
    _ => None,
  }
}
