// generated by xtask gen-tables from exiftool -listx 13.59 — DO NOT EDIT
// (regenerate with `cargo xtask gen-tables --kind tagdef --module FLAC \
//    --out <path>`)
// source table: FLAC::Picture

use crate::tagtable::{PrintConv, PrintConvHash, PrintValue, TagDef, TagId, ValueConv};

static PICTURE_PICTURETYPE_MAP: &[(&str, PrintValue)] = &[
  ("0", PrintValue::Str("Other")),
  ("1", PrintValue::Str("32x32 PNG Icon")),
  ("2", PrintValue::Str("Other Icon")),
  ("3", PrintValue::Str("Front Cover")),
  ("4", PrintValue::Str("Back Cover")),
  ("5", PrintValue::Str("Leaflet")),
  ("6", PrintValue::Str("Media")),
  ("7", PrintValue::Str("Lead Artist")),
  ("8", PrintValue::Str("Artist")),
  ("9", PrintValue::Str("Conductor")),
  ("10", PrintValue::Str("Band")),
  ("11", PrintValue::Str("Composer")),
  ("12", PrintValue::Str("Lyricist")),
  ("13", PrintValue::Str("Recording Studio or Location")),
  ("14", PrintValue::Str("Recording Session")),
  ("15", PrintValue::Str("Performance")),
  ("16", PrintValue::Str("Capture from Movie or Video")),
  ("17", PrintValue::Str("Bright(ly) Colored Fish")),
  ("18", PrintValue::Str("Illustration")),
  ("19", PrintValue::Str("Band Logo")),
  ("20", PrintValue::Str("Publisher Logo")),
];

static PICTURE_PICTURETYPE: TagDef = TagDef::new(
  "PictureType",
  "FLAC",
  ValueConv::None,
  PrintConv::Hash(PrintConvHash::direct(&PICTURE_PICTURETYPE_MAP)),
);
static PICTURE_PICTUREMIMETYPE: TagDef =
  TagDef::new("PictureMIMEType", "FLAC", ValueConv::None, PrintConv::None);
static PICTURE_PICTUREDESCRIPTION: TagDef = TagDef::new(
  "PictureDescription",
  "FLAC",
  ValueConv::None,
  PrintConv::None,
);
static PICTURE_PICTUREWIDTH: TagDef =
  TagDef::new("PictureWidth", "FLAC", ValueConv::None, PrintConv::None);
static PICTURE_PICTUREHEIGHT: TagDef =
  TagDef::new("PictureHeight", "FLAC", ValueConv::None, PrintConv::None);
static PICTURE_PICTUREBITSPERPIXEL: TagDef = TagDef::new(
  "PictureBitsPerPixel",
  "FLAC",
  ValueConv::None,
  PrintConv::None,
);
static PICTURE_PICTUREINDEXEDCOLORS: TagDef = TagDef::new(
  "PictureIndexedColors",
  "FLAC",
  ValueConv::None,
  PrintConv::None,
);
static PICTURE_PICTURELENGTH: TagDef =
  TagDef::new("PictureLength", "FLAC", ValueConv::None, PrintConv::None);
static PICTURE_PICTURE: TagDef = TagDef::new("Picture", "FLAC", ValueConv::None, PrintConv::None);

/// `FLAC::Picture` (g0 `FLAC`, g1 `FLAC`) — 9 tags.
pub fn get(id: TagId) -> Option<&'static TagDef> {
  match id {
    TagId::Int(0) => Some(&PICTURE_PICTURETYPE),
    TagId::Int(1) => Some(&PICTURE_PICTUREMIMETYPE),
    TagId::Int(2) => Some(&PICTURE_PICTUREDESCRIPTION),
    TagId::Int(3) => Some(&PICTURE_PICTUREWIDTH),
    TagId::Int(4) => Some(&PICTURE_PICTUREHEIGHT),
    TagId::Int(5) => Some(&PICTURE_PICTUREBITSPERPIXEL),
    TagId::Int(6) => Some(&PICTURE_PICTUREINDEXEDCOLORS),
    TagId::Int(7) => Some(&PICTURE_PICTURELENGTH),
    TagId::Int(8) => Some(&PICTURE_PICTURE),
    _ => None,
  }
}
