// generated by xtask gen-tables from exiftool -listx 13.59 — DO NOT EDIT
// (regenerate with `cargo xtask gen-tables --kind tagdef --module FLAC \
//    --out <path>`)
// source table: FLAC::Main

use crate::tagtable::{PrintConv, TagDef, TagId, ValueConv};

static MAIN_PADDING: TagDef = TagDef::new("Padding", "FLAC", ValueConv::None, PrintConv::None);
static MAIN_APPLICATIONUNKNOWN: TagDef = TagDef::new(
  "ApplicationUnknown",
  "FLAC",
  ValueConv::None,
  PrintConv::None,
);
static MAIN_SEEKTABLE: TagDef = TagDef::new("SeekTable", "FLAC", ValueConv::None, PrintConv::None);
static MAIN_CUESHEET: TagDef = TagDef::new("CueSheet", "FLAC", ValueConv::None, PrintConv::None);

/// `FLAC::Main` (g0 `FLAC`, g1 `FLAC`) — 4 tags.
pub fn get(id: TagId) -> Option<&'static TagDef> {
  match id {
    TagId::Int(1) => Some(&MAIN_PADDING),
    TagId::Int(2) => Some(&MAIN_APPLICATIONUNKNOWN),
    TagId::Int(3) => Some(&MAIN_SEEKTABLE),
    TagId::Int(5) => Some(&MAIN_CUESHEET),
    _ => None,
  }
}
