// generated by xtask gen-tables from exiftool -listx 13.59 — DO NOT EDIT
// (regenerate with `cargo xtask gen-tables --kind tagdef --module MPC \
//    --out <path>`)
// source table: MPC::Main

use crate::tagtable::{PrintConv, PrintConvHash, PrintValue, TagDef, TagId, ValueConv};

static MAIN_SAMPLERATE_MAP: &[(&str, PrintValue)] = &[
  ("0", PrintValue::I64(44100)),
  ("1", PrintValue::I64(48000)),
  ("2", PrintValue::I64(37800)),
  ("3", PrintValue::I64(32000)),
];
static MAIN_QUALITY_MAP: &[(&str, PrintValue)] = &[
  ("1", PrintValue::Str("Unstable/Experimental")),
  ("5", PrintValue::I64(0)),
  ("6", PrintValue::I64(1)),
  ("7", PrintValue::Str("2 (Telephone)")),
  ("8", PrintValue::Str("3 (Thumb)")),
  ("9", PrintValue::Str("4 (Radio)")),
  ("10", PrintValue::Str("5 (Standard)")),
  ("11", PrintValue::Str("6 (Xtreme)")),
  ("12", PrintValue::Str("7 (Insane)")),
  ("13", PrintValue::Str("8 (BrainDead)")),
  ("14", PrintValue::I64(9)),
  ("15", PrintValue::I64(10)),
];
static MAIN_FASTSEEK_MAP: &[(&str, PrintValue)] =
  &[("0", PrintValue::Str("No")), ("1", PrintValue::Str("Yes"))];
static MAIN_GAPLESS_MAP: &[(&str, PrintValue)] =
  &[("0", PrintValue::Str("No")), ("1", PrintValue::Str("Yes"))];

static MAIN_TOTALFRAMES: TagDef =
  TagDef::new("TotalFrames", "MPC", ValueConv::None, PrintConv::None);
static MAIN_SAMPLERATE: TagDef = TagDef::new(
  "SampleRate",
  "MPC",
  ValueConv::None,
  PrintConv::Hash(PrintConvHash::direct(&MAIN_SAMPLERATE_MAP)),
);
static MAIN_QUALITY: TagDef = TagDef::new(
  "Quality",
  "MPC",
  ValueConv::None,
  PrintConv::Hash(PrintConvHash::direct(&MAIN_QUALITY_MAP)),
);
static MAIN_MAXBAND: TagDef = TagDef::new("MaxBand", "MPC", ValueConv::None, PrintConv::None);
static MAIN_REPLAYGAINTRACKPEAK: TagDef = TagDef::new(
  "ReplayGainTrackPeak",
  "MPC",
  ValueConv::None,
  PrintConv::None,
);
static MAIN_REPLAYGAINTRACKGAIN: TagDef = TagDef::new(
  "ReplayGainTrackGain",
  "MPC",
  ValueConv::None,
  PrintConv::None,
);
static MAIN_REPLAYGAINALBUMPEAK: TagDef = TagDef::new(
  "ReplayGainAlbumPeak",
  "MPC",
  ValueConv::None,
  PrintConv::None,
);
static MAIN_REPLAYGAINALBUMGAIN: TagDef = TagDef::new(
  "ReplayGainAlbumGain",
  "MPC",
  ValueConv::None,
  PrintConv::None,
);
static MAIN_FASTSEEK: TagDef = TagDef::new(
  "FastSeek",
  "MPC",
  ValueConv::None,
  PrintConv::Hash(PrintConvHash::direct(&MAIN_FASTSEEK_MAP)),
);
static MAIN_GAPLESS: TagDef = TagDef::new(
  "Gapless",
  "MPC",
  ValueConv::None,
  PrintConv::Hash(PrintConvHash::direct(&MAIN_GAPLESS_MAP)),
);
static MAIN_ENCODERVERSION: TagDef =
  TagDef::new("EncoderVersion", "MPC", ValueConv::None, PrintConv::None);

/// `MPC::Main` (g0 `MPC`, g1 `MPC`) — 11 tags.
pub fn get(id: TagId) -> Option<&'static TagDef> {
  match id {
    TagId::Str("Bit032-063") => Some(&MAIN_TOTALFRAMES),
    TagId::Str("Bit080-081") => Some(&MAIN_SAMPLERATE),
    TagId::Str("Bit084-087") => Some(&MAIN_QUALITY),
    TagId::Str("Bit088-093") => Some(&MAIN_MAXBAND),
    TagId::Str("Bit096-111") => Some(&MAIN_REPLAYGAINTRACKPEAK),
    TagId::Str("Bit112-127") => Some(&MAIN_REPLAYGAINTRACKGAIN),
    TagId::Str("Bit128-143") => Some(&MAIN_REPLAYGAINALBUMPEAK),
    TagId::Str("Bit144-159") => Some(&MAIN_REPLAYGAINALBUMGAIN),
    TagId::Str("Bit179") => Some(&MAIN_FASTSEEK),
    TagId::Str("Bit191") => Some(&MAIN_GAPLESS),
    TagId::Str("Bit216-223") => Some(&MAIN_ENCODERVERSION),
    _ => None,
  }
}
