// generated by xtask gen-tables from exiftool -listx 13.59 — DO NOT EDIT
// (regenerate with `cargo xtask gen-tables --kind tagdef --module Vorbis \
//    --out <path>`)
// source table: Vorbis::Comments

use crate::tagtable::{PrintConv, TagDef, TagId, ValueConv};

static COMMENTS_ACTOR: TagDef = TagDef::new("Actor", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_ALBUM: TagDef = TagDef::new("Album", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_ARTIST: TagDef = TagDef::new("Artist", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_COMMENT: TagDef =
  TagDef::new("Comment", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_COMPOSER: TagDef =
  TagDef::new("Composer", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_CONTACT: TagDef =
  TagDef::new("Contact", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_COPYRIGHT: TagDef =
  TagDef::new("Copyright", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_COVERART: TagDef =
  TagDef::new("CoverArt", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_COVERARTMIMETYPE: TagDef = TagDef::new(
  "CoverArtMIMEType",
  "Vorbis",
  ValueConv::None,
  PrintConv::None,
);
static COMMENTS_DATE: TagDef = TagDef::new("Date", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_DESCRIPTION: TagDef =
  TagDef::new("Description", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_DIRECTOR: TagDef =
  TagDef::new("Director", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_ENCODEDBY: TagDef =
  TagDef::new("EncodedBy", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_ENCODEDUSING: TagDef =
  TagDef::new("EncodedUsing", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_ENCODER: TagDef =
  TagDef::new("Encoder", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_ENCODEROPTIONS: TagDef =
  TagDef::new("EncoderOptions", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_GENRE: TagDef = TagDef::new("Genre", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_ISRCNUMBER: TagDef =
  TagDef::new("ISRCNumber", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_LICENSE: TagDef =
  TagDef::new("License", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_LOCATION: TagDef =
  TagDef::new("Location", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_ORGANIZATION: TagDef =
  TagDef::new("Organization", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_PERFORMER: TagDef =
  TagDef::new("Performer", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_PRODUCER: TagDef =
  TagDef::new("Producer", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_REPLAYGAINALBUMGAIN: TagDef = TagDef::new(
  "ReplayGainAlbumGain",
  "Vorbis",
  ValueConv::None,
  PrintConv::None,
);
static COMMENTS_REPLAYGAINALBUMPEAK: TagDef = TagDef::new(
  "ReplayGainAlbumPeak",
  "Vorbis",
  ValueConv::None,
  PrintConv::None,
);
static COMMENTS_REPLAYGAINTRACKGAIN: TagDef = TagDef::new(
  "ReplayGainTrackGain",
  "Vorbis",
  ValueConv::None,
  PrintConv::None,
);
static COMMENTS_REPLAYGAINTRACKPEAK: TagDef = TagDef::new(
  "ReplayGainTrackPeak",
  "Vorbis",
  ValueConv::None,
  PrintConv::None,
);
static COMMENTS_TITLE: TagDef = TagDef::new("Title", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_TRACKNUMBER: TagDef =
  TagDef::new("TrackNumber", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_VERSION: TagDef =
  TagDef::new("Version", "Vorbis", ValueConv::None, PrintConv::None);
static COMMENTS_VENDOR: TagDef = TagDef::new("Vendor", "Vorbis", ValueConv::None, PrintConv::None);

/// `Vorbis::Comments` (g0 `Vorbis`, g1 `Vorbis`) — 31 tags.
pub fn get(id: TagId) -> Option<&'static TagDef> {
  match id {
    TagId::Str("ACTOR") => Some(&COMMENTS_ACTOR),
    TagId::Str("ALBUM") => Some(&COMMENTS_ALBUM),
    TagId::Str("ARTIST") => Some(&COMMENTS_ARTIST),
    TagId::Str("COMMENT") => Some(&COMMENTS_COMMENT),
    TagId::Str("COMPOSER") => Some(&COMMENTS_COMPOSER),
    TagId::Str("CONTACT") => Some(&COMMENTS_CONTACT),
    TagId::Str("COPYRIGHT") => Some(&COMMENTS_COPYRIGHT),
    TagId::Str("COVERART") => Some(&COMMENTS_COVERART),
    TagId::Str("COVERARTMIME") => Some(&COMMENTS_COVERARTMIMETYPE),
    TagId::Str("DATE") => Some(&COMMENTS_DATE),
    TagId::Str("DESCRIPTION") => Some(&COMMENTS_DESCRIPTION),
    TagId::Str("DIRECTOR") => Some(&COMMENTS_DIRECTOR),
    TagId::Str("ENCODED_BY") => Some(&COMMENTS_ENCODEDBY),
    TagId::Str("ENCODED_USING") => Some(&COMMENTS_ENCODEDUSING),
    TagId::Str("ENCODER") => Some(&COMMENTS_ENCODER),
    TagId::Str("ENCODER_OPTIONS") => Some(&COMMENTS_ENCODEROPTIONS),
    TagId::Str("GENRE") => Some(&COMMENTS_GENRE),
    TagId::Str("ISRC") => Some(&COMMENTS_ISRCNUMBER),
    TagId::Str("LICENSE") => Some(&COMMENTS_LICENSE),
    TagId::Str("LOCATION") => Some(&COMMENTS_LOCATION),
    TagId::Str("ORGANIZATION") => Some(&COMMENTS_ORGANIZATION),
    TagId::Str("PERFORMER") => Some(&COMMENTS_PERFORMER),
    TagId::Str("PRODUCER") => Some(&COMMENTS_PRODUCER),
    TagId::Str("REPLAYGAIN_ALBUM_GAIN") => Some(&COMMENTS_REPLAYGAINALBUMGAIN),
    TagId::Str("REPLAYGAIN_ALBUM_PEAK") => Some(&COMMENTS_REPLAYGAINALBUMPEAK),
    TagId::Str("REPLAYGAIN_TRACK_GAIN") => Some(&COMMENTS_REPLAYGAINTRACKGAIN),
    TagId::Str("REPLAYGAIN_TRACK_PEAK") => Some(&COMMENTS_REPLAYGAINTRACKPEAK),
    TagId::Str("TITLE") => Some(&COMMENTS_TITLE),
    TagId::Str("TRACKNUMBER") => Some(&COMMENTS_TRACKNUMBER),
    TagId::Str("VERSION") => Some(&COMMENTS_VERSION),
    TagId::Str("vendor") => Some(&COMMENTS_VENDOR),
    _ => None,
  }
}
