// generated by xtask gen-tables from exiftool -listx 13.59 — DO NOT EDIT
// (regenerate with `cargo xtask gen-tables --kind quicktime \
//    --module QuickTime::UserData \
//    --out src/formats/quicktime_generated.rs`)
//
// SP2 supplementary conv-less camera-atom map: the plain-string
// `%QuickTime::UserData` (4cc keys) and `%QuickTime::Keys` (string keys)
// atoms that carry NO RawConv/ValueConv/PrintConv-sub and NO Avoid/Priority
// in QuickTime.pm — each hand-verified against the Perl source (`-listx`
// alone cannot prove conv-less, cf. CAME/MUID which look plain but carry a
// hex ValueConv → kept in UNPORTED + hand-ported). The walker consults
// these to emit a `QuickTime:UserData` / `QuickTime:Keys` tag by Name.

use super::ConvlessAtom;

/// `%QuickTime::UserData` (g0 `QuickTime`, g1 `UserData`) conv-less plain-string atoms,
/// keyed by the raw 4-character-code bytes (the `©`-prefixed and `FOV\0`
/// atoms carry their non-ASCII bytes verbatim). 9 atoms.
pub static QUICKTIME_USERDATA_CONVLESS: &[ConvlessAtom<&[u8]>] = &[
  ConvlessAtom::new(&[0x47, 0x6f, 0x50, 0x72], "GoProType"),
  ConvlessAtom::new(&[0x4c, 0x45, 0x4e, 0x53], "LensSerialNumber"),
  ConvlessAtom::new(&[0x46, 0x4f, 0x56, 0x00], "FieldOfView"),
  ConvlessAtom::new(&[0xa9, 0x6d, 0x61, 0x6c], "MakerURL"),
  ConvlessAtom::new(&[0xa9, 0x67, 0x70, 0x74], "CameraPitch"),
  ConvlessAtom::new(&[0xa9, 0x67, 0x79, 0x77], "CameraYaw"),
  ConvlessAtom::new(&[0xa9, 0x67, 0x72, 0x6c], "CameraRoll"),
  ConvlessAtom::new(&[0xa9, 0x66, 0x6d, 0x74], "Format"),
  ConvlessAtom::new(&[0xa9, 0x69, 0x6e, 0x66], "Information"),
];

/// `%QuickTime::Keys` (g0 `QuickTime`, g1 `Keys`) conv-less plain-string atoms,
/// keyed by the key string (after the `com.apple.quicktime.` strip the
/// walker applies). 2 atoms.
pub static QUICKTIME_KEYS_CONVLESS: &[ConvlessAtom<&str>] = &[
  ConvlessAtom::new("direction.facing", "CameraDirection"),
  ConvlessAtom::new("direction.motion", "CameraMotion"),
];

/// Candidate camera atoms that LOOK conv-less in `-listx` but carry a
/// ValueConv / float decode / group in `QuickTime.pm`, so they are NOT in
/// the maps above — they stay HAND-ported in the typed walker (faithful to
/// the conv). Listed here for audit + drift coverage.
pub static UNPORTED: &[&str] = &[
  "SerialNumberHash",
  "MediaUID",
  "AndroidCaptureFPS",
  "AndroidTimeZone",
];
