// SPDX-License-Identifier: GPL-3.0-or-later
// exifast — a 1:1 Rust port of ExifTool (Phil Harvey). See THIRD_PARTY.md.

//! Render [`TableModel`]s as committed Rust source in the XMP module's
//! `Field::make(...)` vocabulary (`Writable as W` / `PrintConv as P`).
//!
//! Two entry points:
//!
//! * [`emit_table`] — one table → a `pub static FIELDS: &[Field]` (the
//!   single-namespace path the Task-5/6 unit tests pin).
//! * [`emit_xmp_tables`] — EVERY `XMP`-group table → one committed file with a
//!   `pub static GEN_<NS>: &[Field]` per namespace + a `GEN_NS_TABLES` index
//!   (the full XMP surface, Task 7).
//!
//! The emitted file is a child module of `src/formats/xmp/` so it
//! `use super::tables::{Field, PrintConv as P, Writable as W}` and the
//! crate-local `Field::make` constructor is in scope. A PrintConv value-map is
//! a sorted `&[(i64, &str)]` / `&[(&str, &str)]` slice const when SMALL, or a
//! `phf::Map<&'static str, &'static str>` (built by `phf_codegen`) when it has
//! more than [`PHF_THRESHOLD`] entries — both keyed by the RAW scalar string so
//! the `apply_print_conv` lookup is the faithful `$$conv{$val}` exact-string
//! match (ExifTool.pm:3604). A code-valued, map-less conv flagged by the
//! [`crate::conv_registry`] becomes `P::Unported("<module>:<Tag>")`.

use crate::conv_registry::{resolve_printconv, Conv};
use crate::listx::TableModel;
use std::fmt::Write as _;

/// Value-maps with MORE than this many entries are emitted as a
/// `phf::Map<&str, &str>` (O(1) lookup); smaller maps stay a sorted slice +
/// linear stringified scan (no perceptible cost, smaller codegen, and the
/// representation the hand-written tables already use). Across the full XMP
/// surface only 3 maps exceed 24 (PLUS `MediaSummaryCode` = 2143 entries,
/// `tiff:Compression` = 53, `exif:LightSource` = 32), so the threshold keeps
/// the generated file overwhelmingly slice-based while giving the one giant
/// string map an O(1) lookup. Resolves #46/FU-4 for the generated maps.
pub const PHF_THRESHOLD: usize = 24;

/// Render `model` as committed Rust source for the XMP module (single-table
/// path; the all-namespaces path is [`emit_xmp_tables`]).
pub fn emit_table(model: &TableModel) -> String {
  let mut out = String::new();
  out.push_str("// generated by xtask gen-tables from exiftool -listx 13.59 — DO NOT EDIT\n");
  let _ = writeln!(
    out,
    "// (regenerate with `cargo xtask gen-tables --module {}`)",
    module_arg(model)
  );
  out.push_str("// source table: ");
  out.push_str(&model.name);
  out.push('\n');
  out.push_str("\nuse super::tables::{Field, PrintConv as P, Writable as W};\n\n");

  let mut map_consts = String::new();
  let mut fields = String::new();
  for t in &model.tags {
    let p = field_print_conv(&model.name, t, &mut map_consts);
    let _ = writeln!(
      fields,
      "  Field::make(\"{}\", {}, {}, {}),",
      t.id,
      name_arg(t),
      writable_variant(t.ty.as_deref()),
      p
    );
  }

  out.push_str(&map_consts);
  if !map_consts.is_empty() {
    out.push('\n');
  }
  out.push_str("pub static FIELDS: &[Field] = &[\n");
  out.push_str(&fields);
  out.push_str("];\n");
  out
}

/// Render EVERY `XMP`-group `<table>` as one committed file: per-namespace
/// `pub static GEN_<NS>: &[Field]`, the value-map consts (slices + phf), and a
/// `pub static GEN_NS_TABLES: &[(&str, &[Field])]` index keyed by the routing
/// namespace (the `XMP-<ns>` family-1 group with `XMP-` stripped). The hand
/// table wires its 7 namespaces' `GEN_<NS>` slices as the fallback layer; the
/// rest are surfaced as generated-only namespace tables (see `tables.rs`).
///
/// Tables are emitted in namespace-sorted order for a deterministic,
/// review-stable file; `--check` (Task 8) diffs byte-for-byte against this.
pub fn emit_xmp_tables(tables: &[TableModel]) -> String {
  // Sort by routing namespace so the output is deterministic regardless of
  // `-listx` document order.
  let mut sorted: Vec<&TableModel> = tables.iter().collect();
  sorted.sort_by(|a, b| ns_of(a).cmp(ns_of(b)));

  let mut out = String::new();
  out.push_str("// generated by xtask gen-tables from exiftool -listx 13.59 — DO NOT EDIT\n");
  out.push_str("// (regenerate with `cargo xtask gen-tables --module XMP \\\n");
  out.push_str("//    --out src/formats/xmp/tables_generated.rs`)\n");
  out.push_str("//\n");
  let _ = writeln!(
    out,
    "// Full XMP namespace surface: {} namespaces, {} tags. The hand-written\n\
     // `tables.rs` shadows any tag it already defines (hand wins on key\n\
     // collision); these `GEN_*` slices are the additive fallback + the\n\
     // sole source for namespaces the hand table does not list.",
    sorted.len(),
    sorted.iter().map(|t| t.tags.len()).sum::<usize>(),
  );
  out.push_str("#![allow(clippy::unreadable_literal)]\n\n");
  out.push_str("use super::tables::{Field, PrintConv as P, Writable as W};\n\n");

  let mut map_consts = String::new();
  let mut all_fields = String::new();
  let mut index = String::new();

  for model in &sorted {
    let ns = ns_of(model);
    let ident = ns_ident(ns);

    // Per-namespace fields (each appends its map consts as encountered).
    let mut fields = String::new();
    for t in &model.tags {
      let p = field_print_conv_ns(ns, t, &mut map_consts);
      let _ = writeln!(
        fields,
        "  Field::make(\"{}\", {}, {}, {}),",
        t.id,
        name_arg(t),
        writable_variant(t.ty.as_deref()),
        p
      );
    }

    let _ = writeln!(
      all_fields,
      "/// `{}` (g1 `{}`) — {} tags.",
      model.name,
      model.groups.1,
      model.tags.len()
    );
    let _ = writeln!(all_fields, "pub static {ident}: &[Field] = &[");
    all_fields.push_str(&fields);
    all_fields.push_str("];\n\n");

    let _ = writeln!(index, "  (\"{ns}\", {ident}),");
  }

  out.push_str(&map_consts);
  if !map_consts.is_empty() {
    out.push('\n');
  }
  out.push_str(&all_fields);
  out.push_str(
    "/// Every generated XMP namespace table, keyed by its routing namespace\n\
     /// (the `XMP-<ns>` family-1 group with `XMP-` stripped). Consulted by\n\
     /// `tables::lookup_ns_table` AFTER the hand-written tables.\n",
  );
  out.push_str("pub static GEN_NS_TABLES: &[(&str, &[Field])] = &[\n");
  out.push_str(&index);
  out.push_str("];\n");
  out
}

/// The routing namespace of a table — its `g1` with the `XMP-` prefix stripped
/// (e.g. `XMP-tiff` → `tiff`, `XMP-mwg-rs` → `mwg-rs`). Falls back to the raw
/// `g1` if it does not start with `XMP-`.
fn ns_of(model: &TableModel) -> &str {
  model
    .groups
    .1
    .strip_prefix("XMP-")
    .unwrap_or(&model.groups.1)
}

/// Sanitize a routing namespace to a `SCREAMING_SNAKE` Rust identifier, prefixed
/// `GEN_` (e.g. `mwg-rs` → `GEN_MWG_RS`, `drone-dji` → `GEN_DRONE_DJI`).
fn ns_ident(ns: &str) -> String {
  format!("GEN_{}", sanitize_upper(ns))
}

/// `<NS>_<TAGID>` const name for a value-map, sanitized + uppercased and
/// namespace-prefixed for global uniqueness (e.g. (`tiff`, `Compression`) →
/// `TIFF_COMPRESSION`).
fn map_const_name(ns: &str, tag: &str) -> String {
  format!("{}_{}", sanitize_upper(ns), sanitize_upper(tag))
}

/// Uppercase + replace every non-alphanumeric character with `_` so the result
/// is a valid Rust identifier fragment.
fn sanitize_upper(s: &str) -> String {
  s.chars()
    .map(|c| {
      if c.is_ascii_alphanumeric() {
        c.to_ascii_uppercase()
      } else {
        '_'
      }
    })
    .collect()
}

/// The `Some("Name")` / `None` `name` argument — `None` when the emitted name
/// equals the property key (no ExifTool `Name` remap), else the remapped name.
fn name_arg(t: &crate::listx::TagModel) -> String {
  if t.name == t.id {
    "None".to_string()
  } else {
    format!("Some({:?})", t.name)
  }
}

/// The single-table-path PrintConv expression (uses the table NAME's leaf for
/// the const prefix, matching the original Task-5 emitter).
fn field_print_conv(
  table_name: &str,
  t: &crate::listx::TagModel,
  map_consts: &mut String,
) -> String {
  let leaf = table_name.rsplit("::").next().unwrap_or("XMP");
  print_conv_expr(leaf, t, map_consts)
}

/// The all-namespaces-path PrintConv expression (uses the routing namespace for
/// the const prefix so consts are unique + traceable to their `XMP-<ns>` group).
fn field_print_conv_ns(ns: &str, t: &crate::listx::TagModel, map_consts: &mut String) -> String {
  print_conv_expr(ns, t, map_consts)
}

/// Resolve a tag to its `P::*` expression, appending any value-map const to
/// `map_consts`. `prefix` is the const-name namespace.
fn print_conv_expr(prefix: &str, t: &crate::listx::TagModel, map_consts: &mut String) -> String {
  match resolve_printconv(&t.name, &t.values, t.writable.as_deref()) {
    Conv::Identity => "P::Identity".to_string(),
    Conv::Unported(src) => format!("P::Unported({:?})", format!("{src}:{}", t.name)),
    conv @ (Conv::IntMap | Conv::StrMap) => {
      let values = t.values.as_deref().unwrap_or_default();
      let cname = map_const_name(prefix, &t.id);
      if values.len() > PHF_THRESHOLD {
        emit_phf_map_const(map_consts, &cname, &conv, values);
        format!("P::MapPhf(&{cname})")
      } else {
        emit_slice_map_const(map_consts, &cname, &conv, values);
        let variant = if matches!(conv, Conv::IntMap) {
          "IntMap"
        } else {
          "StrMap"
        };
        format!("P::{variant}({cname})")
      }
    }
  }
}

/// Render `model` as committed Rust source in the **generic** `src/tagtable.rs`
/// vocabulary — `TagDef::new(name, group1, ValueConv::*, PrintConv::*)` entries
/// plus their value-map consts — for the audio/container tag-table formats
/// (FLAC, OGG, AIFF, APE, MPC, DSF, AAC, DV, …). This is the second emit target
/// alongside the XMP [`emit_table`] / [`emit_xmp_tables`] `Field` vocabulary.
///
/// Shape (mirrors the hand tables in `src/formats/*.rs`): one
/// `static <NAME>: TagDef = …;` per tag, the `&[(&str, PrintValue)]` map consts
/// for value-mapped tags, and a `pub fn get(id: TagId) -> Option<&'static
/// TagDef>` whose `match` is keyed by the faithful [`crate::tagtable::TagId`]
/// (numeric `<tag id>` → `TagId::Int`, string id → `TagId::Str`). The caller
/// wraps it in a `TagTable::new(group0, get)`.
///
/// PrintConv mapping into the generic vocabulary (which — unlike XMP's
/// `P::IntMap`/`P::StrMap` — has NO map variants, only a Perl-hash
/// `PrintConv::Hash(PrintConvHash::direct(&[(&str, PrintValue)]))`):
/// * a `<values>` map → `PrintConv::Hash(PrintConvHash::direct(&<CONST>))`,
///   keyed by the STRINGIFIED `$val` exactly as ExifTool indexes `$$conv{$val}`
///   (ExifTool.pm:3605); an all-numeric-label map emits `PrintValue::I64`,
///   otherwise `PrintValue::Str` (the AAC `Channels` `2 => 2` numeric-scalar
///   shape vs the `ProfileType` `0 => 'Main'` string shape);
/// * no map, plain tag → `PrintConv::None`;
/// * a code-valued conv flagged by [`crate::conv_registry`] →
///   `PrintConv::Unported("<group0>:<Tag>")` (faithful raw passthrough).
///
/// `group0` (the family-0 group) and `group1` (per-tag family-1) come from the
/// `<table>` `g0` / `g1`; `-listx` carries no value-map for a code-valued
/// `ValueConv`, so ValueConv is always `ValueConv::None` here (a format that
/// needs a real ValueConv hand-writes it — same incremental rule as the XMP
/// `HANDPORTED` escape hatch).
pub fn emit_tagdef_table(model: &TableModel) -> String {
  let group0 = if model.groups.0.is_empty() {
    model.name.split("::").next().unwrap_or("File")
  } else {
    &model.groups.0
  };
  let group1 = if model.groups.1.is_empty() {
    group0
  } else {
    &model.groups.1
  };
  let leaf = model.name.rsplit("::").next().unwrap_or("TABLE");

  let mut out = String::new();
  out.push_str("// generated by xtask gen-tables from exiftool -listx 13.59 — DO NOT EDIT\n");
  let _ = writeln!(
    out,
    "// (regenerate with `cargo xtask gen-tables --kind tagdef --module {} \\\n\
     //    --out <path>`)",
    module_arg(model)
  );
  out.push_str("// source table: ");
  out.push_str(&model.name);
  out.push('\n');

  let mut map_consts = String::new();
  let mut statics = String::new();
  let mut arms = String::new();
  // `PrintConvHash`/`PrintValue` are only referenced when at least one tag has
  // a `<values>` map; emitting them unconditionally would be an `unused_imports`
  // warning (the `-Dwarnings` gate) for a map-less table (e.g. FLAC StreamInfo).
  let mut needs_hash_imports = false;

  for t in &model.tags {
    let sname = static_ident(leaf, &t.name);
    let pc = tagdef_print_conv(group0, leaf, t, &mut map_consts, &mut needs_hash_imports);
    let _ = writeln!(
      statics,
      "static {sname}: TagDef =\n  TagDef::new({:?}, {:?}, ValueConv::None, {});",
      t.name, group1, pc
    );
    let key = tagid_key(&t.id);
    let _ = writeln!(arms, "    {key} => Some(&{sname}),");
  }

  // Adaptive import line: `PrintConvHash`/`PrintValue` only when a value-map
  // is present, so a map-less table is `unused_imports`-clean under `-Dwarnings`.
  out.push('\n');
  if needs_hash_imports {
    out.push_str(
      "use crate::tagtable::{PrintConv, PrintConvHash, PrintValue, TagDef, TagId, ValueConv};\n\n",
    );
  } else {
    out.push_str("use crate::tagtable::{PrintConv, TagDef, TagId, ValueConv};\n\n");
  }

  out.push_str(&map_consts);
  if !map_consts.is_empty() {
    out.push('\n');
  }
  out.push_str(&statics);
  out.push('\n');
  let _ = writeln!(
    out,
    "/// `{}` (g0 `{}`, g1 `{}`) — {} tags.\n\
     pub fn get(id: TagId) -> Option<&'static TagDef> {{\n  \
       match id {{\n{}    _ => None,\n  }}\n}}",
    model.name,
    group0,
    group1,
    model.tags.len(),
    arms,
  );
  out
}

/// The `TagId` match key for a tag id: a numeric id → `TagId::Int(<n>)`, any
/// other (string) id → `TagId::Str("<id>")` — faithful to how ExifTool indexes
/// its tag-table hash (numeric vs string Perl keys, cf. AAC `'Bit016-017'`).
fn tagid_key(id: &str) -> String {
  if let Ok(n) = id.parse::<i64>() {
    format!("TagId::Int({n})")
  } else {
    format!("TagId::Str({id:?})")
  }
}

/// The `static <IDENT>: TagDef` name for a tag — `<LEAF>_<NAME>`, sanitized +
/// uppercased from the emitted tag NAME (readable, vs an opaque numeric id;
/// e.g. (`StreamInfo`, `SampleRate`) → `STREAMINFO_SAMPLERATE`,
/// (`Main`, `ChannelCount`) → `MAIN_CHANNELCOUNT`). The `get` match still keys
/// by the faithful [`tagid_key`], so an id↔name remap is preserved.
fn static_ident(leaf: &str, name: &str) -> String {
  format!("{}_{}", sanitize_upper(leaf), sanitize_upper(name))
}

/// Resolve a tag to its generic `PrintConv::*` expression, appending any
/// `&[(&str, PrintValue)]` map const to `map_consts`. `group0` is the
/// provenance namespace for an `Unported` marker; `leaf` prefixes the const.
fn tagdef_print_conv(
  group0: &str,
  leaf: &str,
  t: &crate::listx::TagModel,
  map_consts: &mut String,
  needs_hash_imports: &mut bool,
) -> String {
  match resolve_printconv(&t.name, &t.values, t.writable.as_deref()) {
    Conv::Identity => "PrintConv::None".to_string(),
    Conv::Unported(_) => format!("PrintConv::Unported({:?})", format!("{group0}:{}", t.name)),
    conv @ (Conv::IntMap | Conv::StrMap) => {
      *needs_hash_imports = true;
      let values = t.values.as_deref().unwrap_or_default();
      // `_MAP` suffix keeps the value-map const in a distinct namespace from
      // the tag's `static <LEAF>_<NAME>: TagDef` (which shares the base ident),
      // so the two never collide (e.g. DSF `FormatID` → `MAIN_FORMATID_MAP`
      // const + `MAIN_FORMATID` TagDef).
      let cname = format!("{}_MAP", map_const_name(leaf, &t.name));
      emit_print_hash_const(map_consts, &cname, &conv, values);
      format!("PrintConv::Hash(PrintConvHash::direct(&{cname}))")
    }
  }
}

/// Emit a generic-vocabulary value-map const: `&[(&str, PrintValue)]` keyed by
/// the STRINGIFIED `$val` (ExifTool.pm:3605). Each LABEL's `PrintValue` variant
/// is decided PER ENTRY, faithfully mirroring ExifTool's Perl scalars + their
/// `-j` JSON rendering: a label that is a bare integer (e.g. AAC `Channels`
/// `1 => 1`) → `PrintValue::I64` (emitted as a JSON number); anything else
/// (e.g. `6 => '5+1'`, `0 => 'Main'`) → `PrintValue::Str`. ExifTool stores `1`
/// and `'5+1'` in the SAME conv hash with DIFFERENT scalar types, so an
/// all-or-nothing rule would mis-type the numeric entries; the hand tables
/// (`AAC::Main` `Channels`) carry exactly this mix. The KEY is always the raw
/// scalar string so the runtime `$$conv{$val}` exact-string lookup is faithful.
fn emit_print_hash_const(buf: &mut String, name: &str, _conv: &Conv, values: &[(String, String)]) {
  let entries: Vec<String> = values
    .iter()
    .map(|(k, v)| {
      if v.parse::<i64>().is_ok() {
        format!("({k:?}, PrintValue::I64({v}))")
      } else {
        format!("({k:?}, PrintValue::Str({v:?}))")
      }
    })
    .collect();
  let _ = writeln!(
    buf,
    "static {name}: &[(&str, PrintValue)] = &[{}];",
    entries.join(", ")
  );
}

/// Map a `-listx` `<tag type=…>` to its [`super::tables::Writable`] variant.
/// An ABSENT type → `W::None` (no explicit `Writable`; XMPAutoConv applies);
/// the `?` ("integer?"-style undeclared) and `struct` (a container, never a
/// scalar leaf) types — and any unrecognized type — map to `W::Str`, which
/// disables XMPAutoConv exactly like the hand table's `{}`→`W::Str` mapping.
fn writable_variant(ty: Option<&str>) -> &'static str {
  match ty {
    None => "W::None",
    Some("integer") => "W::Integer",
    Some("rational") => "W::Rational",
    Some("real") => "W::Real",
    Some("boolean") => "W::Boolean",
    Some("date") => "W::Date",
    Some("lang-alt") => "W::LangAlt",
    Some("string") => "W::Str",
    Some(_) => "W::Str",
  }
}

/// Emit a sorted-slice PrintConv map const (`&[(i64,&str)]` / `&[(&str,&str)]`).
fn emit_slice_map_const(buf: &mut String, name: &str, conv: &Conv, values: &[(String, String)]) {
  match conv {
    Conv::IntMap => {
      let entries: Vec<String> = values
        .iter()
        .map(|(k, v)| format!("({k}, {v:?})"))
        .collect();
      let _ = writeln!(
        buf,
        "const {name}: &[(i64, &str)] = &[{}];",
        entries.join(", ")
      );
    }
    Conv::StrMap => {
      let entries: Vec<String> = values
        .iter()
        .map(|(k, v)| format!("({k:?}, {v:?})"))
        .collect();
      let _ = writeln!(
        buf,
        "const {name}: &[(&str, &str)] = &[{}];",
        entries.join(", ")
      );
    }
    Conv::Identity | Conv::Unported(_) => {}
  }
}

/// Emit a `phf::Map<&'static str, &'static str>` const for a LARGE value-map,
/// keyed by the RAW scalar string (an `i64` key is stringified to its decimal
/// form) so the lookup is the faithful `$$conv{$val}` exact-string match. Built
/// by `phf_codegen` at generation time → a perfect-hash literal with no runtime
/// build cost.
fn emit_phf_map_const(buf: &mut String, name: &str, _conv: &Conv, values: &[(String, String)]) {
  let mut m = phf_codegen::Map::new();
  for (k, v) in values {
    // Both int- and string-keyed maps key by the raw scalar STRING (an int key
    // is already its decimal text in `-listx`), matching the slice path's
    // `k.to_string() == numeric` lookup semantics.
    m.entry(k.as_str(), &format!("{v:?}"));
  }
  let _ = writeln!(
    buf,
    "static {name}: phf::Map<&'static str, &'static str> = {};",
    m.build()
  );
}

/// The `--module` arg that regenerates a single table — the `g1` group when set
/// (e.g. `XMP-tiff`), else the raw table name.
fn module_arg(model: &TableModel) -> &str {
  if model.groups.1.is_empty() {
    &model.name
  } else {
    &model.groups.1
  }
}

#[cfg(test)]
mod tests {
  use super::*;
  use crate::listx::{TableModel, TagModel};

  fn tag(id: &str, name: &str, ty: &str, values: Option<Vec<(&str, &str)>>) -> TagModel {
    TagModel {
      id: id.to_string(),
      name: name.to_string(),
      ty: Some(ty.to_string()),
      writable: Some("true".to_string()),
      values: values.map(|v| {
        v.into_iter()
          .map(|(k, val)| (k.to_string(), val.to_string()))
          .collect()
      }),
    }
  }

  #[test]
  fn emits_field_make_with_intmap_and_provenance() {
    let model = TableModel {
      name: "XMP::tiff".to_string(),
      groups: ("XMP".to_string(), "XMP-tiff".to_string()),
      tags: vec![
        tag(
          "Compression",
          "Compression",
          "integer",
          Some(vec![("1", "Uncompressed"), ("6", "JPEG (old-style)")]),
        ),
        // A `Name` remap (key != name) → emits `Some("ImageHeight")`.
        tag("ImageLength", "ImageHeight", "integer", None),
        // A plain string tag → `W::Str, P::Identity`.
        tag("Make", "Make", "string", None),
      ],
    };
    let src = emit_table(&model);

    // Provenance header.
    assert!(src.contains("// generated by xtask gen-tables from exiftool -listx"));
    // The IntMap field + its sorted-slice const, in the real vocabulary.
    assert!(
      src.contains(r#"Field::make("Compression", None, W::Integer, P::IntMap(TIFF_COMPRESSION))"#)
    );
    assert!(src.contains(
      r#"const TIFF_COMPRESSION: &[(i64, &str)] = &[(1, "Uncompressed"), (6, "JPEG (old-style)")];"#
    ));
    // Name remap → Some("ImageHeight").
    assert!(
      src.contains(r#"Field::make("ImageLength", Some("ImageHeight"), W::Integer, P::Identity)"#)
    );
    // Plain string tag.
    assert!(src.contains(r#"Field::make("Make", None, W::Str, P::Identity)"#));
    // The table is exposed as a `pub static FIELDS: &[Field]`.
    assert!(src.contains("pub static FIELDS: &[Field] = &["));
  }

  #[test]
  fn all_xmp_emits_per_namespace_statics_and_index() {
    let tables = vec![
      TableModel {
        name: "XMP::tiff".to_string(),
        groups: ("XMP".to_string(), "XMP-tiff".to_string()),
        tags: vec![tag("Make", "Make", "string", None)],
      },
      TableModel {
        name: "MWG::Regions".to_string(),
        groups: ("XMP".to_string(), "XMP-mwg-rs".to_string()),
        tags: vec![tag("Regions", "Regions", "struct", None)],
      },
    ];
    let src = emit_xmp_tables(&tables);
    // Per-namespace statics, hyphen-sanitized identifiers.
    assert!(src.contains("pub static GEN_TIFF: &[Field] = &["));
    assert!(src.contains("pub static GEN_MWG_RS: &[Field] = &["));
    // The index keys by the routing namespace (XMP- stripped).
    assert!(src.contains(r#"  ("tiff", GEN_TIFF),"#));
    assert!(src.contains(r#"  ("mwg-rs", GEN_MWG_RS),"#));
    assert!(src.contains("pub static GEN_NS_TABLES: &[(&str, &[Field])] = &["));
    // A `struct`-typed container maps to W::Str (no scalar auto-conv).
    assert!(src.contains(r#"Field::make("Regions", None, W::Str, P::Identity)"#));
  }

  #[test]
  fn large_map_emits_phf() {
    // > PHF_THRESHOLD string-keyed entries → a phf::Map, looked up by raw key.
    let big: Vec<(&str, &str)> = (0..30)
      .map(|i| {
        let s: &'static str = Box::leak(format!("K{i}").into_boxed_str());
        let v: &'static str = Box::leak(format!("V{i}").into_boxed_str());
        (s, v)
      })
      .collect();
    let model = TableModel {
      name: "PLUS::XMP".to_string(),
      groups: ("XMP".to_string(), "XMP-plus".to_string()),
      tags: vec![tag("Code", "Code", "string", Some(big))],
    };
    let src = emit_xmp_tables(&model_vec(model));
    assert!(src.contains("static PLUS_CODE: phf::Map<&'static str, &'static str> ="));
    assert!(src.contains("P::MapPhf(&PLUS_CODE)"));
  }

  fn model_vec(m: TableModel) -> Vec<TableModel> {
    vec![m]
  }

  #[test]
  fn tagdef_mode_emits_generic_tagtable_vocabulary() {
    // Faithful to `%DSF::Main` (DSF.pm) + `%AAC::Main` shapes: a numeric-id
    // tag with an int-keyed string map, a numeric-id plain tag, a string-id
    // tag with a numeric-LABEL map (AAC `Channels` `2 => 2`), and a string-id
    // plain tag — proving the generic `TagDef::new` / `PrintConvHash::direct`
    // / `TagId::{Int,Str}` rendering.
    let model = TableModel {
      name: "DSF::Main".to_string(),
      groups: ("File".to_string(), "File".to_string()),
      tags: vec![
        // int-keyed string map → PrintConv::Hash(direct), key STRINGIFIED.
        tag("4", "FormatID", "int32u", Some(vec![("0", "DSD Raw")])),
        // plain numeric-id tag → PrintConv::None.
        tag("6", "ChannelCount", "int32u", None),
        // string-id tag with a MIXED-type map (the real AAC `Channels` shape:
        // bare numbers `1 => 1` AND strings `6 => '5+1'`) → per-entry
        // PrintValue::I64 vs PrintValue::Str, faithful to the Perl scalars.
        tag(
          "Bit023-025",
          "Channels",
          "?",
          Some(vec![("1", "1"), ("2", "2"), ("6", "5+1")]),
        ),
        // plain string-id tag → TagId::Str + PrintConv::None.
        tag("Encoder", "Encoder", "?", None),
      ],
    };
    let src = emit_tagdef_table(&model);

    // Provenance header + the generic `tagtable` import (NOT the XMP `Field`).
    // This table HAS value-maps → the full import including PrintConvHash/Value.
    assert!(src.contains("// generated by xtask gen-tables from exiftool -listx"));
    assert!(src.contains(
      "use crate::tagtable::{PrintConv, PrintConvHash, PrintValue, TagDef, TagId, ValueConv};"
    ));

    // int-keyed string map → a `&[(&str, PrintValue)]` const (key stringified,
    // const named `<NAME>_MAP`) + a `PrintConv::Hash(PrintConvHash::direct(&…))`.
    assert!(src.contains(
      r#"static MAIN_FORMATID_MAP: &[(&str, PrintValue)] = &[("0", PrintValue::Str("DSD Raw"))];"#
    ));
    assert!(src.contains(
      r#"TagDef::new("FormatID", "File", ValueConv::None, PrintConv::Hash(PrintConvHash::direct(&MAIN_FORMATID_MAP)))"#
    ));

    // MIXED-type map → per-entry PrintValue: numeric labels `I64`, the `"5+1"`
    // label `Str` — exactly the hand-written `AAC::Main` `Channels` shape.
    assert!(src.contains(
      r#"static MAIN_CHANNELS_MAP: &[(&str, PrintValue)] = &[("1", PrintValue::I64(1)), ("2", PrintValue::I64(2)), ("6", PrintValue::Str("5+1"))];"#
    ));

    // plain tags → PrintConv::None.
    assert!(
      src.contains(r#"TagDef::new("ChannelCount", "File", ValueConv::None, PrintConv::None)"#)
    );
    assert!(src.contains(r#"TagDef::new("Encoder", "File", ValueConv::None, PrintConv::None)"#));

    // The `get` fn keys numeric ids by `TagId::Int`, string ids by `TagId::Str`;
    // the static is named by the NAME, the match key is the faithful id.
    assert!(src.contains("pub fn get(id: TagId) -> Option<&'static TagDef> {"));
    assert!(src.contains("TagId::Int(4) => Some(&MAIN_FORMATID),"));
    assert!(src.contains("TagId::Int(6) => Some(&MAIN_CHANNELCOUNT),"));
    assert!(src.contains(r#"TagId::Str("Bit023-025") => Some(&MAIN_CHANNELS),"#));
    assert!(src.contains(r#"TagId::Str("Encoder") => Some(&MAIN_ENCODER),"#));
    assert!(src.contains("_ => None,"));
  }

  #[test]
  fn tagdef_mode_mapless_table_uses_minimal_imports() {
    // A table with no value-maps (e.g. FLAC StreamInfo) must NOT import
    // `PrintConvHash`/`PrintValue` — otherwise the committed file trips the
    // `-Dwarnings` `unused_imports` gate.
    let model = TableModel {
      name: "FLAC::StreamInfo".to_string(),
      groups: ("FLAC".to_string(), "FLAC".to_string()),
      tags: vec![tag("Bit080-099", "SampleRate", "?", None)],
    };
    let src = emit_tagdef_table(&model);
    assert!(src.contains("use crate::tagtable::{PrintConv, TagDef, TagId, ValueConv};"));
    assert!(!src.contains("PrintConvHash"));
    assert!(!src.contains("PrintValue"));
  }

  #[test]
  fn tagdef_mode_marks_code_valued_conv_unported() {
    // A map-less tag pinned by the curated HANDPORTED list (the test probe) →
    // `PrintConv::Unported("<group0>:<Tag>")`, the faithful raw-passthrough
    // marker in the generic vocabulary (parallel to the XMP `P::Unported`).
    let model = TableModel {
      name: "AIFF::Common".to_string(),
      groups: ("AIFF".to_string(), "AIFF".to_string()),
      tags: vec![tag(
        "__xtask_unported_probe__",
        "__xtask_unported_probe__",
        "?",
        None,
      )],
    };
    let src = emit_tagdef_table(&model);
    assert!(src.contains(r#"PrintConv::Unported("AIFF:__xtask_unported_probe__")"#));
  }
}
