// SPDX-License-Identifier: GPL-3.0-or-later
// exifast — a 1:1 Rust port of ExifTool (Phil Harvey). See THIRD_PARTY.md.

//! Render a [`TableModel`] as committed Rust source in the XMP module's
//! `Field::make(...)` vocabulary (`Writable as W` / `PrintConv as P`).
//!
//! The emitted file is a child module of `src/formats/xmp/` (Task 7), so it
//! `use super::tables::{Field, PrintConv as P, Writable as W}` and the
//! crate-local `Field::make` constructor is in scope. Each PrintConv map is a
//! sorted `&[(i64, &str)]` / `&[(&str, &str)]` slice const (the phf path for
//! large maps is Task 7); a code-valued, map-less conv flagged by the
//! [`crate::conv_registry`] becomes `P::Unported("<module>:<Tag>")` so it is
//! faithfully passed through rather than guessed.

use crate::conv_registry::{resolve_printconv, Conv};
use crate::listx::TableModel;

/// Render `model` as committed Rust source for the XMP module.
pub fn emit_table(model: &TableModel) -> String {
  let mut out = String::new();
  out.push_str("// generated by xtask gen-tables from exiftool -listx 13.59 — DO NOT EDIT\n");
  out.push_str(&format!(
    "// (regenerate with `cargo xtask gen-tables --module {}`)\n",
    module_arg(model)
  ));
  out.push_str("// source table: ");
  out.push_str(&model.name);
  out.push('\n');
  out.push_str("\nuse super::tables::{Field, PrintConv as P, Writable as W};\n\n");

  let mut map_consts = String::new();
  let mut fields = String::new();
  for t in &model.tags {
    let name_arg = if t.name == t.id {
      "None".to_string()
    } else {
      format!("Some(\"{}\")", t.name)
    };
    let w = writable_variant(t.ty.as_deref());
    let conv = resolve_printconv(&t.name, &t.values, t.writable.as_deref());
    let p = match &conv {
      Conv::Identity => "P::Identity".to_string(),
      Conv::Unported(src) => format!("P::Unported(\"{}:{}\")", src, t.name),
      Conv::IntMap | Conv::StrMap => {
        let cname = const_name(&model.name, &t.id);
        emit_map_const(
          &mut map_consts,
          &cname,
          &conv,
          t.values.as_deref().unwrap_or_default(),
        );
        let variant = if matches!(conv, Conv::IntMap) {
          "IntMap"
        } else {
          "StrMap"
        };
        format!("P::{variant}({cname})")
      }
    };
    fields.push_str(&format!(
      "  Field::make(\"{}\", {}, {}, {}),\n",
      t.id, name_arg, w, p
    ));
  }

  out.push_str(&map_consts);
  if !map_consts.is_empty() {
    out.push('\n');
  }
  out.push_str("pub static FIELDS: &[Field] = &[\n");
  out.push_str(&fields);
  out.push_str("];\n");
  out
}

/// The `--module` arg that regenerates this table — the `g1` group when set
/// (e.g. `XMP-tiff`), else the raw table name.
fn module_arg(model: &TableModel) -> &str {
  if model.groups.1.is_empty() {
    &model.name
  } else {
    &model.groups.1
  }
}

/// Map a `-listx` `<tag type=…>` to its [`super::tables::Writable`] variant.
/// An ABSENT type → `W::None` (no explicit `Writable`; XMPAutoConv applies);
/// a present-but-unrecognized type falls back to `W::Str`.
fn writable_variant(ty: Option<&str>) -> &'static str {
  match ty {
    None => "W::None",
    Some("integer") => "W::Integer",
    Some("rational") => "W::Rational",
    Some("real") => "W::Real",
    Some("boolean") => "W::Boolean",
    Some("date") => "W::Date",
    Some("lang-alt") => "W::LangAlt",
    Some("string") => "W::Str",
    Some(_) => "W::Str",
  }
}

/// Derive a `SCREAMING_SNAKE` const name from the table + tag, e.g.
/// (`XMP::tiff`, `Compression`) → `TIFF_COMPRESSION`.
fn const_name(table: &str, tag: &str) -> String {
  let leaf = table.rsplit("::").next().unwrap_or("XMP");
  format!("{}_{}", leaf.to_uppercase(), tag.to_uppercase())
}

/// Emit a sorted-slice PrintConv map const for `conv` into `buf`.
fn emit_map_const(buf: &mut String, name: &str, conv: &Conv, values: &[(String, String)]) {
  match conv {
    Conv::IntMap => {
      let entries: Vec<String> = values
        .iter()
        .map(|(k, v)| format!("({}, {:?})", k, v))
        .collect();
      buf.push_str(&format!(
        "const {}: &[(i64, &str)] = &[{}];\n",
        name,
        entries.join(", ")
      ));
    }
    Conv::StrMap => {
      let entries: Vec<String> = values
        .iter()
        .map(|(k, v)| format!("({:?}, {:?})", k, v))
        .collect();
      buf.push_str(&format!(
        "const {}: &[(&str, &str)] = &[{}];\n",
        name,
        entries.join(", ")
      ));
    }
    Conv::Identity | Conv::Unported(_) => {}
  }
}

#[cfg(test)]
mod tests {
  use super::*;
  use crate::listx::{TableModel, TagModel};

  fn tag(id: &str, name: &str, ty: &str, values: Option<Vec<(&str, &str)>>) -> TagModel {
    TagModel {
      id: id.to_string(),
      name: name.to_string(),
      ty: Some(ty.to_string()),
      writable: Some("true".to_string()),
      values: values.map(|v| {
        v.into_iter()
          .map(|(k, val)| (k.to_string(), val.to_string()))
          .collect()
      }),
    }
  }

  #[test]
  fn emits_field_make_with_intmap_and_provenance() {
    let model = TableModel {
      name: "XMP::tiff".to_string(),
      groups: ("XMP".to_string(), "XMP-tiff".to_string()),
      tags: vec![
        tag(
          "Compression",
          "Compression",
          "integer",
          Some(vec![("1", "Uncompressed"), ("6", "JPEG (old-style)")]),
        ),
        // A `Name` remap (key != name) → emits `Some("ImageHeight")`.
        tag("ImageLength", "ImageHeight", "integer", None),
        // A plain string tag → `W::Str, P::Identity`.
        tag("Make", "Make", "string", None),
      ],
    };
    let src = emit_table(&model);

    // Provenance header.
    assert!(src.contains("// generated by xtask gen-tables from exiftool -listx"));
    // The IntMap field + its sorted-slice const, in the real vocabulary.
    assert!(
      src.contains(r#"Field::make("Compression", None, W::Integer, P::IntMap(TIFF_COMPRESSION))"#)
    );
    assert!(src.contains(
      r#"const TIFF_COMPRESSION: &[(i64, &str)] = &[(1, "Uncompressed"), (6, "JPEG (old-style)")];"#
    ));
    // Name remap → Some("ImageHeight").
    assert!(
      src.contains(r#"Field::make("ImageLength", Some("ImageHeight"), W::Integer, P::Identity)"#)
    );
    // Plain string tag.
    assert!(src.contains(r#"Field::make("Make", None, W::Str, P::Identity)"#));
    // The table is exposed as a `pub static FIELDS: &[Field]`.
    assert!(src.contains("pub static FIELDS: &[Field] = &["));
  }
}
