#!/usr/bin/env perl
# Emit src/exif/geotiff/tables.rs from GeoTiff.pm — the GeoKey id->name map +
# the static int->label PrintConv slices (shared %epsg_* + per-key inline),
# deduplicated (Perl last-wins) and sorted by key for binary search.
use strict; use warnings;
my $file = shift or die "usage: $0 GeoTiff.pm\n";
open my $fh,'<',$file or die "open $file: $!\n";
my @lines=<$fh>; close $fh;

sub rs { my $s=shift; $s =~ s/\\/\\\\/g; $s =~ s/"/\\"/g; return $s; }

# harvest INT=>'STR' rows in [lo,hi]; last-wins; return hashref + first-seen order
sub harvest {
  my ($lo,$hi)=@_; my %h;
  for (my $i=$lo;$i<=$hi;$i++){
    if ($lines[$i] =~ /^\s*(-?\d+)\s*=>\s*'((?:[^'\\]|\\.)*)'\s*,?\s*$/){
      $h{$1}=$2;  # last-wins
    }
  }
  return \%h;
}
# emit a sorted-by-numeric-key Rust slice body from a harvested hash
sub emit_slice {
  my ($h)=@_; my @out;
  for my $k (sort { $a <=> $b } keys %$h) {
    push @out, sprintf("  (%d, \"%s\"),", $k, rs($h->{$k}));
  }
  return join("\n",@out);
}

# locate shared hashes
my %sr;
for (my $i=0;$i<@lines;$i++){
  if ($lines[$i] =~ /^my\s+%(epsg_units|epsg_vertcs)\s*=\s*\(/){
    my $n=$1; my $lo=$i+1; my $j=$i;
    while ($j<@lines && $lines[$j] !~ /^\);/){$j++}
    $sr{$n}=[$lo,$j-1];
  }
}
# Main bounds
my ($mlo,$mhi);
for (my $i=0;$i<@lines;$i++){ if($lines[$i]=~/^%Image::ExifTool::GeoTiff::Main\s*=\s*\(/){$mlo=$i+1;last} }
for (my $j=$mlo;$j<@lines;$j++){ if($lines[$j]=~/^\);/){$mhi=$j-1;last} }

# walk keys
my @keys; my $depth=0; my $i=$mlo;
while ($i<=$mhi){
  my $l=$lines[$i];
  if ($depth==0 && $l =~ /^\s{4}(\d+)\s*=>\s*(.*)$/){
    my ($tag,$rest)=($1,$2);
    if ($rest =~ /^'([^']*)'\s*,?\s*$/){
      push @keys,{tag=>$tag,name=>$1,conv=>{kind=>'none'}}; $i++; next;
    } elsif ($rest =~ /^\{/){
      my $bdepth=1; my $name; my $pck='none'; my ($plo,$phi,$pref); $i++;
      while ($i<=$mhi && $bdepth>0){
        my $bl=$lines[$i];
        if ($bdepth==1 && $bl=~/Name\s*=>\s*'([^']*)'/){$name=$1}
        if ($bdepth==1 && $bl=~/PrintConv\s*=>\s*\\%(epsg_units|epsg_vertcs)/){$pck='ref';$pref=$1}
        if ($bdepth==1 && $bl=~/PrintConv\s*=>\s*\{/){
          $pck='inline'; $plo=$i+1; my $id=1; my $k=$i+1;
          while ($k<=$mhi && $id>0){
            my $kl=$lines[$k]; $id += ($kl=~tr/{//) - ($kl=~tr/}//);
            if($id==0){$phi=$k-1;last} $k++;
          }
        }
        $bdepth += ($bl=~tr/{//) - ($bl=~tr/}//); $i++;
      }
      my $c={kind=>$pck};
      if($pck eq 'inline'){$c->{lo}=$plo;$c->{hi}=$phi}
      if($pck eq 'ref'){$c->{name}=$pref}
      push @keys,{tag=>$tag,name=>($name//"Tag$tag"),conv=>$c}; next;
    }
  }
  $depth += ($l=~tr/{//) - ($l=~tr/}//); $i++;
}

# === EMIT RUST ===
print <<'HDR';
// SPDX-License-Identifier: GPL-3.0-or-later
// exifast — a 1:1 Rust port of ExifTool (Phil Harvey). See THIRD_PARTY.md.
//
// GENERATED by tools/gen_geotiff_tables.pl from
// `Image::ExifTool::GeoTiff` (`GeoTiff.pm`, $VERSION 1.12). DO NOT EDIT BY HAND
// — re-run the extractor against the bundled ExifTool to regenerate.
//
// Each GeoKey's static int->label `PrintConv` hash is transcribed verbatim into
// a `(i64, &str)` slice, SORTED by key (for `binary_search_by_key`) and
// deduplicated under Perl's last-wins hash semantics (a duplicate literal key in
// the Perl source keeps the LAST value). The two shared hashes (`%epsg_units`,
// `%epsg_vertcs`) are emitted once and referenced by the keys that point at
// them (`GeogLinearUnits`/`…AngularUnits`/`…AzimuthUnits`/`ProjLinearUnits`/
// `VerticalUnits`/`ChartDepthUnits` → units; `VerticalCSType`/`VerticalDatum` →
// vertcs). A key whose decoded value is absent from its slice renders the RAW
// INT (ExifTool's HASH-PrintConv miss with no `OTHER`/`BITMASK`).

//! GeoTiff GeoKey id->name map + the per-key `PrintConv` int->label slices,
//! mechanically transcribed from `%Image::ExifTool::GeoTiff::Main`
//! (`GeoTiff.pm`). See the module header for the generation contract.

#![allow(clippy::unreadable_literal)]

HDR

# shared tables
for my $sh (qw(epsg_units epsg_vertcs)){
  my $h=harvest(@{$sr{$sh}});
  my $UP = uc $sh;
  my $n = scalar keys %$h;
  print "/// The shared `%$sh` EPSG table ($n entries) — referenced by multiple GeoKeys.\n";
  print "pub(crate) static $UP: &[(i64, &str)] = &[\n";
  print emit_slice($h), "\n];\n\n";
}

# per-key inline tables
for my $k (@keys){
  next unless $k->{conv}{kind} eq 'inline';
  my $h=harvest($k->{conv}{lo},$k->{conv}{hi});
  my $n=scalar keys %$h;
  my $UP = uc($k->{name}); $UP =~ s/[^A-Z0-9]/_/g;
  print "/// `$k->{name}` (GeoKey $k->{tag}) PrintConv ($n entries).\n";
  print "static $UP: &[(i64, &str)] = &[\n";
  print emit_slice($h), "\n];\n\n";
}

# the GeoKey descriptor: id, name, optional printconv slice
print "/// One GeoKey: its id, tag name, and (optional) int->label PrintConv slice.\n";
print "/// `print_conv` is `None` for the name-only keys (Citations + numeric values).\n";
print "pub(crate) struct GeoKeyDef {\n";
print "  /// The GeoKey id (the `%GeoTiff::Main` hash key).\n";
print "  pub(crate) id: u16,\n";
print "  /// The tag Name (`Name => '…'`).\n";
print "  pub(crate) name: &'static str,\n";
print "  /// The int->label PrintConv slice, or `None` for a name-only key.\n";
print "  pub(crate) print_conv: Option<&'static [(i64, &'static str)]>,\n";
print "}\n\n";

# the key table sorted by id
print "/// Every `%GeoTiff::Main` GeoKey, SORTED by id for `binary_search_by_key`.\n";
print "/// (`GeoTiffVersion` id 1 is the synthetic version key — emitted by the\n";
print "/// processor, never decoded from a GeoKey entry, but kept here for the name.)\n";
print "pub(crate) static GEO_KEYS: &[GeoKeyDef] = &[\n";
for my $k (sort { $a->{tag} <=> $b->{tag} } @keys){
  my $c=$k->{conv};
  my $pc;
  if ($c->{kind} eq 'inline'){ my $UP=uc($k->{name}); $UP=~s/[^A-Z0-9]/_/g; $pc="Some($UP)"; }
  elsif ($c->{kind} eq 'ref'){ $pc="Some(".uc($c->{name}).")"; }
  else { $pc="None"; }
  printf "  GeoKeyDef { id: %d, name: \"%s\", print_conv: %s },\n", $k->{tag}, rs($k->{name}), $pc;
}
print "];\n";
